.TH "Config" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static FString \fBGetIdFilePath\fP ()"
.br
.ti -1c
.RI "static FString \fBGetMasterDirectory\fP ()"
.br
.ti -1c
.RI "static FString \fBGetScriptDirectory\fP ()"
.br
.ti -1c
.RI "static FString \fBGetDLCDirectory\fP ()"
.br
.in -1c
.SS "静的公開変数類"

.in +1c
.ti -1c
.RI "static const FString \fBServerHost\fP = '218\&.220\&.121\&.112'"
.br
.ti -1c
.RI "static const int \fBServerPort\fP = 4424"
.br
.ti -1c
.RI "static const FString \fBMasterURL\fP = 'http://218\&.220\&.121\&.112/~Master/anpanmmomaster/main/'"
.br
.ti -1c
.RI "static const FString \fBScriptURL\fP = 'http://218\&.220\&.121\&.112/~Master/anpanmmoscript/'"
.br
.ti -1c
.RI "static const FString \fBDLCURL\fP = 'http://218\&.220\&.121\&.112/~Master/anpanmmo/dlc/'"
.br
.in -1c
.SH "詳解"
.PP 
定数定義\&. 
.SH "関数詳解"
.PP 
.SS "FString Config::GetDLCDirectory ()\fC [static]\fP"

.SS "FString Config::GetIdFilePath ()\fC [static]\fP"

.SS "FString Config::GetMasterDirectory ()\fC [static]\fP"

.SS "FString Config::GetScriptDirectory ()\fC [static]\fP"

.SH "メンバ詳解"
.PP 
.SS "const FString Config::DLCURL = 'http://218\&.220\&.121\&.112/~Master/anpanmmo/dlc/'\fC [static]\fP"

.SS "const FString Config::MasterURL = 'http://218\&.220\&.121\&.112/~Master/anpanmmomaster/main/'\fC [static]\fP"

.SS "const FString Config::ScriptURL = 'http://218\&.220\&.121\&.112/~Master/anpanmmoscript/'\fC [static]\fP"

.SS "const FString Config::ServerHost = '218\&.220\&.121\&.112'\fC [static]\fP"

.SS "const int Config::ServerPort = 4424\fC [static]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
