.TH "FQuestData" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FQuestData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestMenu\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "uint32 \fBQuestId\fP"
.br
.ti -1c
.RI "FString \fBName\fP"
.br
.ti -1c
.RI "FString \fBExplain\fP"
.br
.ti -1c
.RI "bool \fBbIsMainQuest\fP"
.br
.ti -1c
.RI "bool \fBbIsActive\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "bool FQuestData::bIsActive"

.SS "bool FQuestData::bIsMainQuest"

.SS "FString FQuestData::Explain"

.SS "FString FQuestData::Name"

.SS "uint32 FQuestData::QuestId"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
