.TH "D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/MemoryStream/MemoryStreamReader.cpp" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/MemoryStream/MemoryStreamReader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MemoryStreamReader\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'EndianConverter\&.h'\fP
.br

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
