.TH "D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Active/UI/Menu/Notice/NoticeMenuWidget.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Active/UI/Menu/Notice/NoticeMenuWidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'UI/Menu/LayeredMenuWidgetBase\&.h'\fP
.br
\fC#include 'NoticeMenuWidget\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBUNoticeBase\fP"
.br
.ti -1c
.RI "class \fBUPartyInviteNotice\fP"
.br
.ti -1c
.RI "class \fBUNoticeMenuItem\fP"
.br
.ti -1c
.RI "class \fBUPartyInviteNoticeItem\fP"
.br
.ti -1c
.RI "class \fBUNoticeMenuWidget\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBENoticeType\fP : uint8 { \fBENoticeType::None\fP, \fBENoticeType::PartyInvite\fP }"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBENoticeType\fP : uint8\fC [strong]\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIPartyInvite \fP\fP
.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
