.TH "PacketAreaMoveResponse" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketAreaMoveResponse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketAreaMoveResponse\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBResultCode\fP { \fBSuccess\fP, \fBFatal\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketAreaMoveResponse\fP ()"
.br
.ti -1c
.RI "\fBPacketAreaMoveResponse\fP (\fBu8\fP InResult)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBResult\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBPacketAreaMoveResponse::ResultCode\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIFatal \fP\fP
.SH "構築子と解体子"
.PP 
.SS "PacketAreaMoveResponse::PacketAreaMoveResponse ()\fC [inline]\fP"

.SS "PacketAreaMoveResponse::PacketAreaMoveResponse (\fBu8\fP InResult)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketAreaMoveResponse::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketAreaMoveResponse::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu8\fP PacketAreaMoveResponse::Result"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
