.TH "UFadeScreen" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UFadeScreen
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FadeScreen\&.h>\fP
.PP
UUserWidgetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUFadeScreen\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UFadeScreen\fP ()"
.br
.ti -1c
.RI "virtual void \fBNativeTick\fP (const FGeometry &Geometry, float DeltaTime) override"
.br
.ti -1c
.RI "void \fBStart\fP (\fBEFadeMode\fP Mode)"
.br
.ti -1c
.RI "void \fBSetAlpha\fP (float InAlphaValue)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FOnFadeFinished \fBOnFadeFinished\fP"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBOnStart\fP ()"
.br
.ti -1c
.RI "void \fBOnStart_Implementation\fP ()"
.br
.ti -1c
.RI "void \fBOnFinish\fP ()"
.br
.ti -1c
.RI "void \fBOnFinish_Implementation\fP ()"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "float \fBAlphaValue\fP"
.br
.in -1c
.SH "詳解"
.PP 
画面のフェード 
.SH "構築子と解体子"
.PP 
.SS "UFadeScreen::UFadeScreen (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UFadeScreen::~UFadeScreen ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UFadeScreen::NativeTick (const FGeometry & Geometry, float DeltaTime)\fC [override]\fP, \fC [virtual]\fP"

.SS "void UFadeScreen::OnFinish ()\fC [protected]\fP"

.SS "void UFadeScreen::OnFinish_Implementation ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void UFadeScreen::OnStart ()\fC [protected]\fP"

.SS "void UFadeScreen::OnStart_Implementation ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void UFadeScreen::SetAlpha (float InAlphaValue)\fC [inline]\fP"

.SS "void UFadeScreen::Start (\fBEFadeMode\fP Mode)"

.SH "メンバ詳解"
.PP 
.SS "float UFadeScreen::AlphaValue\fC [protected]\fP"

.SS "FOnFadeFinished UFadeScreen::OnFadeFinished"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
