.TH "UMMOGameInstance" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UMMOGameInstance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MMOGameInstance\&.h>\fP
.PP
UGameInstanceを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUMMOGameInstance\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UMMOGameInstance\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP () override"
.br
.ti -1c
.RI "virtual void \fBShutdown\fP () override"
.br
.ti -1c
.RI "bool \fBConnect\fP (const FString &Host, int Port)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "bool \fBIsConnected\fP () const"
.br
.ti -1c
.RI "void \fBSendPacket\fP (\fBPacketBase\fP *pPacket)"
.br
.ti -1c
.RI "void \fBOnRecvStatus\fP (uint32 Uuid, const FString &Name, \fBu8\fP Job, uint32 Level, int32 MaxHp, int32 Atk, int32 Def, int32 Exp, \fBu32\fP Gold)"
.br
.ti -1c
.RI "void \fBOnRecvSkillList\fP (uint32 NormalAttack, uint32 Skill1, uint32 Skill2, uint32 Skill3, uint32 Skill4)"
.br
.ti -1c
.RI "void \fBOnRecvSkillTreeData\fP (const \fBFlexArray\fP< \fBSkillTreeNode\fP > &Nodes)"
.br
.ti -1c
.RI "void \fBOnRecvItemList\fP (const \fBFlexArray\fP< \fBItemData\fP > &Items)"
.br
.ti -1c
.RI "void \fBOnRecvItemShortcht\fP (uint32 ItemId1, uint32 ItemId2)"
.br
.ti -1c
.RI "const \fBPlayerStatus\fP & \fBGetStatusCache\fP () const"
.br
.ti -1c
.RI "void \fBSetAreaIdCache\fP (uint32 AreaId)"
.br
.ti -1c
.RI "uint32 \fBGetAreaIdCache\fP ()"
.br
.ti -1c
.RI "\fBScriptExecuter\fP * \fBGetScript\fP ()"
.br
.ti -1c
.RI "const \fBQuestManager\fP & \fBGetQuestManager\fP () const"
.br
.ti -1c
.RI "void \fBInitializeQuestManager\fP ()"
.br
.ti -1c
.RI "void \fBAddQuestData\fP (const \fBQuestData\fP &Data)"
.br
.ti -1c
.RI "void \fBQuestKillAnpan\fP (uint32 QuestId)"
.br
.ti -1c
.RI "void \fBProgressQuest\fP (uint32 QuestId, uint32 StageNo)"
.br
.ti -1c
.RI "void \fBClearQuest\fP (uint32 QuestId)"
.br
.ti -1c
.RI "void \fBRetireQuest\fP (uint32 QuestId)"
.br
.ti -1c
.RI "void \fBSetActiveQuest\fP (uint32 QuestId, bool bSendSavePacket)"
.br
.ti -1c
.RI "const \fBQuestData\fP * \fBGetActiveQuestData\fP ()"
.br
.ti -1c
.RI "FOnActiveQuestUpdated & \fBOnActiveQuestUpdated\fP ()"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FOnRecvPacketDelegate \fBOnRecvPacketDelegate\fP"
.br
.in -1c
.SH "詳解"
.PP 
GameInstance 
.SH "構築子と解体子"
.PP 
.SS "UMMOGameInstance::UMMOGameInstance (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UMMOGameInstance::~UMMOGameInstance ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UMMOGameInstance::AddQuestData (const \fBQuestData\fP & Data)"

.SS "void UMMOGameInstance::ClearQuest (uint32 QuestId)"

.SS "void UMMOGameInstance::Close ()"

.SS "bool UMMOGameInstance::Connect (const FString & Host, int Port)"

.SS "const \fBQuestData\fP* UMMOGameInstance::GetActiveQuestData ()\fC [inline]\fP"

.SS "uint32 UMMOGameInstance::GetAreaIdCache ()\fC [inline]\fP"

.SS "const \fBQuestManager\fP& UMMOGameInstance::GetQuestManager () const\fC [inline]\fP"

.SS "\fBScriptExecuter\fP* UMMOGameInstance::GetScript ()\fC [inline]\fP"

.SS "const \fBPlayerStatus\fP& UMMOGameInstance::GetStatusCache () const\fC [inline]\fP"

.SS "void UMMOGameInstance::Init ()\fC [override]\fP, \fC [virtual]\fP"

.SS "void UMMOGameInstance::InitializeQuestManager ()\fC [inline]\fP"

.SS "bool UMMOGameInstance::IsConnected () const\fC [inline]\fP"

.SS "FOnActiveQuestUpdated& UMMOGameInstance::OnActiveQuestUpdated ()\fC [inline]\fP"

.SS "void UMMOGameInstance::OnRecvItemList (const \fBFlexArray\fP< \fBItemData\fP > & Items)"

.SS "void UMMOGameInstance::OnRecvItemShortcht (uint32 ItemId1, uint32 ItemId2)"

.SS "void UMMOGameInstance::OnRecvSkillList (uint32 NormalAttack, uint32 Skill1, uint32 Skill2, uint32 Skill3, uint32 Skill4)"

.SS "void UMMOGameInstance::OnRecvSkillTreeData (const \fBFlexArray\fP< \fBSkillTreeNode\fP > & Nodes)"

.SS "void UMMOGameInstance::OnRecvStatus (uint32 Uuid, const FString & Name, \fBu8\fP Job, uint32 Level, int32 MaxHp, int32 Atk, int32 Def, int32 Exp, \fBu32\fP Gold)"

.SS "void UMMOGameInstance::ProgressQuest (uint32 QuestId, uint32 StageNo)"

.SS "void UMMOGameInstance::QuestKillAnpan (uint32 QuestId)"

.SS "void UMMOGameInstance::RetireQuest (uint32 QuestId)"

.SS "void UMMOGameInstance::SendPacket (\fBPacketBase\fP * pPacket)"

.SS "void UMMOGameInstance::SetActiveQuest (uint32 QuestId, bool bSendSavePacket)\fC [inline]\fP"

.SS "void UMMOGameInstance::SetAreaIdCache (uint32 AreaId)\fC [inline]\fP"

.SS "void UMMOGameInstance::Shutdown ()\fC [override]\fP, \fC [virtual]\fP"

.SH "メンバ詳解"
.PP 
.SS "FOnRecvPacketDelegate UMMOGameInstance::OnRecvPacketDelegate"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
