.TH "UPartyInfoMenuWidget" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPartyInfoMenuWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartyInfoMenuWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUPartyInfoMenuWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UPartyInfoMenuWidget\fP ()"
.br
.ti -1c
.RI "virtual void \fBNativeConstruct\fP () override"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUPartyInfoMenuWidget\fP * \fBCreate\fP (UObject *pOuter)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnInit_Implementation\fP ()"
.br
.ti -1c
.RI "void \fBSendDissolutionRequest\fP ()"
.br
.ti -1c
.RI "void \fBSendExitRequest\fP ()"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "TArray< \fBFPartyMemberData\fP > \fBMemberList\fP"
.br
.ti -1c
.RI "bool \fBbIsLeader\fP"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
パーティ情報メニューWidget 
.SH "構築子と解体子"
.PP 
.SS "UPartyInfoMenuWidget::UPartyInfoMenuWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UPartyInfoMenuWidget::~UPartyInfoMenuWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "\fBUPartyInfoMenuWidget\fP * UPartyInfoMenuWidget::Create (UObject * pOuter)\fC [static]\fP"

.SS "void UPartyInfoMenuWidget::Init ()\fC [protected]\fP"

.SS "void UPartyInfoMenuWidget::NativeConstruct ()\fC [override]\fP, \fC [virtual]\fP"

.SS "void UPartyInfoMenuWidget::OnInit ()\fC [protected]\fP"

.SS "void UPartyInfoMenuWidget::OnInit_Implementation ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void UPartyInfoMenuWidget::SendDissolutionRequest ()\fC [protected]\fP"

.SS "void UPartyInfoMenuWidget::SendExitRequest ()\fC [protected]\fP"

.SH "メンバ詳解"
.PP 
.SS "bool UPartyInfoMenuWidget::bIsLeader\fC [protected]\fP"

.SS "TArray<\fBFPartyMemberData\fP> UPartyInfoMenuWidget::MemberList\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
