.TH "UQuestMenu" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UQuestMenu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestMenu\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUQuestMenu\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UQuestMenu\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRecvPacket\fP (uint8 ID) override"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBInitEvent\fP (const TArray< \fBFQuestData\fP > &List)"
.br
.ti -1c
.RI "void \fBInitEvent_Implementation\fP (const TArray< \fBFQuestData\fP > &List)"
.br
.ti -1c
.RI "void \fBRetireQuest\fP (const \fBFQuestData\fP &Data)"
.br
.ti -1c
.RI "void \fBChangeActiveQuest\fP (const \fBFQuestData\fP &Data)"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
クエストメニュー 
.SH "構築子と解体子"
.PP 
.SS "UQuestMenu::UQuestMenu (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UQuestMenu::~UQuestMenu ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UQuestMenu::ChangeActiveQuest (const \fBFQuestData\fP & Data)\fC [protected]\fP"

.SS "void UQuestMenu::Init ()\fC [protected]\fP"

.SS "void UQuestMenu::InitEvent (const TArray< \fBFQuestData\fP > & List)\fC [protected]\fP"

.SS "void UQuestMenu::InitEvent_Implementation (const TArray< \fBFQuestData\fP > & List)\fC [inline]\fP, \fC [protected]\fP"

.SS "void UQuestMenu::OnRecvPacket (uint8 ID)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBULayeredMenuWidgetBase\fPを再実装しています。
.SS "void UQuestMenu::RetireQuest (const \fBFQuestData\fP & Data)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
