.TH "D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Master/WarpDataMaster.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Master/WarpDataMaster.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MemoryStream/MemoryStreamInterface\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBWarpDataItem\fP"
.br
.ti -1c
.RI "class \fBWarpDataMaster\fP"
.br
.in -1c
.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
