.TH "ACharacterBase" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACharacterBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CharacterBase\&.h>\fP
.PP
ACharacterを継承しています。
.PP
\fBAAnpan\fP, \fBANPCCharacter\fP, \fBAPlayerCharacterBase\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBACharacterBase\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~ACharacterBase\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP (AActor *pDestroyedActor)"
.br
.ti -1c
.RI "void \fBApplyDamage\fP (int32 Value)"
.br
.ti -1c
.RI "void \fBHeal\fP (int32 Value)"
.br
.ti -1c
.RI "bool \fBIsDead\fP () const"
.br
.ti -1c
.RI "int32 \fBGetHp\fP () const"
.br
.ti -1c
.RI "int32 \fBGetMaxHp\fP () const"
.br
.ti -1c
.RI "virtual float \fBGetHalfHeight\fP () const"
.br
.ti -1c
.RI "virtual \fBECharacterType\fP \fBGetCharacterType\fP () const"
.br
.ti -1c
.RI "void \fBSpawnTargetCircle\fP ()"
.br
.ti -1c
.RI "void \fBDestroyTargetCircle\fP ()"
.br
.ti -1c
.RI "virtual uint32 \fBGetUuid\fP () const"
.br
.ti -1c
.RI "virtual FString \fBGetCharacterName\fP () const"
.br
.ti -1c
.RI "virtual void \fBOnSkillCast\fP (uint32 SkillId)"
.br
.ti -1c
.RI "virtual void \fBOnSkillCastFinished\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnSkillActivate\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (int32 InHp, int32 InMaxHp)"
.br
.ti -1c
.RI "void \fBUpdateMaxHp\fP (int32 InMaxHp)"
.br
.ti -1c
.RI "void \fBOnDamaged\fP (int32 BeforeHp, int32 AfterHp, int32 DamageValue)"
.br
.ti -1c
.RI "virtual void \fBOnDamaged_Implementation\fP (int32 BeforeHp, int32 AfterHp, int32 DamageValue)"
.br
.ti -1c
.RI "void \fBOnHeal\fP (int32 BeforeHp, int32 AfterHp, int32 HealValue)"
.br
.ti -1c
.RI "void \fBOnHeal_Implementation\fP (int32 BeforeHp, int32 AfterHp, int32 HealValue)"
.br
.ti -1c
.RI "void \fBOnDead\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDead_Implementation\fP ()"
.br
.ti -1c
.RI "void \fBSetHP\fP (int InHp)"
.br
.in -1c
.SH "詳解"
.PP 
キャラクタ基底クラス 
.SH "構築子と解体子"
.PP 
.SS "ACharacterBase::ACharacterBase (const FObjectInitializer & ObjectInitializer)"

.SS "virtual ACharacterBase::~ACharacterBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ACharacterBase::ApplyDamage (int32 Value)"

.SS "void ACharacterBase::DestroyTargetCircle ()"

.SS "virtual FString ACharacterBase::GetCharacterName () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBAGameCharacter\fP, \fBAOtherPlayerCharacter\fPで再実装されています。
.SS "virtual \fBECharacterType\fP ACharacterBase::GetCharacterType () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBAGameCharacter\fP, \fBAAnpan\fP, \fBAOtherPlayerCharacter\fP, \fBANPCCharacter\fPで再実装されています。
.SS "virtual float ACharacterBase::GetHalfHeight () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBAAnpan\fP, \fBAPlayerCharacterBase\fP, \fBANPCCharacter\fPで再実装されています。
.SS "int32 ACharacterBase::GetHp () const\fC [inline]\fP"

.SS "int32 ACharacterBase::GetMaxHp () const\fC [inline]\fP"

.SS "virtual uint32 ACharacterBase::GetUuid () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBAGameCharacter\fP, \fBAOtherPlayerCharacter\fP, \fBAAnpan\fPで再実装されています。
.SS "void ACharacterBase::Heal (int32 Value)"

.SS "void ACharacterBase::Initialize (int32 InHp, int32 InMaxHp)\fC [protected]\fP"

.SS "bool ACharacterBase::IsDead () const\fC [inline]\fP"

.SS "void ACharacterBase::OnDamaged (int32 BeforeHp, int32 AfterHp, int32 DamageValue)\fC [protected]\fP"

.SS "virtual void ACharacterBase::OnDamaged_Implementation (int32 BeforeHp, int32 AfterHp, int32 DamageValue)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SS "void ACharacterBase::OnDead ()\fC [protected]\fP"

.SS "virtual void ACharacterBase::OnDead_Implementation ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SS "void ACharacterBase::OnDestroy (AActor * pDestroyedActor)"

.SS "void ACharacterBase::OnHeal (int32 BeforeHp, int32 AfterHp, int32 HealValue)\fC [protected]\fP"

.SS "void ACharacterBase::OnHeal_Implementation (int32 BeforeHp, int32 AfterHp, int32 HealValue)\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void ACharacterBase::OnSkillActivate ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBAGameCharacter\fPで再実装されています。
.SS "void ACharacterBase::OnSkillCast (uint32 SkillId)\fC [virtual]\fP"

.SS "void ACharacterBase::OnSkillCastFinished ()\fC [virtual]\fP"

.PP
\fBAGameCharacter\fPで再実装されています。
.SS "void ACharacterBase::SetHP (int InHp)\fC [inline]\fP, \fC [protected]\fP"

.SS "void ACharacterBase::SpawnTargetCircle ()"

.SS "void ACharacterBase::UpdateMaxHp (int32 InMaxHp)\fC [inline]\fP, \fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
