.TH "AGameController" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGameController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameController\&.h>\fP
.PP
APlayerControllerを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAGameController\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~AGameController\fP ()"
.br
.ti -1c
.RI "virtual void \fBPossess\fP (APawn *aPawn) override"
.br
.ti -1c
.RI "virtual void \fBTick\fP (float DeltaTime) override"
.br
.ti -1c
.RI "virtual bool \fBInputTouch\fP (uint32 Handle, ETouchType::Type Type, const FVector2D &TouchLocation, float Force, FDateTime DeviceTimestamp, uint32 TouchpadIndex) override"
.br
.ti -1c
.RI "void \fBSetEnableMove\fP (bool bInEnableMove)"
.br
.ti -1c
.RI "\fBACharacterBase\fP * \fBGetCurrentTarget\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
コントローラクラス 
.SH "構築子と解体子"
.PP 
.SS "AGameController::AGameController (const FObjectInitializer & ObjectInitializer)"

.SS "virtual AGameController::~AGameController ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "\fBACharacterBase\fP* AGameController::GetCurrentTarget () const\fC [inline]\fP"

.SS "bool AGameController::InputTouch (uint32 Handle, ETouchType::Type Type, const FVector2D & TouchLocation, float Force, FDateTime DeviceTimestamp, uint32 TouchpadIndex)\fC [override]\fP, \fC [virtual]\fP"

.SS "void AGameController::Possess (APawn * aPawn)\fC [override]\fP, \fC [virtual]\fP"

.SS "void AGameController::SetEnableMove (bool bInEnableMove)\fC [inline]\fP"

.SS "void AGameController::Tick (float DeltaTime)\fC [override]\fP, \fC [virtual]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
