.TH "AMMOGameModeBase" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AMMOGameModeBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MMOGameModeBase\&.h>\fP
.PP
AGameModeBaseを継承しています。
.PP
\fBAActiveGameMode\fP, \fBATitleGameMode\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAMMOGameModeBase\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~AMMOGameModeBase\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginPlay\fP () override"
.br
.ti -1c
.RI "void \fBSetCurrentMenu\fP (\fBULayeredMenuWidgetBase\fP *pMenu)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBAddPacketFunction\fP (uint8 ID, const PacketFunc &Func)"
.br
.in -1c
.SH "詳解"
.PP 
GameMode基底クラス 
.SH "構築子と解体子"
.PP 
.SS "AMMOGameModeBase::AMMOGameModeBase (const FObjectInitializer & ObjectInitializer)"

.SS "virtual AMMOGameModeBase::~AMMOGameModeBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void AMMOGameModeBase::AddPacketFunction (uint8 ID, const PacketFunc & Func)\fC [protected]\fP"

.SS "void AMMOGameModeBase::BeginPlay ()\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBAActiveGameMode\fP, \fBATitleGameMode\fPで再実装されています。
.SS "void AMMOGameModeBase::SetCurrentMenu (\fBULayeredMenuWidgetBase\fP * pMenu)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
