.TH "AnpanMaster" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBAnpanItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBAnpanItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBAnpanItem\fP * AnpanMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBAnpanItem\fP > AnpanMaster::GetAll () const"

.SS "void AnpanMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
