.TH "AnpanManager" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanManager\fP ()"
.br
.ti -1c
.RI "\fB~AnpanManager\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP ()"
.br
.ti -1c
.RI "void \fBSetWorld\fP (UWorld *pInWorld)"
.br
.ti -1c
.RI "\fBAAnpan\fP * \fBGet\fP (uint32 Uuid) const"
.br
.ti -1c
.RI "void \fBOnRecvList\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvSpawn\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvMove\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvRotate\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvStop\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "\fBAAnpan\fP * \fBFindCenterTarget\fP (float Distance)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
アンパン管理\&. 
.SH "構築子と解体子"
.PP 
.SS "AnpanManager::AnpanManager ()"

.SS "AnpanManager::~AnpanManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "\fBAAnpan\fP * AnpanManager::FindCenterTarget (float Distance)"

.SS "\fBAAnpan\fP * AnpanManager::Get (uint32 Uuid) const"

.SS "void AnpanManager::OnRecvList (\fBMemoryStreamInterface\fP * pStream)"

.SS "void AnpanManager::OnRecvMove (\fBMemoryStreamInterface\fP * pStream)"

.SS "void AnpanManager::OnRecvRotate (\fBMemoryStreamInterface\fP * pStream)"

.SS "void AnpanManager::OnRecvSpawn (\fBMemoryStreamInterface\fP * pStream)"

.SS "void AnpanManager::OnRecvStop (\fBMemoryStreamInterface\fP * pStream)"

.SS "void AnpanManager::Poll ()"

.SS "void AnpanManager::Reset ()"

.SS "void AnpanManager::SetWorld (UWorld * pInWorld)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
