.TH "AreaMaster" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AreaMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBAreaItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBAreaItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBAreaItem\fP * AreaMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBAreaItem\fP > AreaMaster::GetAll () const"

.SS "void AreaMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
