.TH "AreaItem" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AreaMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBNORMAL_AREA\fP = 0, \fBINSTANCE_AREA\fP = 1 }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "FString \fBName\fP"
.br
.ti -1c
.RI "FString \fBLevelName\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBInstanceInfoId\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINORMAL_AREA \fP\fP
.TP
\fB\fIINSTANCE_AREA \fP\fP
.SH "関数詳解"
.PP 
.SS "bool AreaItem::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP AreaItem::ID"

.SS "\fBu32\fP AreaItem::InstanceInfoId"

.SS "FString AreaItem::LevelName"

.SS "FString AreaItem::Name"

.SS "\fBu8\fP AreaItem::Type"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
