.TH "ASkyControl" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASkyControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkyControl\&.h>\fP
.PP
AActorを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBASkyControl\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~ASkyControl\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginPlay\fP () override"
.br
.ti -1c
.RI "virtual void \fBTick\fP (float DeltaTime) override"
.br
.ti -1c
.RI "void \fBRefleshMaterial\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSunDirection\fP ()"
.br
.ti -1c
.RI "void \fBSetTime\fP (uint32 MasterId)"
.br
.ti -1c
.RI "void \fBTimeChange\fP (uint32 MasterId)"
.br
.in -1c
.SH "詳解"
.PP 
天球の状態コントロールActor 
.SH "構築子と解体子"
.PP 
.SS "ASkyControl::ASkyControl (const FObjectInitializer & ObjectInitializer)"

.SS "virtual ASkyControl::~ASkyControl ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ASkyControl::BeginPlay ()\fC [override]\fP, \fC [virtual]\fP"

.SS "void ASkyControl::RefleshMaterial ()"

.SS "void ASkyControl::SetTime (uint32 MasterId)"

.SS "void ASkyControl::Tick (float DeltaTime)\fC [override]\fP, \fC [virtual]\fP"

.SS "void ASkyControl::TimeChange (uint32 MasterId)"

.SS "void ASkyControl::UpdateSunDirection ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
