.TH "ATargetCircle" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ATargetCircle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TargetCircle\&.h>\fP
.PP
AActorを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBATargetCircle\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~ATargetCircle\fP ()"
.br
.ti -1c
.RI "void \fBSetCharacter\fP (\fBACharacterBase\fP *pInCharacter)"
.br
.ti -1c
.RI "virtual void \fBTick\fP (float DeltaTime) override"
.br
.in -1c
.SH "詳解"
.PP 
ターゲットサークル 
.SH "構築子と解体子"
.PP 
.SS "ATargetCircle::ATargetCircle (const FObjectInitializer & ObjectInitializer)"

.SS "virtual ATargetCircle::~ATargetCircle ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ATargetCircle::SetCharacter (\fBACharacterBase\fP * pInCharacter)"

.SS "void ATargetCircle::Tick (float DeltaTime)\fC [override]\fP, \fC [virtual]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
