.TH "AWarpPoint" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AWarpPoint
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WarpPoint\&.h>\fP
.PP
AActorを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAWarpPoint\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~AWarpPoint\fP ()"
.br
.ti -1c
.RI "virtual void \fBTick\fP (float DeltaTime) override"
.br
.ti -1c
.RI "void \fBOnOverlap\fP (UPrimitiveComponent *pOverlappedComponent, AActor *pOtherActor, UPrimitiveComponent *pOtherComponent, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBAWarpPoint\fP * \fBSpawn\fP (UWorld *pWorld, float X, float Y, float Z, uint32 InId)"
.br
.in -1c
.SH "詳解"
.PP 
ワープポイントクラス 
.SH "構築子と解体子"
.PP 
.SS "AWarpPoint::AWarpPoint (const FObjectInitializer & ObjectInitializer)"

.SS "virtual AWarpPoint::~AWarpPoint ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void AWarpPoint::OnOverlap (UPrimitiveComponent * pOverlappedComponent, AActor * pOtherActor, UPrimitiveComponent * pOtherComponent, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult)"

.SS "\fBAWarpPoint\fP * AWarpPoint::Spawn (UWorld * pWorld, float X, float Y, float Z, uint32 InId)\fC [static]\fP"

.SS "void AWarpPoint::Tick (float DeltaTime)\fC [override]\fP, \fC [virtual]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
