.TH "Buffer" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Buffer\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBBuffer\fP ()"
.br
.ti -1c
.RI "\fB~Buffer\fP ()"
.br
.ti -1c
.RI "void \fBPush\fP (const uint8 *pData, int32 Size)"
.br
.ti -1c
.RI "void \fBPop\fP (int32 Size)"
.br
.ti -1c
.RI "uint8 * \fBGetTop\fP ()"
.br
.ti -1c
.RI "int32 \fBGetSize\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
バッファクラス 
.SH "構築子と解体子"
.PP 
.SS "Buffer::Buffer ()"

.SS "Buffer::~Buffer ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "int32 Buffer::GetSize () const\fC [inline]\fP"

.SS "uint8 * Buffer::GetTop ()"

.SS "void Buffer::Pop (int32 Size)"

.SS "void Buffer::Push (const uint8 * pData, int32 Size)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
