.TH "D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Character/CharacterBase.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Character/CharacterBase.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'GameFramework/Character\&.h'\fP
.br
\fC#include 'CharacterBase\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBACharacterBase\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBECharacterType\fP : uint8 { \fBECharacterType::UMETA\fP =(Hidden), \fBECharacterType::Player\fP, \fBECharacterType::Other\fP, \fBECharacterType::Anpan\fP, \fBECharacterType::NPC\fP }"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBECharacterType\fP : uint8\fC [strong]\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIUMETA \fP\fP
.TP
\fB\fIPlayer \fP\fP
.TP
\fB\fIOther \fP\fP
.TP
\fB\fIAnpan \fP\fP
.TP
\fB\fINPC \fP\fP
.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
