.TH "ChatWindowWidget.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatWindowWidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Blueprint/UserWidget\&.h'\fP
.br
\fC#include 'ChatWindowWidget\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBUChatWindowWidget\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBEChatType\fP : uint8 { \fBEChatType::Say\fP, \fBEChatType::Showt\fP }"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBEChatType\fP : uint8\fC [strong]\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fISay \fP\fP
.TP
\fB\fIShowt \fP\fP
.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
