.TH "FadeScreen.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FadeScreen.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Blueprint/UserWidget\&.h'\fP
.br
\fC#include 'FadeScreen\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBUFadeScreen\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBEFadeMode\fP : uint8 { \fBEFadeMode::UMETA\fP =(Hidden), \fBEFadeMode::FadeIn\fP, \fBEFadeMode::FadeOut\fP }"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DYNAMIC_MULTICAST_DELEGATE\fP (FOnFadeFinished)"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBEFadeMode\fP : uint8\fC [strong]\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIUMETA \fP\fP
.TP
\fB\fIFadeIn \fP\fP
.TP
\fB\fIFadeOut \fP\fP
.SH "関数詳解"
.PP 
.SS "DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnFadeFinished)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
