.TH "FItemData" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FItemData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemMenu\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "uint32 \fBItemId\fP"
.br
.ti -1c
.RI "FString \fBName\fP"
.br
.ti -1c
.RI "int32 \fBCount\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "int32 FItemData::Count"

.SS "uint32 FItemData::ItemId"

.SS "FString FItemData::Name"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
