.TH "FPartyMemberData" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FPartyMemberData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartyInfoMenuWidget\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "uint32 \fBUuid\fP"
.br
.ti -1c
.RI "FString \fBName\fP"
.br
.ti -1c
.RI "bool \fBbIsLeader\fP"
.br
.ti -1c
.RI "bool \fBbIsSelf\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "bool FPartyMemberData::bIsLeader"

.SS "bool FPartyMemberData::bIsSelf"

.SS "FString FPartyMemberData::Name"

.SS "uint32 FPartyMemberData::Uuid"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
