.TH "FSkillTreeNode" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSkillTreeNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillMenu\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "uint32 \fBNodeId\fP"
.br
.ti -1c
.RI "int32 \fBSkillId\fP"
.br
.ti -1c
.RI "int32 \fBNeedLevel\fP"
.br
.ti -1c
.RI "int32 \fBCost\fP"
.br
.ti -1c
.RI "bool \fBbIsOpened\fP"
.br
.ti -1c
.RI "bool \fBbIsParentOpened\fP"
.br
.ti -1c
.RI "FVector2D \fBPosition\fP"
.br
.in -1c
.SH "詳解"
.PP 
スキルツリーノード 
.SH "メンバ詳解"
.PP 
.SS "bool FSkillTreeNode::bIsOpened"

.SS "bool FSkillTreeNode::bIsParentOpened"

.SS "int32 FSkillTreeNode::Cost"

.SS "int32 FSkillTreeNode::NeedLevel"

.SS "uint32 FSkillTreeNode::NodeId"

.SS "FVector2D FSkillTreeNode::Position"

.SS "int32 FSkillTreeNode::SkillId"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
