.TH "GameServerConnection" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameServerConnection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameServerConnection\&.h>\fP
.PP
FTickableGameObjectを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBGameServerConnection\fP ()"
.br
.ti -1c
.RI "\fB~GameServerConnection\fP ()"
.br
.ti -1c
.RI "bool \fBConnect\fP (const FString &Host, int32 Port)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "bool \fBIsConnected\fP () const"
.br
.ti -1c
.RI "void \fBSendPacket\fP (\fBPacketBase\fP *pPacket)"
.br
.ti -1c
.RI "virtual void \fBTick\fP (float DeltaTime) override"
.br
.ti -1c
.RI "virtual TStatId \fBGetStatId\fP () const override"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FOnRecvPacketDelegate \fBOnRecvPacketDelegate\fP"
.br
.in -1c
.SH "詳解"
.PP 
ゲームサーバ接続\&. 
.SH "構築子と解体子"
.PP 
.SS "GameServerConnection::GameServerConnection ()"

.SS "GameServerConnection::~GameServerConnection ()"

.SH "関数詳解"
.PP 
.SS "void GameServerConnection::Close ()"

.SS "bool GameServerConnection::Connect (const FString & Host, int32 Port)"

.SS "virtual TStatId GameServerConnection::GetStatId () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.SS "bool GameServerConnection::IsConnected () const\fC [inline]\fP"

.SS "void GameServerConnection::SendPacket (\fBPacketBase\fP * pPacket)"

.SS "void GameServerConnection::Tick (float DeltaTime)\fC [override]\fP, \fC [virtual]\fP"

.SH "メンバ詳解"
.PP 
.SS "FOnRecvPacketDelegate GameServerConnection::OnRecvPacketDelegate"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
