.TH "GameServerConnection.h" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameServerConnection.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Networking/Public/Networking\&.h'\fP
.br
\fC#include 'Tickable\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'Packet/PacketID\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBGameServerConnection\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE_TwoParams\fP (FOnRecvPacketDelegate, uint8, \fBMemoryStreamInterface\fP *)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE_TwoParams (FOnRecvPacketDelegate, uint8, \fBMemoryStreamInterface\fP *)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
