.TH "HttpConnection" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HttpConnection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HttpConnection\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBHttpConnection\fP ()"
.br
.ti -1c
.RI "\fB~HttpConnection\fP ()"
.br
.ti -1c
.RI "bool \fBStartDownload\fP (const FString &URL)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FDownloadFinished \fBDownloadFinished\fP"
.br
.in -1c
.SH "詳解"
.PP 
HTTP通信クラス 
.SH "構築子と解体子"
.PP 
.SS "HttpConnection::HttpConnection ()"

.SS "HttpConnection::~HttpConnection ()"

.SH "関数詳解"
.PP 
.SS "void HttpConnection::Close ()"

.SS "bool HttpConnection::StartDownload (const FString & URL)"

.SH "メンバ詳解"
.PP 
.SS "FDownloadFinished HttpConnection::DownloadFinished"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
