.TH "HttpConnection.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HttpConnection.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Online/HTTP/Public/Http\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBHttpConnection\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE_TwoParams\fP (FDownloadFinished, bool, const TArray< uint8 > &)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE_TwoParams (FDownloadFinished, bool, const TArray< uint8 > &)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
