.TH "IdManager" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IdManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBIdManager\fP (const std::string &InFilePath)"
.br
.ti -1c
.RI "\fB~IdManager\fP ()"
.br
.ti -1c
.RI "std::string \fBGetId\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
IDのローカル管理\&. 
.SH "構築子と解体子"
.PP 
.SS "IdManager::IdManager (const std::string & InFilePath)"

.SS "IdManager::~IdManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "std::string IdManager::GetId ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
