.TH "IdManager.cpp" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IdManager\&.h'\fP
.br
\fC#include 'AnpanMMO\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
