.TH "ItemMaster" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBItemItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBItemItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBItemItem\fP * ItemMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBItemItem\fP > ItemMaster::GetAll () const"

.SS "void ItemMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
