.TH "ItemList" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemList\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBItemList\fP ()"
.br
.ti -1c
.RI "\fB~ItemList\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (uint32 ItemId, uint32 Count)"
.br
.ti -1c
.RI "void \fBSubtract\fP (uint32 ItemId, uint32 Count)"
.br
.ti -1c
.RI "uint32 \fBGetCount\fP (uint32 ItemId) const"
.br
.ti -1c
.RI "TArray< uint32 > \fBCollectItemList\fP () const"
.br
.ti -1c
.RI "void \fBUpdateItemShortcut\fP (uint32 ItemId1, uint32 ItemId2)"
.br
.ti -1c
.RI "const TArray< uint32 > & \fBGetItemShortcut\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
アイテムリストクラス 
.SH "構築子と解体子"
.PP 
.SS "ItemList::ItemList ()"

.SS "ItemList::~ItemList ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void ItemList::Add (uint32 ItemId, uint32 Count)"

.SS "TArray< uint32 > ItemList::CollectItemList () const"

.SS "uint32 ItemList::GetCount (uint32 ItemId) const"

.SS "const TArray<uint32>& ItemList::GetItemShortcut () const\fC [inline]\fP"

.SS "void ItemList::Subtract (uint32 ItemId, uint32 Count)"

.SS "void ItemList::UpdateItemShortcut (uint32 ItemId1, uint32 ItemId2)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
