.TH "LayeredMenuWidgetBase.h" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayeredMenuWidgetBase.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Blueprint/UserWidget\&.h'\fP
.br
\fC#include 'LayeredMenuWidgetBase\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBULayeredMenuWidgetBase\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE\fP (FOnMenuClosed)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE (FOnMenuClosed)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
