.TH "MasterData" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MasterData\&.h>\fP
.PP
FNoncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fB~MasterData\fP ()"
.br
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "const \fBAreaMaster\fP & \fBGetAreaMaster\fP () const"
.br
.ti -1c
.RI "const \fBWarpPointMaster\fP & \fBGetWarpPointMaster\fP () const"
.br
.ti -1c
.RI "const \fBWarpDataMaster\fP & \fBGetWarpDataMaster\fP () const"
.br
.ti -1c
.RI "const \fBAnpanMaster\fP & \fBGetAnpanMaster\fP () const"
.br
.ti -1c
.RI "const \fBTimeInfoMaster\fP & \fBGetTimeInfoMaster\fP () const"
.br
.ti -1c
.RI "const \fBNPCMaster\fP & \fBGetNPCMaster\fP () const"
.br
.ti -1c
.RI "const \fBNPCResourceMaster\fP & \fBGetNPCReseourceMaster\fP () const"
.br
.ti -1c
.RI "const \fBNPCConditionMaster\fP & \fBGetNPCConditionMaster\fP () const"
.br
.ti -1c
.RI "const \fBSkillMaster\fP & \fBGetSkillMaster\fP () const"
.br
.ti -1c
.RI "const \fBSkillTreeMaster\fP & \fBGetSkillTreeMaster\fP () const"
.br
.ti -1c
.RI "const \fBItemMaster\fP & \fBGetItemMaster\fP () const"
.br
.ti -1c
.RI "const \fBQuestMaster\fP & \fBGetQuestMaster\fP () const"
.br
.ti -1c
.RI "const \fBQuestStageMaster\fP & \fBGetQuestStageMaster\fP () const"
.br
.ti -1c
.RI "const \fBQuestRewardMaster\fP & \fBGetQuestRewardMaster\fP () const"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBMasterData\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
マスタデータ 
.SH "構築子と解体子"
.PP 
.SS "MasterData::~MasterData ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "const \fBAnpanMaster\fP& MasterData::GetAnpanMaster () const\fC [inline]\fP"

.SS "const \fBAreaMaster\fP& MasterData::GetAreaMaster () const\fC [inline]\fP"

.SS "static \fBMasterData\fP& MasterData::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "const \fBItemMaster\fP& MasterData::GetItemMaster () const\fC [inline]\fP"

.SS "const \fBNPCConditionMaster\fP& MasterData::GetNPCConditionMaster () const\fC [inline]\fP"

.SS "const \fBNPCMaster\fP& MasterData::GetNPCMaster () const\fC [inline]\fP"

.SS "const \fBNPCResourceMaster\fP& MasterData::GetNPCReseourceMaster () const\fC [inline]\fP"

.SS "const \fBQuestMaster\fP& MasterData::GetQuestMaster () const\fC [inline]\fP"

.SS "const \fBQuestRewardMaster\fP& MasterData::GetQuestRewardMaster () const\fC [inline]\fP"

.SS "const \fBQuestStageMaster\fP& MasterData::GetQuestStageMaster () const\fC [inline]\fP"

.SS "const \fBSkillMaster\fP& MasterData::GetSkillMaster () const\fC [inline]\fP"

.SS "const \fBSkillTreeMaster\fP& MasterData::GetSkillTreeMaster () const\fC [inline]\fP"

.SS "const \fBTimeInfoMaster\fP& MasterData::GetTimeInfoMaster () const\fC [inline]\fP"

.SS "const \fBWarpDataMaster\fP& MasterData::GetWarpDataMaster () const\fC [inline]\fP"

.SS "const \fBWarpPointMaster\fP& MasterData::GetWarpPointMaster () const\fC [inline]\fP"

.SS "void MasterData::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
