.TH "MemoryStreamReader" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryStreamReader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemoryStreamReader\&.h>\fP
.PP
\fBMemoryStreamInterface\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMemoryStreamReader\fP (const \fBu8\fP *pInData, const int InSize)"
.br
.ti -1c
.RI "virtual \fB~MemoryStreamReader\fP ()"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBs32\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBu32\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBs16\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBu16\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBs8\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBu8\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (std::string *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (float *pValue)"
.br
.ti -1c
.RI "virtual bool \fBIsReadMode\fP () const"
.br
.ti -1c
.RI "virtual bool \fBIsError\fP () const"
.br
.ti -1c
.RI "virtual void \fBReset\fP ()"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "MemoryStreamReader::MemoryStreamReader (const \fBu8\fP * pInData, const int InSize)"

.SS "virtual MemoryStreamReader::~MemoryStreamReader ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "virtual bool MemoryStreamReader::IsError () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "virtual bool MemoryStreamReader::IsReadMode () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "void MemoryStreamReader::Reset ()\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (\fBs32\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (\fBu32\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (\fBs16\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (\fBu16\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (\fBs8\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (\fBu8\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (std::string * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamReader::Serialize (float * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
