.TH "D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Notice/NoticeManager.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Notice/NoticeManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Packet/NoticeData\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBNoticeInformation\fP"
.br
.ti -1c
.RI "class \fBNoticeManager\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE_TwoParams\fP (FOnRecvNotice, int32, const \fBNoticeData\fP &)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE_TwoParams (FOnRecvNotice, int32, const \fBNoticeData\fP &)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
