.TH "NoticeInformation" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoticeInformation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeManager\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "uint32 \fBUuid\fP"
.br
.ti -1c
.RI "\fBNoticeData\fP \fBData\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBNoticeData\fP NoticeInformation::Data"

.SS "uint32 NoticeInformation::Uuid"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
