.TH "NPCConditionItem" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NPCConditionItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCConditionMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBQuestId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBStageNo\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool NPCConditionItem::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP NPCConditionItem::ID"

.SS "\fBu32\fP NPCConditionItem::QuestId"

.SS "\fBu32\fP NPCConditionItem::StageNo"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
