.TH "NPCItem" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NPCItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "FString \fBName\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAreaId\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.ti -1c
.RI "float \fBRotation\fP"
.br
.ti -1c
.RI "FString \fBScriptName\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAppearConditionId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBEraseConditionId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBResourceId\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool NPCItem::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP NPCItem::AppearConditionId"

.SS "\fBu32\fP NPCItem::AreaId"

.SS "\fBu32\fP NPCItem::EraseConditionId"

.SS "\fBu32\fP NPCItem::ID"

.SS "FString NPCItem::Name"

.SS "\fBu32\fP NPCItem::ResourceId"

.SS "float NPCItem::Rotation"

.SS "FString NPCItem::ScriptName"

.SS "float NPCItem::X"

.SS "float NPCItem::Y"

.SS "float NPCItem::Z"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
