.TH "NPCManager" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NPCManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBNPCManager\fP ()"
.br
.ti -1c
.RI "\fB~NPCManager\fP ()"
.br
.ti -1c
.RI "void \fBSetWorld\fP (UWorld *pInWorld)"
.br
.ti -1c
.RI "void \fBOnMapChanegd\fP (uint32 MapId)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
NPC管理クラス 
.SH "構築子と解体子"
.PP 
.SS "NPCManager::NPCManager ()"

.SS "NPCManager::~NPCManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void NPCManager::OnMapChanegd (uint32 MapId)"

.SS "void NPCManager::Reset ()"

.SS "void NPCManager::SetWorld (UWorld * pInWorld)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
