.TH "NPCMaster" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NPCMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBNPCItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBNPCItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBNPCItem\fP * NPCMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBNPCItem\fP > NPCMaster::GetAll () const"

.SS "void NPCMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
