.TH "NPCResourceMaster" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NPCResourceMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCResourceMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBNPCResourceItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBNPCResourceItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBNPCResourceItem\fP * NPCResourceMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBNPCResourceItem\fP > NPCResourceMaster::GetAll () const"

.SS "void NPCResourceMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
