.TH "PacketPartyInviteResponse" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketPartyInviteResponse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketPartyInviteResponse\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBResponseCode\fP { \fBAccept\fP, \fBRefuse\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketPartyInviteResponse\fP ()"
.br
.ti -1c
.RI "\fBPacketPartyInviteResponse\fP (\fBu32\fP InCustomerId, \fBu8\fP InResponse)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBCustomerId\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBResponse\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBPacketPartyInviteResponse::ResponseCode\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIAccept \fP\fP
.TP
\fB\fIRefuse \fP\fP
.SH "構築子と解体子"
.PP 
.SS "PacketPartyInviteResponse::PacketPartyInviteResponse ()\fC [inline]\fP"

.SS "PacketPartyInviteResponse::PacketPartyInviteResponse (\fBu32\fP InCustomerId, \fBu8\fP InResponse)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketPartyInviteResponse::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketPartyInviteResponse::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketPartyInviteResponse::CustomerId"

.SS "\fBu8\fP PacketPartyInviteResponse::Response"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
