.TH "PacketPartyJoin" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketPartyJoin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketPartyJoin\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketPartyJoin\fP ()"
.br
.ti -1c
.RI "\fBPacketPartyJoin\fP (\fBu32\fP InUuid, \fBFlexArray\fP< \fBPartyMemberData\fP > InMemberList)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBUuid\fP"
.br
.ti -1c
.RI "\fBFlexArray\fP< \fBPartyMemberData\fP > \fBMemberList\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketPartyJoin::PacketPartyJoin ()\fC [inline]\fP"

.SS "PacketPartyJoin::PacketPartyJoin (\fBu32\fP InUuid, \fBFlexArray\fP< \fBPartyMemberData\fP > InMemberList)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketPartyJoin::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketPartyJoin::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBFlexArray\fP<\fBPartyMemberData\fP> PacketPartyJoin::MemberList"

.SS "\fBu32\fP PacketPartyJoin::Uuid"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
