.TH "PacketHeader" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketHeader\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBGetPacketId\fP ()"
.br
.ti -1c
.RI "\fBu16\fP \fBGetPacketSize\fP ()"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *Stream)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBu8\fP PacketHeader::GetPacketId ()\fC [inline]\fP"

.SS "\fBu16\fP PacketHeader::GetPacketSize ()\fC [inline]\fP"

.SS "bool PacketHeader::Serialize (\fBMemoryStreamInterface\fP * Stream)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
