.TH "PacketItemUse" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketItemUse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketItemUse\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketItemUse\fP ()"
.br
.ti -1c
.RI "\fBPacketItemUse\fP (\fBu32\fP InItemId, \fBu8\fP InTargetType, \fBu32\fP InTargetUuid)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBItemId\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBTargetType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBTargetUuid\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketItemUse::PacketItemUse ()\fC [inline]\fP"

.SS "PacketItemUse::PacketItemUse (\fBu32\fP InItemId, \fBu8\fP InTargetType, \fBu32\fP InTargetUuid)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketItemUse::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketItemUse::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketItemUse::ItemId"

.SS "\fBu8\fP PacketItemUse::TargetType"

.SS "\fBu32\fP PacketItemUse::TargetUuid"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
