.TH "PacketLogInRequest" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketLogInRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketLogInRequest\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketLogInRequest\fP ()"
.br
.ti -1c
.RI "\fBPacketLogInRequest\fP (std::string InUserCode)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "std::string \fBUserCode\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketLogInRequest::PacketLogInRequest ()\fC [inline]\fP"

.SS "PacketLogInRequest::PacketLogInRequest (std::string InUserCode)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketLogInRequest::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketLogInRequest::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "std::string PacketLogInRequest::UserCode"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
