.TH "PacketQuestData" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketQuestData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketQuestData\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketQuestData\fP ()"
.br
.ti -1c
.RI "\fBPacketQuestData\fP (\fBFlexArray\fP< \fBQuestData\fP > InQuests, \fBu32\fP InActiveQuestId)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBFlexArray\fP< \fBQuestData\fP > \fBQuests\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBActiveQuestId\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketQuestData::PacketQuestData ()\fC [inline]\fP"

.SS "PacketQuestData::PacketQuestData (\fBFlexArray\fP< \fBQuestData\fP > InQuests, \fBu32\fP InActiveQuestId)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketQuestData::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketQuestData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketQuestData::ActiveQuestId"

.SS "\fBFlexArray\fP<\fBQuestData\fP> PacketQuestData::Quests"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
