.TH "PacketRotateAnpan" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketRotateAnpan
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketRotateAnpan\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketRotateAnpan\fP ()"
.br
.ti -1c
.RI "\fBPacketRotateAnpan\fP (\fBu32\fP InUuid, float InRotation, \fBs32\fP InRotateMilliSec)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBUuid\fP"
.br
.ti -1c
.RI "float \fBRotation\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBRotateMilliSec\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketRotateAnpan::PacketRotateAnpan ()\fC [inline]\fP"

.SS "PacketRotateAnpan::PacketRotateAnpan (\fBu32\fP InUuid, float InRotation, \fBs32\fP InRotateMilliSec)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketRotateAnpan::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketRotateAnpan::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP PacketRotateAnpan::RotateMilliSec"

.SS "float PacketRotateAnpan::Rotation"

.SS "\fBu32\fP PacketRotateAnpan::Uuid"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
