.TH "PacketPartyCreateResult" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketPartyCreateResult
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketPartyCreateResult\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBResultCode\fP { \fBSuccess\fP, \fBAlreadyJoin\fP, \fBError\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketPartyCreateResult\fP ()"
.br
.ti -1c
.RI "\fBPacketPartyCreateResult\fP (\fBu8\fP InResult, \fBu32\fP InPartyId)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBResult\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBPartyId\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBPacketPartyCreateResult::ResultCode\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIAlreadyJoin \fP\fP
.TP
\fB\fIError \fP\fP
.SH "構築子と解体子"
.PP 
.SS "PacketPartyCreateResult::PacketPartyCreateResult ()\fC [inline]\fP"

.SS "PacketPartyCreateResult::PacketPartyCreateResult (\fBu8\fP InResult, \fBu32\fP InPartyId)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketPartyCreateResult::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketPartyCreateResult::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketPartyCreateResult::PartyId"

.SS "\fBu8\fP PacketPartyCreateResult::Result"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
