.TH "PacketLevelUp" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketLevelUp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketLevelUp\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketLevelUp\fP ()"
.br
.ti -1c
.RI "\fBPacketLevelUp\fP (\fBu32\fP InLevel, \fBs32\fP InMaxHp, \fBs32\fP InAtk, \fBs32\fP InDef, \fBs32\fP InResultExp)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBLevel\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBMaxHp\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBAtk\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBDef\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBResultExp\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketLevelUp::PacketLevelUp ()\fC [inline]\fP"

.SS "PacketLevelUp::PacketLevelUp (\fBu32\fP InLevel, \fBs32\fP InMaxHp, \fBs32\fP InAtk, \fBs32\fP InDef, \fBs32\fP InResultExp)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketLevelUp::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketLevelUp::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP PacketLevelUp::Atk"

.SS "\fBs32\fP PacketLevelUp::Def"

.SS "\fBu32\fP PacketLevelUp::Level"

.SS "\fBs32\fP PacketLevelUp::MaxHp"

.SS "\fBs32\fP PacketLevelUp::ResultExp"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
