.TH "PacketSkillUseFailed" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketSkillUseFailed
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketSkillUseFailed\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBReasonType\fP { \fBRecastTime\fP, \fBCancel\fP, \fBTargetDisappeared\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketSkillUseFailed\fP ()"
.br
.ti -1c
.RI "\fBPacketSkillUseFailed\fP (\fBu8\fP InReason)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBReason\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBPacketSkillUseFailed::ReasonType\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIRecastTime \fP\fP
.TP
\fB\fICancel \fP\fP
.TP
\fB\fITargetDisappeared \fP\fP
.SH "構築子と解体子"
.PP 
.SS "PacketSkillUseFailed::PacketSkillUseFailed ()\fC [inline]\fP"

.SS "PacketSkillUseFailed::PacketSkillUseFailed (\fBu8\fP InReason)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketSkillUseFailed::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketSkillUseFailed::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu8\fP PacketSkillUseFailed::Reason"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
