.TH "PakFileManager" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PakFileManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PakFileManager\&.h>\fP
.PP
FNoncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fB~PakFileManager\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "bool \fBMount\fP (const FString &Path)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBPakFileManager\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
Pakファイル管理\&. 
.SH "構築子と解体子"
.PP 
.SS "PakFileManager::~PakFileManager ()"

.SH "関数詳解"
.PP 
.SS "static \fBPakFileManager\fP& PakFileManager::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "void PakFileManager::Initialize ()"

.SS "bool PakFileManager::Mount (const FString & Path)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
