.TH "PartyInformation" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartyInformation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartyInformation\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPartyInformation\fP ()"
.br
.ti -1c
.RI "\fB~PartyInformation\fP ()"
.br
.ti -1c
.RI "void \fBSetGameMode\fP (\fBAActiveGameMode\fP *pInGameMode)"
.br
.ti -1c
.RI "bool \fBIsJoined\fP () const"
.br
.ti -1c
.RI "bool \fBIsLeader\fP () const"
.br
.ti -1c
.RI "TArray< \fBPartyMemberData\fP > \fBGetMemberList\fP () const"
.br
.ti -1c
.RI "void \fBOnRecvCreateResult\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvDissolutionResult\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvExitResult\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvJoin\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvJoinMember\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvExitMember\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvKickMember\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvDissolution\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SH "詳解"
.PP 
パーティ情報\&. 
.SH "構築子と解体子"
.PP 
.SS "PartyInformation::PartyInformation ()"

.SS "PartyInformation::~PartyInformation ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "TArray< \fBPartyMemberData\fP > PartyInformation::GetMemberList () const"

.SS "bool PartyInformation::IsJoined () const\fC [inline]\fP"

.SS "bool PartyInformation::IsLeader () const\fC [inline]\fP"

.SS "void PartyInformation::OnRecvCreateResult (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvDissolution (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvDissolutionResult (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvExitMember (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvExitResult (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvJoin (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvJoinMember (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::OnRecvKickMember (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PartyInformation::SetGameMode (\fBAActiveGameMode\fP * pInGameMode)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
