.TH "PlayerStatus" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerStatus
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerStatus\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPlayerStatus\fP ()"
.br
.ti -1c
.RI "\fB~PlayerStatus\fP ()"
.br
.ti -1c
.RI "void \fBSetUuid\fP (uint32 InUuid)"
.br
.ti -1c
.RI "void \fBSet\fP (uint32 InLevel, int32 InMaxHp, int32 InAtk, int32 InDef)"
.br
.ti -1c
.RI "void \fBSetExp\fP (int32 InExp)"
.br
.ti -1c
.RI "void \fBSetName\fP (const FString &InName)"
.br
.ti -1c
.RI "const FString & \fBGetName\fP () const"
.br
.ti -1c
.RI "uint32 \fBGetUuid\fP () const"
.br
.ti -1c
.RI "void \fBSetJob\fP (uint8 InJob)"
.br
.ti -1c
.RI "\fBu8\fP \fBGetJob\fP () const"
.br
.ti -1c
.RI "void \fBSetGold\fP (uint32 InGold)"
.br
.ti -1c
.RI "uint32 \fBGetGold\fP () const"
.br
.ti -1c
.RI "uint32 \fBGetLevel\fP () const"
.br
.ti -1c
.RI "int32 \fBGetMaxHp\fP () const"
.br
.ti -1c
.RI "int32 \fBGetAtk\fP () const"
.br
.ti -1c
.RI "int32 \fBGetDef\fP () const"
.br
.ti -1c
.RI "int32 \fBGetExp\fP () const"
.br
.ti -1c
.RI "void \fBSetSkillList\fP (uint32 NormalAttack, uint32 Skill1, uint32 Skill2, uint32 Skill3, uint32 Skill4)"
.br
.ti -1c
.RI "const TArray< uint32 > & \fBGetSkillList\fP () const"
.br
.ti -1c
.RI "void \fBOpenSkillTreeNode\fP (uint32 NodeId)"
.br
.ti -1c
.RI "void \fBRefleshSkillTree\fP ()"
.br
.ti -1c
.RI "const \fBSkillTree\fP & \fBGetSkillTree\fP () const"
.br
.ti -1c
.RI "const \fBItemList\fP & \fBGetItemList\fP () const"
.br
.ti -1c
.RI "void \fBAddItem\fP (uint32 ItemId, uint32 Count)"
.br
.ti -1c
.RI "void \fBSubtractItem\fP (uint32 ItemId, uint32 Count)"
.br
.ti -1c
.RI "void \fBUpdateItemShortcut\fP (uint32 ItemId1, uint32 ItemId2)"
.br
.in -1c
.SH "詳解"
.PP 
プレイヤーステータス 
.SH "構築子と解体子"
.PP 
.SS "PlayerStatus::PlayerStatus ()"

.SS "PlayerStatus::~PlayerStatus ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void PlayerStatus::AddItem (uint32 ItemId, uint32 Count)\fC [inline]\fP"

.SS "int32 PlayerStatus::GetAtk () const\fC [inline]\fP"

.SS "int32 PlayerStatus::GetDef () const\fC [inline]\fP"

.SS "int32 PlayerStatus::GetExp () const\fC [inline]\fP"

.SS "uint32 PlayerStatus::GetGold () const\fC [inline]\fP"

.SS "const \fBItemList\fP& PlayerStatus::GetItemList () const\fC [inline]\fP"

.SS "\fBu8\fP PlayerStatus::GetJob () const\fC [inline]\fP"

.SS "uint32 PlayerStatus::GetLevel () const\fC [inline]\fP"

.SS "int32 PlayerStatus::GetMaxHp () const\fC [inline]\fP"

.SS "const FString& PlayerStatus::GetName () const\fC [inline]\fP"

.SS "const TArray<uint32>& PlayerStatus::GetSkillList () const\fC [inline]\fP"

.SS "const \fBSkillTree\fP& PlayerStatus::GetSkillTree () const\fC [inline]\fP"

.SS "uint32 PlayerStatus::GetUuid () const\fC [inline]\fP"

.SS "void PlayerStatus::OpenSkillTreeNode (uint32 NodeId)"

.SS "void PlayerStatus::RefleshSkillTree ()\fC [inline]\fP"

.SS "void PlayerStatus::Set (uint32 InLevel, int32 InMaxHp, int32 InAtk, int32 InDef)\fC [inline]\fP"

.SS "void PlayerStatus::SetExp (int32 InExp)\fC [inline]\fP"

.SS "void PlayerStatus::SetGold (uint32 InGold)\fC [inline]\fP"

.SS "void PlayerStatus::SetJob (uint8 InJob)\fC [inline]\fP"

.SS "void PlayerStatus::SetName (const FString & InName)\fC [inline]\fP"

.SS "void PlayerStatus::SetSkillList (uint32 NormalAttack, uint32 Skill1, uint32 Skill2, uint32 Skill3, uint32 Skill4)"

.SS "void PlayerStatus::SetUuid (uint32 InUuid)\fC [inline]\fP"

.SS "void PlayerStatus::SubtractItem (uint32 ItemId, uint32 Count)\fC [inline]\fP"

.SS "void PlayerStatus::UpdateItemShortcut (uint32 ItemId1, uint32 ItemId2)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
