.TH "PlayerManager" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPlayerManager\fP ()"
.br
.ti -1c
.RI "\fB~PlayerManager\fP ()"
.br
.ti -1c
.RI "void \fBSetWorld\fP (UWorld *pInWorld)"
.br
.ti -1c
.RI "void \fBAdd\fP (uint8 Uuid, \fBAPlayerCharacterBase\fP *pPlayer)"
.br
.ti -1c
.RI "\fBAPlayerCharacterBase\fP * \fBGet\fP (uint32 Uuid) const"
.br
.ti -1c
.RI "void \fBOnRecvSpawn\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvList\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvMove\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBOnRecvExit\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
プレイヤー管理\&. 
.SH "構築子と解体子"
.PP 
.SS "PlayerManager::PlayerManager ()"

.SS "PlayerManager::~PlayerManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void PlayerManager::Add (uint8 Uuid, \fBAPlayerCharacterBase\fP * pPlayer)"

.SS "\fBAPlayerCharacterBase\fP * PlayerManager::Get (uint32 Uuid) const"

.SS "void PlayerManager::OnRecvExit (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PlayerManager::OnRecvList (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PlayerManager::OnRecvMove (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PlayerManager::OnRecvSpawn (\fBMemoryStreamInterface\fP * pStream)"

.SS "void PlayerManager::Reset ()"

.SS "void PlayerManager::SetWorld (UWorld * pInWorld)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
