.TH "PlayerMove" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerMove
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerMove\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPlayerMove\fP ()"
.br
.ti -1c
.RI "\fB~PlayerMove\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBAGameCharacter\fP *pInCharacter, \fBUMMOGameInstance\fP *pInInst)"
.br
.ti -1c
.RI "void \fBPoll\fP (float DeltaTime)"
.br
.in -1c
.SH "詳解"
.PP 
プレイヤー移動パケット処理クラス 
.SH "構築子と解体子"
.PP 
.SS "PlayerMove::PlayerMove ()"

.SS "PlayerMove::~PlayerMove ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void PlayerMove::Initialize (\fBAGameCharacter\fP * pInCharacter, \fBUMMOGameInstance\fP * pInInst)"

.SS "void PlayerMove::Poll (float DeltaTime)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
