.TH "PlayerManager.h" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'PlayerCharacterBase\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBPlayerManager\fP"
.br
.in -1c
.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
