.TH "QuestMaster" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBQuestItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBQuestItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBQuestItem\fP * QuestMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBQuestItem\fP > QuestMaster::GetAll () const"

.SS "void QuestMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
