.TH "QuestManager" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBQuestManager\fP ()"
.br
.ti -1c
.RI "\fB~QuestManager\fP ()"
.br
.ti -1c
.RI "void \fBSetGameInstance\fP (\fBUMMOGameInstance\fP *pInInst)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBQuestData\fP &Data)"
.br
.ti -1c
.RI "void \fBKillAnpan\fP (uint32 QuestId)"
.br
.ti -1c
.RI "void \fBProgressStage\fP (uint32 QuestId, uint32 StageNo)"
.br
.ti -1c
.RI "void \fBClear\fP (uint32 QuestId)"
.br
.ti -1c
.RI "void \fBRetire\fP (uint32 QuestId)"
.br
.ti -1c
.RI "bool \fBIsActive\fP (uint32 QuestId) const"
.br
.ti -1c
.RI "bool \fBIsClear\fP (uint32 QuestId) const"
.br
.ti -1c
.RI "uint32 \fBGetStageNo\fP (uint32 QuestId) const"
.br
.ti -1c
.RI "TArray< const \fBQuestData\fP * > \fBCollectProgressingQuests\fP () const"
.br
.ti -1c
.RI "void \fBSetActiveQuest\fP (uint32 QuestId, bool bSendSavePacket)"
.br
.ti -1c
.RI "const \fBQuestData\fP * \fBGetActiveQuestData\fP () const"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FOnActiveQuestUpdated \fBOnActiveQuestUpdated\fP"
.br
.in -1c
.SH "詳解"
.PP 
クエスト管理\&. 
.SH "構築子と解体子"
.PP 
.SS "QuestManager::QuestManager ()"

.SS "QuestManager::~QuestManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void QuestManager::Add (const \fBQuestData\fP & Data)"

.SS "void QuestManager::Clear (uint32 QuestId)"

.SS "TArray< const \fBQuestData\fP * > QuestManager::CollectProgressingQuests () const"

.SS "const \fBQuestData\fP * QuestManager::GetActiveQuestData () const"

.SS "uint32 QuestManager::GetStageNo (uint32 QuestId) const"

.SS "void QuestManager::Initialize ()"

.SS "bool QuestManager::IsActive (uint32 QuestId) const"

.SS "bool QuestManager::IsClear (uint32 QuestId) const"

.SS "void QuestManager::KillAnpan (uint32 QuestId)"

.SS "void QuestManager::ProgressStage (uint32 QuestId, uint32 StageNo)"

.SS "void QuestManager::Retire (uint32 QuestId)"

.SS "void QuestManager::SetActiveQuest (uint32 QuestId, bool bSendSavePacket)"

.SS "void QuestManager::SetGameInstance (\fBUMMOGameInstance\fP * pInInst)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "FOnActiveQuestUpdated QuestManager::OnActiveQuestUpdated"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
