.TH "QuestData" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestData\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBStateType\fP { \fBActive\fP, \fBCleared\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBQuestData\fP ()"
.br
.ti -1c
.RI "\fBQuestData\fP (\fBu32\fP InQuestId, \fBu32\fP InStageNo, \fBu32\fP InKillCount, \fBu8\fP InState)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBQuestId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBStageNo\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBKillCount\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBState\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBQuestData::StateType\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIActive \fP\fP
.TP
\fB\fICleared \fP\fP
.SH "構築子と解体子"
.PP 
.SS "QuestData::QuestData ()\fC [inline]\fP"

.SS "QuestData::QuestData (\fBu32\fP InQuestId, \fBu32\fP InStageNo, \fBu32\fP InKillCount, \fBu8\fP InState)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool QuestData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP QuestData::KillCount"

.SS "\fBu32\fP QuestData::QuestId"

.SS "\fBu32\fP QuestData::StageNo"

.SS "\fBu8\fP QuestData::State"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
