.TH "QuestManager.h" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Packet/QuestData\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBQuestManager\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE_OneParam\fP (FOnActiveQuestUpdated, const \fBQuestData\fP *)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE_OneParam (FOnActiveQuestUpdated, const \fBQuestData\fP *)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
