.TH "QuestStageItem" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestStageItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestStageMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBNPC\fP = 0, \fBKILL_ANPAN_IN_AREA\fP = 1, \fBCOLLECT_ITEM\fP = 2 }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBId\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBCondition\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBTargetId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCount\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBNextStageId\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINPC \fP\fP
.TP
\fB\fIKILL_ANPAN_IN_AREA \fP\fP
.TP
\fB\fICOLLECT_ITEM \fP\fP
.SH "関数詳解"
.PP 
.SS "bool QuestStageItem::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu8\fP QuestStageItem::Condition"

.SS "\fBu32\fP QuestStageItem::Count"

.SS "\fBu32\fP QuestStageItem::Id"

.SS "\fBu32\fP QuestStageItem::NextStageId"

.SS "\fBu32\fP QuestStageItem::TargetId"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
