.TH "ScriptExecuterBase" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptExecuterBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptExecuterBase\&.h>\fP
.PP
\fBScriptExecuter\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBScriptExecuterBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~ScriptExecuterBase\fP ()"
.br
.ti -1c
.RI "void \fBSetScriptDir\fP (const char *pScriptDir)"
.br
.ti -1c
.RI "void \fBExecuteScript\fP (const char *pScript)"
.br
.ti -1c
.RI "void \fBResume\fP ()"
.br
.ti -1c
.RI "bool \fBIsFinished\fP () const"
.br
.ti -1c
.RI "virtual void \fBShowMessage_Impl\fP (const std::string &Message)=0"
.br
.ti -1c
.RI "virtual void \fBPushSelection_Impl\fP (const std::string &Message)=0"
.br
.ti -1c
.RI "virtual void \fBShowSelection_Impl\fP ()=0"
.br
.ti -1c
.RI "void \fBOnSelectedSelection\fP (int Index)"
.br
.ti -1c
.RI "virtual void \fBSetFlag\fP (int Flag)=0"
.br
.ti -1c
.RI "virtual bool \fBGetFlag\fP (int Flag)=0"
.br
.ti -1c
.RI "virtual bool \fBIsQuestActive\fP (\fBu32\fP QuestId)=0"
.br
.ti -1c
.RI "virtual void \fBProgressQuest\fP (\fBu32\fP QuestId)=0"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetQuestStageNo\fP (\fBu32\fP QuestId)=0"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetItemCount\fP (\fBu32\fP ItemId)=0"
.br
.ti -1c
.RI "virtual void \fBConsumeItem\fP (\fBu32\fP ItemId, \fBu32\fP Count)=0"
.br
.ti -1c
.RI "virtual void \fBAcceptQuest\fP (\fBu32\fP QuestId)=0"
.br
.ti -1c
.RI "virtual bool \fBIsQuestClear\fP (\fBu32\fP QuestId)=0"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBOnExecuteError\fP (const std::string &ErrorMessage)=0"
.br
.ti -1c
.RI "virtual void \fBOnFinished\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBShowDebugMessage\fP (const std::string &Message)=0"
.br
.ti -1c
.RI "virtual bool \fBIsServer\fP () const =0"
.br
.in -1c
.SH "詳解"
.PP 
スクリプト実行基底クラス 
.SH "構築子と解体子"
.PP 
.SS "ScriptExecuterBase::ScriptExecuterBase ()"

.SS "ScriptExecuterBase::~ScriptExecuterBase ()\fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "virtual void ScriptExecuterBase::AcceptQuest (\fBu32\fP QuestId)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual void ScriptExecuterBase::ConsumeItem (\fBu32\fP ItemId, \fBu32\fP Count)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "void ScriptExecuterBase::ExecuteScript (const char * pScript)"

.SS "virtual bool ScriptExecuterBase::GetFlag (int Flag)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual \fBu32\fP ScriptExecuterBase::GetItemCount (\fBu32\fP ItemId)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual \fBu32\fP ScriptExecuterBase::GetQuestStageNo (\fBu32\fP QuestId)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "bool ScriptExecuterBase::IsFinished () const\fC [inline]\fP"

.SS "virtual bool ScriptExecuterBase::IsQuestActive (\fBu32\fP QuestId)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual bool ScriptExecuterBase::IsQuestClear (\fBu32\fP QuestId)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual bool ScriptExecuterBase::IsServer () const\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual void ScriptExecuterBase::OnExecuteError (const std::string & ErrorMessage)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual void ScriptExecuterBase::OnFinished ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "void ScriptExecuterBase::OnSelectedSelection (int Index)"

.SS "virtual void ScriptExecuterBase::ProgressQuest (\fBu32\fP QuestId)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual void ScriptExecuterBase::PushSelection_Impl (const std::string & Message)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "void ScriptExecuterBase::Resume ()"

.SS "virtual void ScriptExecuterBase::SetFlag (int Flag)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "void ScriptExecuterBase::SetScriptDir (const char * pScriptDir)\fC [inline]\fP"

.SS "virtual void ScriptExecuterBase::ShowDebugMessage (const std::string & Message)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual void ScriptExecuterBase::ShowMessage_Impl (const std::string & Message)\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。
.SS "virtual void ScriptExecuterBase::ShowSelection_Impl ()\fC [pure virtual]\fP"

.PP
\fBScriptExecuter\fPで実装されています。

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
