.TH "ScriptExecuter" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptExecuter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptExecuter\&.h>\fP
.PP
\fBScriptExecuterBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBScriptExecuter\fP ()"
.br
.ti -1c
.RI "virtual \fB~ScriptExecuter\fP ()"
.br
.ti -1c
.RI "void \fBSetGameMode\fP (\fBAActiveGameMode\fP *pInGameMode)"
.br
.ti -1c
.RI "void \fBRunScript\fP (const FString &FileName)"
.br
.ti -1c
.RI "virtual void \fBShowMessage_Impl\fP (const std::string &Message) override"
.br
.ti -1c
.RI "virtual void \fBPushSelection_Impl\fP (const std::string &Message) override"
.br
.ti -1c
.RI "virtual void \fBShowSelection_Impl\fP () override"
.br
.ti -1c
.RI "virtual void \fBSetFlag\fP (int Flag) override"
.br
.ti -1c
.RI "virtual bool \fBGetFlag\fP (int Flag) override"
.br
.ti -1c
.RI "virtual bool \fBIsQuestActive\fP (\fBu32\fP QuestId) override"
.br
.ti -1c
.RI "virtual void \fBProgressQuest\fP (\fBu32\fP QuestId) override"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetQuestStageNo\fP (\fBu32\fP QuestId) override"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetItemCount\fP (\fBu32\fP ItemId) override"
.br
.ti -1c
.RI "virtual void \fBConsumeItem\fP (\fBu32\fP ItemId, \fBu32\fP Count) override"
.br
.ti -1c
.RI "virtual void \fBAcceptQuest\fP (\fBu32\fP QuestId) override"
.br
.ti -1c
.RI "virtual bool \fBIsQuestClear\fP (\fBu32\fP QuestId) override"
.br
.ti -1c
.RI "void \fBConvertFlagFromBitFields\fP (uint32 BitField1, uint32 BitField2, uint32 BitField3)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBOnExecuteError\fP (const std::string &ErrorMessage) override"
.br
.ti -1c
.RI "virtual void \fBOnFinished\fP () override"
.br
.ti -1c
.RI "virtual void \fBShowDebugMessage\fP (const std::string &Message) override"
.br
.ti -1c
.RI "virtual bool \fBIsServer\fP () const override"
.br
.in -1c
.SH "詳解"
.PP 
スクリプト制御クラス 
.SH "構築子と解体子"
.PP 
.SS "ScriptExecuter::ScriptExecuter ()"

.SS "virtual ScriptExecuter::~ScriptExecuter ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "virtual void ScriptExecuter::AcceptQuest (\fBu32\fP QuestId)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual void ScriptExecuter::ConsumeItem (\fBu32\fP ItemId, \fBu32\fP Count)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::ConvertFlagFromBitFields (uint32 BitField1, uint32 BitField2, uint32 BitField3)"

.SS "bool ScriptExecuter::GetFlag (int Flag)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "\fBu32\fP ScriptExecuter::GetItemCount (\fBu32\fP ItemId)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "\fBu32\fP ScriptExecuter::GetQuestStageNo (\fBu32\fP QuestId)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "bool ScriptExecuter::IsQuestActive (\fBu32\fP QuestId)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "bool ScriptExecuter::IsQuestClear (\fBu32\fP QuestId)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual bool ScriptExecuter::IsServer () const\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::OnExecuteError (const std::string & ErrorMessage)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::OnFinished ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual void ScriptExecuter::ProgressQuest (\fBu32\fP QuestId)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::PushSelection_Impl (const std::string & Message)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::RunScript (const FString & FileName)"

.SS "void ScriptExecuter::SetFlag (int Flag)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::SetGameMode (\fBAActiveGameMode\fP * pInGameMode)\fC [inline]\fP"

.SS "void ScriptExecuter::ShowDebugMessage (const std::string & Message)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::ShowMessage_Impl (const std::string & Message)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::ShowSelection_Impl ()\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
