.TH "SkillMaster" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBSkillItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBSkillItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBSkillItem\fP * SkillMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBSkillItem\fP > SkillMaster::GetAll () const"

.SS "void SkillMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
