.TH "D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Skill/State/SkillStateBase.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Client/AnpanMMO/Source/AnpanMMO/Skill/State/SkillStateBase.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBSkillStateBase\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBESkillStateType\fP : uint8 { \fBESkillStateType::Nutral\fP, \fBESkillStateType::Cast\fP, \fBESkillStateType::AutoMode\fP }"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBESkillStateType\fP : uint8\fC [strong]\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINutral \fP\fP
.TP
\fB\fICast \fP\fP
.TP
\fB\fIAutoMode \fP\fP
.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
