.TH "TitleScreenWidget.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TitleScreenWidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Blueprint/UserWidget\&.h'\fP
.br
\fC#include 'VersionDownloader\&.h'\fP
.br
\fC#include 'TitleScreenWidget\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBUTitleScreenWidget\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE_OneParam\fP (FOnConnect, bool)"
.br
.ti -1c
.RI "\fBDECLARE_DELEGATE\fP (FOnReadyToGame)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE (FOnReadyToGame)"

.SS "DECLARE_DELEGATE_OneParam (FOnConnect, bool)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
