.TH "UBlueprintFunctions" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UBlueprintFunctions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlueprintFunctions\&.h>\fP
.PP
UBlueprintFunctionLibraryを継承しています。
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUSimpleDialog\fP * \fBShowSimpleDialog\fP (UObject *pOuter, const FString &DisplayText, int32 ZOrder=0)"
.br
.ti -1c
.RI "static \fBUYesNoDialog\fP * \fBShowYesNoDialog\fP (UObject *pOuter, const FString &DisplayText, int32 ZOrder=0)"
.br
.ti -1c
.RI "static AEmitter * \fBSpawnEffect\fP (UObject *pWorldContext, UParticleSystem *pParticle, const FVector &Position, const FRotator &Rotation)"
.br
.ti -1c
.RI "static FVector \fBGetRandomVector\fP (float Min, float Max)"
.br
.ti -1c
.RI "static void \fBSendRespawnRequest\fP (UObject *pWorldContext)"
.br
.ti -1c
.RI "static FString \fBGetSkillName\fP (int32 SkillId)"
.br
.ti -1c
.RI "static int32 \fBGetRecastTime\fP (int32 SkillId)"
.br
.ti -1c
.RI "static int32 \fBGetItemRecastTime\fP (int32 ItemId)"
.br
.ti -1c
.RI "static int32 \fBGetSkillIdFromItemId\fP (int32 ItemId)"
.br
.ti -1c
.RI "static FString \fBGetItemName\fP (int32 ItemId)"
.br
.ti -1c
.RI "static bool \fBIsValidItem\fP (int32 ItemId)"
.br
.ti -1c
.RI "static FString \fBGetAreaName\fP (int32 AreaId)"
.br
.ti -1c
.RI "static FString \fBGetNPCName\fP (int32 NPCId)"
.br
.in -1c
.SH "詳解"
.PP 
Blueprint用関数群\&. 
.SH "関数詳解"
.PP 
.SS "FString UBlueprintFunctions::GetAreaName (int32 AreaId)\fC [static]\fP"

.SS "FString UBlueprintFunctions::GetItemName (int32 ItemId)\fC [static]\fP"

.SS "int32 UBlueprintFunctions::GetItemRecastTime (int32 ItemId)\fC [static]\fP"

.SS "FString UBlueprintFunctions::GetNPCName (int32 NPCId)\fC [static]\fP"

.SS "FVector UBlueprintFunctions::GetRandomVector (float Min, float Max)\fC [static]\fP"

.SS "int32 UBlueprintFunctions::GetRecastTime (int32 SkillId)\fC [static]\fP"

.SS "int32 UBlueprintFunctions::GetSkillIdFromItemId (int32 ItemId)\fC [static]\fP"

.SS "FString UBlueprintFunctions::GetSkillName (int32 SkillId)\fC [static]\fP"

.SS "bool UBlueprintFunctions::IsValidItem (int32 ItemId)\fC [static]\fP"

.SS "void UBlueprintFunctions::SendRespawnRequest (UObject * pWorldContext)\fC [static]\fP"

.SS "\fBUSimpleDialog\fP * UBlueprintFunctions::ShowSimpleDialog (UObject * pOuter, const FString & DisplayText, int32 ZOrder = \fC0\fP)\fC [static]\fP"

.SS "\fBUYesNoDialog\fP * UBlueprintFunctions::ShowYesNoDialog (UObject * pOuter, const FString & DisplayText, int32 ZOrder = \fC0\fP)\fC [static]\fP"

.SS "AEmitter * UBlueprintFunctions::SpawnEffect (UObject * pWorldContext, UParticleSystem * pParticle, const FVector & Position, const FRotator & Rotation)\fC [static]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
