.TH "UChatWindowWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UChatWindowWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatWindowWidget\&.h>\fP
.PP
UUserWidgetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUChatWindowWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UChatWindowWidget\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBSendChat\fP (\fBEChatType\fP Type, const FString &Message)"
.br
.in -1c
.SH "詳解"
.PP 
チャットウィンドウ 
.SH "構築子と解体子"
.PP 
.SS "UChatWindowWidget::UChatWindowWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UChatWindowWidget::~UChatWindowWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UChatWindowWidget::SendChat (\fBEChatType\fP Type, const FString & Message)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
