.TH "UCharacterNameInputWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UCharacterNameInputWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CharacterNameInputWidget\&.h>\fP
.PP
UUserWidgetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUCharacterNameInputWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UCharacterNameInputWidget\fP ()"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUCharacterNameInputWidget\fP * \fBShow\fP (UObject *pOuter, int32 ZOrder)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBSendRequestPacket\fP (const FString &Name, int32 Job)"
.br
.in -1c
.SH "詳解"
.PP 
キャラクタ名入力Widget 
.SH "構築子と解体子"
.PP 
.SS "UCharacterNameInputWidget::UCharacterNameInputWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UCharacterNameInputWidget::~UCharacterNameInputWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UCharacterNameInputWidget::SendRequestPacket (const FString & Name, int32 Job)\fC [protected]\fP"

.SS "\fBUCharacterNameInputWidget\fP * UCharacterNameInputWidget::Show (UObject * pOuter, int32 ZOrder)\fC [static]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
