.TH "UGameMenuWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UGameMenuWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameMenuWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUGameMenuWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UGameMenuWidget\fP ()"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUGameMenuWidget\fP * \fBShowWidget\fP (UObject *pOuter)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBShowPartyMenu\fP ()"
.br
.ti -1c
.RI "void \fBLogOut\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
ゲームメニューWidget 
.SH "構築子と解体子"
.PP 
.SS "UGameMenuWidget::UGameMenuWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UGameMenuWidget::~UGameMenuWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UGameMenuWidget::LogOut ()\fC [protected]\fP"

.SS "void UGameMenuWidget::ShowPartyMenu ()\fC [protected]\fP"

.SS "\fBUGameMenuWidget\fP * UGameMenuWidget::ShowWidget (UObject * pOuter)\fC [static]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
