.TH "UInstanceAreaTicketMenuWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UInstanceAreaTicketMenuWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InstanceAreaTicketMenuWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUInstanceAreaTicketMenuWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UInstanceAreaTicketMenuWidget\fP ()"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static void \fBShowWidget\fP (UObject *pOuter, uint32 TicketId)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBSendEnter\fP ()"
.br
.ti -1c
.RI "void \fBSendDiscard\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
インスタンスマップチケットメニュー 
.SH "構築子と解体子"
.PP 
.SS "UInstanceAreaTicketMenuWidget::UInstanceAreaTicketMenuWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UInstanceAreaTicketMenuWidget::~UInstanceAreaTicketMenuWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UInstanceAreaTicketMenuWidget::SendDiscard ()\fC [protected]\fP"

.SS "void UInstanceAreaTicketMenuWidget::SendEnter ()\fC [protected]\fP"

.SS "void UInstanceAreaTicketMenuWidget::ShowWidget (UObject * pOuter, uint32 TicketId)\fC [static]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
