.TH "UInstanceAreaWaitingWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UInstanceAreaWaitingWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InstanceAreaWaitingWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUInstanceAreaWaitingWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UInstanceAreaWaitingWidget\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRecvPacket\fP (uint8 ID) override"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
インスタンスエリア移動待機Widegt 
.SH "構築子と解体子"
.PP 
.SS "UInstanceAreaWaitingWidget::UInstanceAreaWaitingWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UInstanceAreaWaitingWidget::~UInstanceAreaWaitingWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UInstanceAreaWaitingWidget::OnRecvPacket (uint8 ID)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBULayeredMenuWidgetBase\fPを再実装しています。

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
