.TH "UItemMenu" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UItemMenu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemMenu\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUItemMenu\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UItemMenu\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRecvPacket\fP (uint8 ID) override"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBInitEvent\fP (const TArray< \fBFItemData\fP > &Items, const \fBFItemData\fP &ItemShortcut1, const \fBFItemData\fP &ItemShortcut2)"
.br
.ti -1c
.RI "void \fBInitEvent_Implementation\fP (const TArray< \fBFItemData\fP > &Items, const \fBFItemData\fP &ItemShortcut1, const \fBFItemData\fP &ItemShortcut2)"
.br
.ti -1c
.RI "void \fBUse\fP (const \fBFItemData\fP &Data)"
.br
.ti -1c
.RI "void \fBSubtract\fP (const \fBFItemData\fP &Data, int32 Count)"
.br
.ti -1c
.RI "void \fBSaveShortcut\fP (const \fBFItemData\fP &Data1, const \fBFItemData\fP &Data2)"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
アイテムメニュー 
.SH "構築子と解体子"
.PP 
.SS "UItemMenu::UItemMenu (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UItemMenu::~UItemMenu ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UItemMenu::Init ()"

.SS "void UItemMenu::InitEvent (const TArray< \fBFItemData\fP > & Items, const \fBFItemData\fP & ItemShortcut1, const \fBFItemData\fP & ItemShortcut2)\fC [protected]\fP"

.SS "void UItemMenu::InitEvent_Implementation (const TArray< \fBFItemData\fP > & Items, const \fBFItemData\fP & ItemShortcut1, const \fBFItemData\fP & ItemShortcut2)\fC [inline]\fP, \fC [protected]\fP"

.SS "void UItemMenu::OnRecvPacket (uint8 ID)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBULayeredMenuWidgetBase\fPを再実装しています。
.SS "void UItemMenu::SaveShortcut (const \fBFItemData\fP & Data1, const \fBFItemData\fP & Data2)\fC [protected]\fP"

.SS "void UItemMenu::Subtract (const \fBFItemData\fP & Data, int32 Count)\fC [protected]\fP"

.SS "void UItemMenu::Use (const \fBFItemData\fP & Data)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
