.TH "ULayeredMenuWidgetBase" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ULayeredMenuWidgetBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LayeredMenuWidgetBase\&.h>\fP
.PP
UUserWidgetを継承しています。
.PP
\fBUGameMenuWidget\fP, \fBUInstanceAreaTicketMenuWidget\fP, \fBUInstanceAreaWaitingWidget\fP, \fBUItemMenu\fP, \fBUNoticeMenuWidget\fP, \fBUPartyCreateMenuWidget\fP, \fBUPartyInfoMenuWidget\fP, \fBUPartyMemberInfoMenuWidget\fP, \fBUQuestMenu\fP, \fBUScriptMessageWidget\fP, \fBUScriptSelectionWidget\fP, \fBUScriptWidgetRoot\fP, \fBUSkillMenu\fP, \fBUWarpAreaList\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBULayeredMenuWidgetBase\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~ULayeredMenuWidgetBase\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP (int32 InZOrder=0)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "void \fBCloseChild\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRecvPacket\fP (uint8 ID)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FOnMenuClosed \fBOnMenuClosed\fP"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBBack\fP ()"
.br
.ti -1c
.RI "void \fBOnBackFromChild\fP ()"
.br
.ti -1c
.RI "void \fBOnBackFromChild_Implementation\fP ()"
.br
.ti -1c
.RI "void \fBShowChild\fP (\fBULayeredMenuWidgetBase\fP *pInChildMenu, bool bHideSelf=true)"
.br
.in -1c
.SH "詳解"
.PP 
レイヤに分割されたメニューWidget基底クラス 
.SH "構築子と解体子"
.PP 
.SS "ULayeredMenuWidgetBase::ULayeredMenuWidgetBase (const FObjectInitializer & ObjectInitializer)"

.SS "virtual ULayeredMenuWidgetBase::~ULayeredMenuWidgetBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ULayeredMenuWidgetBase::Back ()\fC [protected]\fP"

.SS "void ULayeredMenuWidgetBase::Close ()"

.SS "void ULayeredMenuWidgetBase::CloseChild ()"

.SS "void ULayeredMenuWidgetBase::OnBackFromChild ()\fC [protected]\fP"

.SS "void ULayeredMenuWidgetBase::OnBackFromChild_Implementation ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void ULayeredMenuWidgetBase::OnRecvPacket (uint8 ID)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBUSkillMenu\fP, \fBUQuestMenu\fP, \fBUItemMenu\fP, \fBUInstanceAreaWaitingWidget\fPで再実装されています。
.SS "void ULayeredMenuWidgetBase::Show (int32 InZOrder = \fC0\fP)"

.SS "void ULayeredMenuWidgetBase::ShowChild (\fBULayeredMenuWidgetBase\fP * pInChildMenu, bool bHideSelf = \fCtrue\fP)\fC [protected]\fP"

.SH "メンバ詳解"
.PP 
.SS "FOnMenuClosed ULayeredMenuWidgetBase::OnMenuClosed"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
