.TH "ULevelManager" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ULevelManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelManager\&.h>\fP
.PP
UObjectを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBULevelManager\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~ULevelManager\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP ()"
.br
.ti -1c
.RI "void \fBLoad\fP (const FString &LevelPath)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FOnLevelLoadFinished \fBOnLevelLoadFinished\fP"
.br
.in -1c
.SH "詳解"
.PP 
レベル管理\&. 
.SH "構築子と解体子"
.PP 
.SS "ULevelManager::ULevelManager (const FObjectInitializer & ObjectInitializer)"

.SS "virtual ULevelManager::~ULevelManager ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ULevelManager::Load (const FString & LevelPath)"

.SS "void ULevelManager::Poll ()"

.SH "メンバ詳解"
.PP 
.SS "FOnLevelLoadFinished ULevelManager::OnLevelLoadFinished"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
