.TH "UNoticeBase" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNoticeBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeMenuWidget\&.h>\fP
.PP
UObjectを継承しています。
.PP
\fBUPartyInviteNotice\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUNoticeBase\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UNoticeBase\fP ()"
.br
.ti -1c
.RI "void \fBAction\fP ()"
.br
.ti -1c
.RI "virtual \fBENoticeType\fP \fBGetNoticeType\fP () const"
.br
.ti -1c
.RI "const FString & \fBGetCharacterName\fP () const"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBOnAction\fP ()"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "uint32 \fBCustomerId\fP"
.br
.ti -1c
.RI "uint32 \fBNoticeUuid\fP"
.br
.ti -1c
.RI "FString \fBCharacterName\fP"
.br
.in -1c
.SH "詳解"
.PP 
通知基底クラス 
.SH "構築子と解体子"
.PP 
.SS "UNoticeBase::UNoticeBase (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UNoticeBase::~UNoticeBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UNoticeBase::Action ()"

.SS "const FString& UNoticeBase::GetCharacterName () const\fC [inline]\fP"

.SS "virtual \fBENoticeType\fP UNoticeBase::GetNoticeType () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBUPartyInviteNotice\fPで再実装されています。
.SS "virtual void UNoticeBase::OnAction ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBUPartyInviteNotice\fPで再実装されています。
.SH "メンバ詳解"
.PP 
.SS "FString UNoticeBase::CharacterName\fC [protected]\fP"

.SS "uint32 UNoticeBase::CustomerId\fC [protected]\fP"

.SS "uint32 UNoticeBase::NoticeUuid\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
