.TH "UNoticeMenuWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNoticeMenuWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeMenuWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUNoticeMenuWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UNoticeMenuWidget\fP ()"
.br
.ti -1c
.RI "virtual void \fBNativeConstruct\fP () override"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static void \fBShowWidget\fP (UObject *pOuter)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnInit_Implementation\fP ()"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "TArray< \fBUNoticeBase\fP * > \fBNoticeList\fP"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
通知メニュー 
.SH "構築子と解体子"
.PP 
.SS "UNoticeMenuWidget::UNoticeMenuWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UNoticeMenuWidget::~UNoticeMenuWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UNoticeMenuWidget::NativeConstruct ()\fC [override]\fP, \fC [virtual]\fP"

.SS "void UNoticeMenuWidget::OnInit ()\fC [protected]\fP"

.SS "void UNoticeMenuWidget::OnInit_Implementation ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void UNoticeMenuWidget::ShowWidget (UObject * pOuter)\fC [static]\fP"

.SH "メンバ詳解"
.PP 
.SS "TArray<\fBUNoticeBase\fP *> UNoticeMenuWidget::NoticeList\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
