.TH "UNoticeMenuItem" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNoticeMenuItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeMenuWidget\&.h>\fP
.PP
UUserWidgetを継承しています。
.PP
\fBUPartyInviteNoticeItem\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUNoticeMenuItem\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UNoticeMenuItem\fP ()"
.br
.ti -1c
.RI "void \fBSetNotice\fP (\fBUNoticeBase\fP *pInNotice)"
.br
.ti -1c
.RI "void \fBSetParent\fP (\fBUNoticeMenuWidget\fP *pInParent)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBAction\fP ()"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "\fBUNoticeBase\fP * \fBpNotice\fP"
.br
.in -1c
.SH "詳解"
.PP 
通知メニューのアイテム 
.SH "構築子と解体子"
.PP 
.SS "UNoticeMenuItem::UNoticeMenuItem (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UNoticeMenuItem::~UNoticeMenuItem ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UNoticeMenuItem::Action ()\fC [protected]\fP"

.SS "void UNoticeMenuItem::SetNotice (\fBUNoticeBase\fP * pInNotice)\fC [inline]\fP"

.SS "void UNoticeMenuItem::SetParent (\fBUNoticeMenuWidget\fP * pInParent)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBUNoticeBase\fP* UNoticeMenuItem::pNotice\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
