.TH "UNPCDataAsset" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNPCDataAsset
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCDataAsset\&.h>\fP
.PP
UDataAssetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUNPCDataAsset\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UNPCDataAsset\fP ()"
.br
.ti -1c
.RI "USkeletalMesh * \fBGet\fP (int32 Index)"
.br
.in -1c
.SH "詳解"
.PP 
NPCリソースのDataAsset 
.SH "構築子と解体子"
.PP 
.SS "UNPCDataAsset::UNPCDataAsset (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UNPCDataAsset::~UNPCDataAsset ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "USkeletalMesh * UNPCDataAsset::Get (int32 Index)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
