.TH "UPartyInviteNoticeItem" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPartyInviteNoticeItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeMenuWidget\&.h>\fP
.PP
\fBUNoticeMenuItem\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUPartyInviteNoticeItem\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UPartyInviteNoticeItem\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBSetAccept\fP (bool bAccept)"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
パーティ勧誘通知アイテム ※勧誘を受けるかどうかを設定する必要があるためC++で定義。 
.SH "構築子と解体子"
.PP 
.SS "UPartyInviteNoticeItem::UPartyInviteNoticeItem (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UPartyInviteNoticeItem::~UPartyInviteNoticeItem ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UPartyInviteNoticeItem::SetAccept (bool bAccept)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
