.TH "UPartyInviteNotice" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPartyInviteNotice
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeMenuWidget\&.h>\fP
.PP
\fBUNoticeBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUPartyInviteNotice\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UPartyInviteNotice\fP ()"
.br
.ti -1c
.RI "virtual \fBENoticeType\fP \fBGetNoticeType\fP () const override"
.br
.ti -1c
.RI "void \fBSetAccept\fP (bool bInAccept)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUPartyInviteNotice\fP * \fBCreate\fP (UObject *pOuter, uint32 \fBNoticeUuid\fP, uint32 \fBCustomerId\fP, const FString &\fBCharacterName\fP)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBOnAction\fP () override"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
パーティ勧誘通知\&. 
.SH "構築子と解体子"
.PP 
.SS "UPartyInviteNotice::UPartyInviteNotice (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UPartyInviteNotice::~UPartyInviteNotice ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "\fBUPartyInviteNotice\fP * UPartyInviteNotice::Create (UObject * pOuter, uint32 NoticeUuid, uint32 CustomerId, const FString & CharacterName)\fC [static]\fP"

.SS "virtual \fBENoticeType\fP UPartyInviteNotice::GetNoticeType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBUNoticeBase\fPを再実装しています。
.SS "void UPartyInviteNotice::OnAction ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBUNoticeBase\fPを再実装しています。
.SS "void UPartyInviteNotice::SetAccept (bool bInAccept)\fC [inline]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
