.TH "UPlayerHPGauge" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPlayerHPGauge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerHPGauge\&.h>\fP
.PP
UUserWidgetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUPlayerHPGauge\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UPlayerHPGauge\fP ()"
.br
.ti -1c
.RI "virtual void \fBNativeTick\fP (const FGeometry &InGeometry, float InDeltaTime) override"
.br
.ti -1c
.RI "void \fBInit\fP (int32 InCurrentHp, int32 InMaxHp)"
.br
.ti -1c
.RI "void \fBRespawn\fP ()"
.br
.ti -1c
.RI "void \fBDamaged\fP (int32 Value)"
.br
.ti -1c
.RI "void \fBHealed\fP (int32 Value)"
.br
.ti -1c
.RI "void \fBLevelUp\fP (int32 InMaxHp)"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "float \fBProgressRate\fP"
.br
.in -1c
.SH "詳解"
.PP 
プレイヤーＨＰゲージ 
.SH "構築子と解体子"
.PP 
.SS "UPlayerHPGauge::UPlayerHPGauge (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UPlayerHPGauge::~UPlayerHPGauge ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UPlayerHPGauge::Damaged (int32 Value)"

.SS "void UPlayerHPGauge::Healed (int32 Value)"

.SS "void UPlayerHPGauge::Init (int32 InCurrentHp, int32 InMaxHp)"

.SS "void UPlayerHPGauge::LevelUp (int32 InMaxHp)"

.SS "void UPlayerHPGauge::NativeTick (const FGeometry & InGeometry, float InDeltaTime)\fC [override]\fP, \fC [virtual]\fP"

.SS "void UPlayerHPGauge::Respawn ()"

.SH "メンバ詳解"
.PP 
.SS "float UPlayerHPGauge::ProgressRate\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
