.TH "UScriptMessageWidget" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UScriptMessageWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptMessageWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUScriptMessageWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UScriptMessageWidget\fP ()"
.br
.ti -1c
.RI "void \fBSetMessage\fP (const FString &InMessage)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUScriptMessageWidget\fP * \fBCreate\fP (UObject *pOuter)"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "FString \fBMessage\fP"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
スクリプト：メッセージウィンドウ 
.SH "構築子と解体子"
.PP 
.SS "UScriptMessageWidget::UScriptMessageWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UScriptMessageWidget::~UScriptMessageWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "\fBUScriptMessageWidget\fP * UScriptMessageWidget::Create (UObject * pOuter)\fC [static]\fP"

.SS "void UScriptMessageWidget::SetMessage (const FString & InMessage)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "FString UScriptMessageWidget::Message\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
