.TH "UScriptWidgetRoot" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UScriptWidgetRoot
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptWidgetRoot\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUScriptWidgetRoot\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UScriptWidgetRoot\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBShowMessage\fP (const FString &Message)"
.br
.ti -1c
.RI "void \fBAddSelection\fP (const FString &Item)"
.br
.ti -1c
.RI "void \fBShowSelection\fP ()"
.br
.ti -1c
.RI "void \fBCloseWidget\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
スクリプトWidgetの親\&. 
.SH "構築子と解体子"
.PP 
.SS "UScriptWidgetRoot::UScriptWidgetRoot (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UScriptWidgetRoot::~UScriptWidgetRoot ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UScriptWidgetRoot::AddSelection (const FString & Item)"

.SS "void UScriptWidgetRoot::CloseWidget ()"

.SS "void UScriptWidgetRoot::Init ()"

.SS "void UScriptWidgetRoot::ShowMessage (const FString & Message)"

.SS "void UScriptWidgetRoot::ShowSelection ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
