.TH "UScriptSelectionWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UScriptSelectionWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptSelectionWidget\&.h>\fP
.PP
\fBULayeredMenuWidgetBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUScriptSelectionWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~UScriptSelectionWidget\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBAddSelection\fP (const FString &Item)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBUScriptSelectionWidget\fP * \fBCreate\fP (UObject *pOuter)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBSelect\fP (int32 Index)"
.br
.ti -1c
.RI "void \fBInitEvent\fP (const TArray< FString > &Items)"
.br
.ti -1c
.RI "void \fBInitEvent_Implementation\fP (const TArray< FString > &Items)"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
スクリプト：選択肢Widget 
.SH "構築子と解体子"
.PP 
.SS "UScriptSelectionWidget::UScriptSelectionWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual UScriptSelectionWidget::~UScriptSelectionWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void UScriptSelectionWidget::AddSelection (const FString & Item)"

.SS "\fBUScriptSelectionWidget\fP * UScriptSelectionWidget::Create (UObject * pOuter)\fC [static]\fP"

.SS "void UScriptSelectionWidget::Init ()"

.SS "void UScriptSelectionWidget::InitEvent (const TArray< FString > & Items)\fC [protected]\fP"

.SS "void UScriptSelectionWidget::InitEvent_Implementation (const TArray< FString > & Items)\fC [inline]\fP, \fC [protected]\fP"

.SS "void UScriptSelectionWidget::Select (int32 Index)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
