.TH "USkillListWidget" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USkillListWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillListWidget\&.h>\fP
.PP
UUserWidgetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUSkillListWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~USkillListWidget\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBInitEvent\fP (const TArray< \fBFSkillTreeNode\fP > &Nodes, int32 Skill1, int32 Skill2, int32 Skill3, int32 Skill4)"
.br
.ti -1c
.RI "void \fBInitEvent_Implementation\fP (const TArray< \fBFSkillTreeNode\fP > &Nodes, int32 Skill1, int32 Skill2, int32 Skill3, int32 Skill4)"
.br
.ti -1c
.RI "void \fBSendSaveSkillListRequest\fP (int32 Skill1, int32 Skill2, int32 Skill3, int32 Skill4)"
.br
.in -1c
.SH "詳解"
.PP 
スキルリスト画面\&. 
.SH "構築子と解体子"
.PP 
.SS "USkillListWidget::USkillListWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual USkillListWidget::~USkillListWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void USkillListWidget::Init ()"

.SS "void USkillListWidget::InitEvent (const TArray< \fBFSkillTreeNode\fP > & Nodes, int32 Skill1, int32 Skill2, int32 Skill3, int32 Skill4)\fC [protected]\fP"

.SS "void USkillListWidget::InitEvent_Implementation (const TArray< \fBFSkillTreeNode\fP > & Nodes, int32 Skill1, int32 Skill2, int32 Skill3, int32 Skill4)\fC [inline]\fP, \fC [protected]\fP"

.SS "void USkillListWidget::SendSaveSkillListRequest (int32 Skill1, int32 Skill2, int32 Skill3, int32 Skill4)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
