.TH "USkillTreeWidget" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USkillTreeWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillTreeWidget\&.h>\fP
.PP
UUserWidgetを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBUSkillTreeWidget\fP (const FObjectInitializer &ObjectInitializer)"
.br
.ti -1c
.RI "virtual \fB~USkillTreeWidget\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBInitEvent\fP (const TArray< \fBFSkillTreeNode\fP > &NodeList)"
.br
.ti -1c
.RI "void \fBInitEvent_Implementation\fP (const TArray< \fBFSkillTreeNode\fP > &NodeList)"
.br
.ti -1c
.RI "void \fBSendOpenRequest\fP (const \fBFSkillTreeNode\fP &Item)"
.br
.in -1c
.SH "詳解"
.PP 
スキルツリー画面\&. 
.SH "構築子と解体子"
.PP 
.SS "USkillTreeWidget::USkillTreeWidget (const FObjectInitializer & ObjectInitializer)"

.SS "virtual USkillTreeWidget::~USkillTreeWidget ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void USkillTreeWidget::Init ()"

.SS "void USkillTreeWidget::InitEvent (const TArray< \fBFSkillTreeNode\fP > & NodeList)\fC [protected]\fP"

.SS "void USkillTreeWidget::InitEvent_Implementation (const TArray< \fBFSkillTreeNode\fP > & NodeList)\fC [inline]\fP, \fC [protected]\fP"

.SS "void USkillTreeWidget::SendOpenRequest (const \fBFSkillTreeNode\fP & Item)\fC [protected]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
