.TH "Util" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Util
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Util\&.h>\fP
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "template<class T > static T * \fBLoadBlueprint\fP (UObject *pOuter, const TCHAR *Path)"
.br
.ti -1c
.RI "template<class T > static T * \fBSpawnFromBlueprint\fP (UWorld *pWorld, const TCHAR *Path, const FVector &Position, const FRotator &Rotation)"
.br
.in -1c
.SH "詳解"
.PP 
ユーティリティクラス 
.SH "関数詳解"
.PP 
.SS "template<class T > static T* Util::LoadBlueprint (UObject * pOuter, const TCHAR * Path)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class T > static T* Util::SpawnFromBlueprint (UWorld * pWorld, const TCHAR * Path, const FVector & Position, const FRotator & Rotation)\fC [inline]\fP, \fC [static]\fP"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
