.TH "VersionDownloader.h" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VersionDownloader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Connection/HttpConnection\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBVersionDownloader\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DELEGATE_OneParam\fP (FDownloadResult, bool)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DELEGATE_OneParam (FDownloadResult, bool)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
