.TH "VersionFile" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VersionFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VersionFile\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBVersionFile\fP ()"
.br
.ti -1c
.RI "\fBVersionFile\fP (const TArray< uint8 > &Content)"
.br
.ti -1c
.RI "\fB~VersionFile\fP ()"
.br
.ti -1c
.RI "TArray< FString > \fBGetAllFiles\fP () const"
.br
.ti -1c
.RI "FString \fBGetHash\fP (const FString &FileName) const"
.br
.ti -1c
.RI "void \fBConfigure\fP (const TArray< uint8 > &Content)"
.br
.in -1c
.SH "詳解"
.PP 
バージョンファイルクラス 
.SH "構築子と解体子"
.PP 
.SS "VersionFile::VersionFile ()"

.SS "VersionFile::VersionFile (const TArray< uint8 > & Content)"

.SS "VersionFile::~VersionFile ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void VersionFile::Configure (const TArray< uint8 > & Content)"

.SS "TArray< FString > VersionFile::GetAllFiles () const"

.SS "FString VersionFile::GetHash (const FString & FileName) const"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
