.TH "VersionDownloader" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VersionDownloader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VersionDownloader\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBVersionDownloader\fP ()"
.br
.ti -1c
.RI "\fB~VersionDownloader\fP ()"
.br
.ti -1c
.RI "bool \fBStart\fP (const FString &InURL, const FString &InSavePath)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "FDownloadResult \fBDownloadResult\fP"
.br
.in -1c
.SH "詳解"
.PP 
バージョンファイルで管理されたファイルのダウンロードクラス 
.SH "構築子と解体子"
.PP 
.SS "VersionDownloader::VersionDownloader ()"

.SS "VersionDownloader::~VersionDownloader ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool VersionDownloader::Start (const FString & InURL, const FString & InSavePath)"

.SH "メンバ詳解"
.PP 
.SS "FDownloadResult VersionDownloader::DownloadResult"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
