.TH "WarpDataItem" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WarpDataItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WarpDataMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBWarpDataId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAreaId\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool WarpDataItem::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP WarpDataItem::AreaId"

.SS "\fBu32\fP WarpDataItem::ID"

.SS "\fBu32\fP WarpDataItem::WarpDataId"

.SS "float WarpDataItem::X"

.SS "float WarpDataItem::Y"

.SS "float WarpDataItem::Z"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
