.TH "WarpPointMaster" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WarpPointMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WarpPointMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBWarpPointItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBWarpPointItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBWarpPointItem\fP * WarpPointMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBWarpPointItem\fP > WarpPointMaster::GetAll () const"

.SS "void WarpPointMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
