.TH "WarpDataMaster" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WarpDataMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WarpDataMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "TArray< \fBWarpDataItem\fP > \fBGetAll\fP () const"
.br
.ti -1c
.RI "const \fBWarpDataItem\fP * \fBGet\fP (\fBu32\fP Key) const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "const \fBWarpDataItem\fP * WarpDataMaster::Get (\fBu32\fP Key) const"

.SS "TArray< \fBWarpDataItem\fP > WarpDataMaster::GetAll () const"

.SS "void WarpDataMaster::Load ()"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
