.TH "WarpPointItem" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WarpPointItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WarpPointMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAreaId\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBWarpDataId\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool WarpPointItem::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP WarpPointItem::AreaId"

.SS "\fBu32\fP WarpPointItem::Id"

.SS "\fBu32\fP WarpPointItem::WarpDataId"

.SS "float WarpPointItem::X"

.SS "float WarpPointItem::Y"

.SS "float WarpPointItem::Z"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
