.TH "WarpPointManager" 3 "2018年12月20日(木)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WarpPointManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WarpPointManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBWarpPointManager\fP ()"
.br
.ti -1c
.RI "\fB~WarpPointManager\fP ()"
.br
.ti -1c
.RI "void \fBSetWorld\fP (UWorld *pInWorld)"
.br
.ti -1c
.RI "void \fBSpawn\fP (uint32 AreaId)"
.br
.ti -1c
.RI "void \fBSpawnFromWarpPointId\fP (uint32 WarpPointId)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
ワープポイント管理クラス 
.SH "構築子と解体子"
.PP 
.SS "WarpPointManager::WarpPointManager ()"

.SS "WarpPointManager::~WarpPointManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void WarpPointManager::Reset ()"

.SS "void WarpPointManager::SetWorld (UWorld * pInWorld)\fC [inline]\fP"

.SS "void WarpPointManager::Spawn (uint32 AreaId)"

.SS "void WarpPointManager::SpawnFromWarpPointId (uint32 WarpPointId)"


.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
