.TH "YesNoDialog.h" 3 "2018年12月21日(金)" "AnpanMMO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YesNoDialog.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'Blueprint/UserWidget\&.h'\fP
.br
\fC#include 'YesNoDialog\&.generated\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBUYesNoDialog\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBDECLARE_DYNAMIC_MULTICAST_DELEGATE\fP (FOnDialogResult)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnDialogResult)"

.SH "著者"
.PP 
 AnpanMMOのソースコードから抽出しました。
