.TH "AnpanPopAreaMaster" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanPopAreaMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanPopAreaMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBLoad\fP (const \fBMySqlConnection\fP &Connection)"
.br
.ti -1c
.RI "std::vector< const \fBAnpanPopAreaItem\fP * > \fBCollectItems\fP (\fBu32\fP Key) const"
.br
.ti -1c
.RI "std::vector< \fBAnpanPopAreaItem\fP > \fBGetAll\fP () const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "std::vector< const \fBAnpanPopAreaItem\fP * > AnpanPopAreaMaster::CollectItems (\fBu32\fP Key) const"

.SS "std::vector< \fBAnpanPopAreaItem\fP > AnpanPopAreaMaster::GetAll () const"

.SS "bool AnpanPopAreaMaster::Load (const \fBMySqlConnection\fP & Connection)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
