.TH "AnpanItem" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanMaster\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBHp\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBAtk\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBDef\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBExp\fP"
.br
.ti -1c
.RI "float \fBScale\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBDropId\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP AnpanItem::Atk"

.SS "\fBs32\fP AnpanItem::Def"

.SS "\fBu32\fP AnpanItem::DropId"

.SS "\fBs32\fP AnpanItem::Exp"

.SS "\fBs32\fP AnpanItem::Hp"

.SS "\fBu32\fP AnpanItem::ID"

.SS "float AnpanItem::Scale"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
