.TH "AnpanManager" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanManager\fP ()"
.br
.ti -1c
.RI "\fB~AnpanManager\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBu32\fP AreaId)"
.br
.ti -1c
.RI "void \fBPoll\fP (int DeltaTime)"
.br
.ti -1c
.RI "\fBAnpanPtr\fP \fBGet\fP (\fBu32\fP Uuid) const"
.br
.ti -1c
.RI "void \fBSetSpawnCallback\fP (const SpawnFunc &InOnSpawn)"
.br
.ti -1c
.RI "void \fBMakeListPacket\fP (\fBPacketAnpanList\fP &Packet)"
.br
.ti -1c
.RI "\fBu32\fP \fBGetCount\fP () const"
.br
.ti -1c
.RI "void \fBSpawn\fP (\fBu32\fP MasterId, const \fBVector3D\fP &Position)"
.br
.ti -1c
.RI "void \fBGetAllAsCharacterPtr\fP (std::vector< \fBCharacterPtr\fP > &OutList) const"
.br
.in -1c
.SH "詳解"
.PP 
アンパン管理クラス 
.SH "構築子と解体子"
.PP 
.SS "AnpanManager::AnpanManager ()"

.SS "AnpanManager::~AnpanManager ()"

.SH "関数詳解"
.PP 
.SS "\fBAnpanPtr\fP AnpanManager::Get (\fBu32\fP Uuid) const"

.SS "void AnpanManager::GetAllAsCharacterPtr (std::vector< \fBCharacterPtr\fP > & OutList) const"

.SS "\fBu32\fP AnpanManager::GetCount () const\fC [inline]\fP"

.SS "void AnpanManager::Initialize (\fBu32\fP AreaId)"

.SS "void AnpanManager::MakeListPacket (\fBPacketAnpanList\fP & Packet)"

.SS "void AnpanManager::Poll (int DeltaTime)"

.SS "void AnpanManager::SetSpawnCallback (const SpawnFunc & InOnSpawn)\fC [inline]\fP"

.SS "void AnpanManager::Spawn (\fBu32\fP MasterId, const \fBVector3D\fP & Position)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
