.TH "AnpanMovePacketData" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanMovePacketData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanAIPacketData\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanMovePacketData\fP (\fBu32\fP InUuid, const \fBVector3D\fP &InPos, int InTime)"
.br
.ti -1c
.RI "\fBPacketMoveAnpan\fP \fBCreatePacket\fP ()"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "AnpanMovePacketData::AnpanMovePacketData (\fBu32\fP InUuid, const \fBVector3D\fP & InPos, int InTime)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "\fBPacketMoveAnpan\fP AnpanMovePacketData::CreatePacket ()\fC [inline]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
