.TH "AnpanMaster" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBLoad\fP (const \fBMySqlConnection\fP &Connection)"
.br
.ti -1c
.RI "const \fBAnpanItem\fP * \fBGetItem\fP (\fBu32\fP Key) const"
.br
.ti -1c
.RI "std::vector< \fBAnpanItem\fP > \fBGetAll\fP () const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "std::vector< \fBAnpanItem\fP > AnpanMaster::GetAll () const"

.SS "const \fBAnpanItem\fP * AnpanMaster::GetItem (\fBu32\fP Key) const"

.SS "bool AnpanMaster::Load (const \fBMySqlConnection\fP & Connection)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
