.TH "AnpanPopArea.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanPopArea.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/function\&.hpp>\fP
.br
\fC#include 'Math/Vector3D\&.h'\fP
.br
\fC#include 'AnpanManager\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBAnpanPopArea\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
