.TH "Anpan.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Anpan.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Character/CharacterBase\&.h'\fP
.br
\fC#include 'AI/AnpanAI\&.h'\fP
.br
\fC#include 'Packet/CharacterType\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBAnpan\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
