.TH "AnpanAIStateNonActive" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanAIStateNonActive
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanAIStateNonActive\&.h>\fP
.PP
\fBAnpanAIStateBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanAIStateNonActive\fP (\fBAnpan\fP *pInParent)"
.br
.ti -1c
.RI "virtual \fB~AnpanAIStateNonActive\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDamaged\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP (int DeltaTime)"
.br
.in -1c
.SH "詳解"
.PP 
アンパンＡＩステート：ノンアクティブ状態\&. 
.SH "構築子と解体子"
.PP 
.SS "AnpanAIStateNonActive::AnpanAIStateNonActive (\fBAnpan\fP * pInParent)"

.SS "virtual AnpanAIStateNonActive::~AnpanAIStateNonActive ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void AnpanAIStateNonActive::OnDamaged ()\fC [virtual]\fP"

.PP
\fBAnpanAIStateBase\fPを再実装しています。
.SS "void AnpanAIStateNonActive::Update (int DeltaTime)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBAnpanAIStateBase\fPを再実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
