.TH "AnpanAIStateActive" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanAIStateActive
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanAIStateActive\&.h>\fP
.PP
\fBAnpanAIStateBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanAIStateActive\fP (\fBAnpan\fP *pInParent)"
.br
.ti -1c
.RI "virtual \fB~AnpanAIStateActive\fP ()"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP (int DeltaTime)"
.br
.in -1c
.SH "詳解"
.PP 
アンパンＡＩステート：アクティブ状態\&. 
.SH "構築子と解体子"
.PP 
.SS "AnpanAIStateActive::AnpanAIStateActive (\fBAnpan\fP * pInParent)"

.SS "virtual AnpanAIStateActive::~AnpanAIStateActive ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void AnpanAIStateActive::Update (int DeltaTime)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBAnpanAIStateBase\fPを再実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
