.TH "AnpanData" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanData\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanData\fP ()"
.br
.ti -1c
.RI "\fBAnpanData\fP (\fBu32\fP InUuid, \fBu32\fP InMasterId, float InX, float InY, float InZ, float InRotation, \fBs32\fP InHp, \fBs32\fP InMaxHp)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBUuid\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBMasterId\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.ti -1c
.RI "float \fBRotation\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBHp\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBMaxHp\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "AnpanData::AnpanData ()\fC [inline]\fP"

.SS "AnpanData::AnpanData (\fBu32\fP InUuid, \fBu32\fP InMasterId, float InX, float InY, float InZ, float InRotation, \fBs32\fP InHp, \fBs32\fP InMaxHp)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool AnpanData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP AnpanData::Hp"

.SS "\fBu32\fP AnpanData::MasterId"

.SS "\fBs32\fP AnpanData::MaxHp"

.SS "float AnpanData::Rotation"

.SS "\fBu32\fP AnpanData::Uuid"

.SS "float AnpanData::X"

.SS "float AnpanData::Y"

.SS "float AnpanData::Z"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
