.TH "AnpanAI" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanAI
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanAI\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAnpanAI\fP (\fBAnpan\fP *pInParent)"
.br
.ti -1c
.RI "\fB~AnpanAI\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP (int DeltaTime)"
.br
.ti -1c
.RI "void \fBChangeState\fP (\fBAnpanAIStateBase\fP *pNewState)"
.br
.ti -1c
.RI "void \fBCreateMovePacketData\fP (const \fBVector3D\fP &Position, int Time)"
.br
.ti -1c
.RI "shared_ptr< \fBAnpanMovePacketData\fP > \fBSweepMovePacketData\fP ()"
.br
.ti -1c
.RI "void \fBCreateRotatePacketData\fP (const \fBRotation\fP &Rot, int Time)"
.br
.ti -1c
.RI "shared_ptr< \fBAnpanRotatePacketData\fP > \fBSweepRotatePacketData\fP ()"
.br
.ti -1c
.RI "void \fBSetSendStopPacket\fP ()"
.br
.ti -1c
.RI "bool \fBSweepSendStopPacketFlag\fP ()"
.br
.ti -1c
.RI "void \fBOnDamaged\fP (weak_ptr< \fBCharacterBase\fP > pAttacker, int DamageValue)"
.br
.ti -1c
.RI "const \fBHate\fP & \fBGetHate\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
アンパンＡＩクラス 
.SH "構築子と解体子"
.PP 
.SS "AnpanAI::AnpanAI (\fBAnpan\fP * pInParent)"

.SS "AnpanAI::~AnpanAI ()"

.SH "関数詳解"
.PP 
.SS "void AnpanAI::ChangeState (\fBAnpanAIStateBase\fP * pNewState)"

.SS "void AnpanAI::CreateMovePacketData (const \fBVector3D\fP & Position, int Time)"

.SS "void AnpanAI::CreateRotatePacketData (const \fBRotation\fP & Rot, int Time)"

.SS "const \fBHate\fP& AnpanAI::GetHate () const\fC [inline]\fP"

.SS "void AnpanAI::OnDamaged (weak_ptr< \fBCharacterBase\fP > pAttacker, int DamageValue)"

.SS "void AnpanAI::Poll (int DeltaTime)"

.SS "void AnpanAI::SetSendStopPacket ()\fC [inline]\fP"

.SS "shared_ptr< \fBAnpanMovePacketData\fP > AnpanAI::SweepMovePacketData ()"

.SS "shared_ptr< \fBAnpanRotatePacketData\fP > AnpanAI::SweepRotatePacketData ()"

.SS "bool AnpanAI::SweepSendStopPacketFlag ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
