.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/Character/Anpan/AI/AnpanAIPacketData.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/Character/Anpan/AI/AnpanAIPacketData.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Math/Vector3D\&.h'\fP
.br
\fC#include 'Math/Rotation\&.h'\fP
.br
\fC#include 'Packet/PacketMoveAnpan\&.h'\fP
.br
\fC#include 'Packet/PacketRotateAnpan\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBAnpanMovePacketData\fP"
.br
.ti -1c
.RI "class \fBAnpanRotatePacketData\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
