.TH "AnpanPopDataItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanPopDataItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanPopDataMaster\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBs32\fP \fBAutoKey\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAnpanId\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP AnpanPopDataItem::AnpanId"

.SS "\fBs32\fP AnpanPopDataItem::AutoKey"

.SS "\fBu32\fP AnpanPopDataItem::Id"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
