.TH "AnpanPopAreaItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnpanPopAreaItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AnpanPopAreaMaster\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBs32\fP \fBAutoKey\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAreaId\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.ti -1c
.RI "float \fBRange\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBPopInterval\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBMaxCount\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBPopId\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP AnpanPopAreaItem::AreaId"

.SS "\fBs32\fP AnpanPopAreaItem::AutoKey"

.SS "\fBu32\fP AnpanPopAreaItem::MaxCount"

.SS "\fBu32\fP AnpanPopAreaItem::PopId"

.SS "\fBs32\fP AnpanPopAreaItem::PopInterval"

.SS "float AnpanPopAreaItem::Range"

.SS "float AnpanPopAreaItem::X"

.SS "float AnpanPopAreaItem::Y"

.SS "float AnpanPopAreaItem::Z"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
