.TH "AreaBase.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaBase.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/enable_shared_from_this\&.hpp>\fP
.br
\fC#include 'PlayerManager\&.h'\fP
.br
\fC#include 'AnpanManager\&.h'\fP
.br
\fC#include 'HeightMap\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBAreaBase\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
