.TH "AreaBase" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AreaBase\&.h>\fP
.PP
enable_shared_from_this< AreaBase >を継承しています。
.PP
\fBArea\fP, \fBInstanceArea\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBAreaBase\fP (const \fBAreaItem\fP *pItem)"
.br
.ti -1c
.RI "virtual \fB~AreaBase\fP ()"
.br
.ti -1c
.RI "virtual void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP (int DeltaTime)"
.br
.ti -1c
.RI "void \fBAddPlayerCharacter\fP (const \fBPlayerCharacterPtr\fP &pPlayer)"
.br
.ti -1c
.RI "void \fBRemovePlayerCharacter\fP (\fBu32\fP Uuid)"
.br
.ti -1c
.RI "void \fBOnRecvMove\fP (\fBu32\fP Uuid, float X, float Y, float Z, float \fBRotation\fP)"
.br
.ti -1c
.RI "void \fBOnRecvSkillUse\fP (\fBu32\fP Uuid, \fBu32\fP SkillId, \fBu8\fP TargetType, \fBu32\fP TargetUuid)"
.br
.ti -1c
.RI "void \fBOnRecvItemUse\fP (\fBu32\fP Uuid, \fBu32\fP ItemId, \fBu8\fP TargetType, \fBu32\fP TargetUuid)"
.br
.ti -1c
.RI "void \fBBroadcastPacket\fP (\fBPacketBase\fP *pPacket, \fBClient\fP *pIgnoreClient=NULL)"
.br
.ti -1c
.RI "void \fBBroadcastPacketWithRange\fP (\fBPacketBase\fP *pPacket, const \fBVector3D\fP &Center, float Range, \fBClient\fP *pIgnoreClient=NULL)"
.br
.ti -1c
.RI "float \fBGetHeight\fP (float X, float Y) const"
.br
.ti -1c
.RI "bool \fBCheckMovable\fP (const \fBVector3D\fP &Start, const \fBVector3D\fP &End, float ClimbableHeight, \fBVector3D\fP &OutHit) const"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetId\fP () const =0"
.br
.ti -1c
.RI "\fBu32\fP \fBGetMasterId\fP () const"
.br
.ti -1c
.RI "virtual bool \fBIsAbleDelete\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBIsInstance\fP () const"
.br
.ti -1c
.RI "void \fBCollectCircle\fP (const \fBVector3D\fP &Center, float Radius, \fBu8\fP TargetType, std::vector< \fBCharacterBase\fP *> &OutTargets)"
.br
.ti -1c
.RI "void \fBCollectBox\fP (const \fBVector3D\fP &Center, float Width, float Height, \fBu8\fP TargetType, std::vector< \fBCharacterBase\fP *> &OutTargets)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "\fBPlayerManager\fP \fBPlayerMgr\fP"
.br
.ti -1c
.RI "\fBAnpanManager\fP \fBAnpanMgr\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBMasterId\fP"
.br
.in -1c
.SH "詳解"
.PP 
エリア基底クラス 
.SH "構築子と解体子"
.PP 
.SS "AreaBase::AreaBase (const \fBAreaItem\fP * pItem)"

.SS "virtual AreaBase::~AreaBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void AreaBase::AddPlayerCharacter (const \fBPlayerCharacterPtr\fP & pPlayer)"

.SS "void AreaBase::BroadcastPacket (\fBPacketBase\fP * pPacket, \fBClient\fP * pIgnoreClient = \fCNULL\fP)"

.SS "void AreaBase::BroadcastPacketWithRange (\fBPacketBase\fP * pPacket, const \fBVector3D\fP & Center, float Range, \fBClient\fP * pIgnoreClient = \fCNULL\fP)"

.SS "bool AreaBase::CheckMovable (const \fBVector3D\fP & Start, const \fBVector3D\fP & End, float ClimbableHeight, \fBVector3D\fP & OutHit) const"

.SS "void AreaBase::CollectBox (const \fBVector3D\fP & Center, float Width, float Height, \fBu8\fP TargetType, std::vector< \fBCharacterBase\fP *> & OutTargets)"

.SS "void AreaBase::CollectCircle (const \fBVector3D\fP & Center, float Radius, \fBu8\fP TargetType, std::vector< \fBCharacterBase\fP *> & OutTargets)"

.SS "float AreaBase::GetHeight (float X, float Y) const"

.SS "virtual \fBu32\fP AreaBase::GetId () const\fC [pure virtual]\fP"

.PP
\fBInstanceArea\fP, \fBArea\fPで実装されています。
.SS "\fBu32\fP AreaBase::GetMasterId () const\fC [inline]\fP"

.SS "virtual void AreaBase::Initialize ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBInstanceArea\fPで再実装されています。
.SS "virtual bool AreaBase::IsAbleDelete () const\fC [pure virtual]\fP"

.PP
\fBInstanceArea\fP, \fBArea\fPで実装されています。
.SS "virtual bool AreaBase::IsInstance () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBInstanceArea\fPで再実装されています。
.SS "void AreaBase::OnRecvItemUse (\fBu32\fP Uuid, \fBu32\fP ItemId, \fBu8\fP TargetType, \fBu32\fP TargetUuid)"

.SS "void AreaBase::OnRecvMove (\fBu32\fP Uuid, float X, float Y, float Z, float Rotation)"

.SS "void AreaBase::OnRecvSkillUse (\fBu32\fP Uuid, \fBu32\fP SkillId, \fBu8\fP TargetType, \fBu32\fP TargetUuid)"

.SS "void AreaBase::Poll (int DeltaTime)"

.SS "void AreaBase::RemovePlayerCharacter (\fBu32\fP Uuid)"

.SS "virtual void AreaBase::Update ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBInstanceArea\fPで再実装されています。
.SH "メンバ詳解"
.PP 
.SS "\fBAnpanManager\fP AreaBase::AnpanMgr\fC [protected]\fP"

.SS "\fBu32\fP AreaBase::MasterId\fC [protected]\fP"

.SS "\fBPlayerManager\fP AreaBase::PlayerMgr\fC [protected]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
