.TH "AreaConfig" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaConfig
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AreaConfig\&.h>\fP
.SS "静的公開変数類"

.in +1c
.ti -1c
.RI "static const float \fBMinWidth\fP = \-10000\&.0f"
.br
.ti -1c
.RI "static const float \fBMaxWidth\fP = 10000\&.0f"
.br
.ti -1c
.RI "static const float \fBMinHeight\fP = \-10000\&.0f"
.br
.ti -1c
.RI "static const float \fBMaxHeight\fP = 10000\&.0f"
.br
.ti -1c
.RI "static const float \fBMinDepth\fP = \-10000\&.0f"
.br
.ti -1c
.RI "static const float \fBMaxDepth\fP = 10000\&.0f"
.br
.in -1c
.SH "詳解"
.PP 
エリアコンフィグ 
.SH "メンバ詳解"
.PP 
.SS "const float AreaConfig::MaxDepth = 10000\&.0f\fC [static]\fP"

.SS "const float AreaConfig::MaxHeight = 10000\&.0f\fC [static]\fP"

.SS "const float AreaConfig::MaxWidth = 10000\&.0f\fC [static]\fP"

.SS "const float AreaConfig::MinDepth = \-10000\&.0f\fC [static]\fP"

.SS "const float AreaConfig::MinHeight = \-10000\&.0f\fC [static]\fP"

.SS "const float AreaConfig::MinWidth = \-10000\&.0f\fC [static]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
