.TH "basic_repeating_timer.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_repeating_timer.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <boost/noncopyable\&.hpp>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <boost/date_time/posix_time/posix_time\&.hpp>\fP
.br
\fC#include <boost/thread/recursive_mutex\&.hpp>\fP
.br
\fC#include <boost/thread/condition\&.hpp>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <boost/enable_shared_from_this\&.hpp>\fP
.br
\fC#include <boost/weak_ptr\&.hpp>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBboost::asio::basic_repeating_timer< Time, TimeTraits, TimerService >\fP"
.br
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI " \fBboost\fP"
.br
.ti -1c
.RI " \fBboost::asio\fP"
.br
.in -1c
.SS "型定義"

.in +1c
.ti -1c
.RI "typedef basic_repeating_timer< boost::posix_time::ptime > \fBboost::asio::repeating_timer\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
