.TH "BitmapFileHeader" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitmapFileHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bitmap\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBRead\fP (std::ifstream &FileStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBFileType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBFileSize\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBReserved1\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBReserved2\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBOffset\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool BitmapFileHeader::Read (std::ifstream & FileStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP BitmapFileHeader::FileSize"

.SS "\fBu16\fP BitmapFileHeader::FileType"

.SS "\fBu32\fP BitmapFileHeader::Offset"

.SS "\fBu16\fP BitmapFileHeader::Reserved1"

.SS "\fBu16\fP BitmapFileHeader::Reserved2"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
