.TH "BitmapInfoData" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitmapInfoData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bitmap\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBRead\fP (std::ifstream &FileStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBHeight\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBPlanes\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBBitCount\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCompression\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBImageSize\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBXPixelPerMeter\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBYPixelPerMeter\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBUsedColors\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBImportantColors\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool BitmapInfoData::Read (std::ifstream & FileStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu16\fP BitmapInfoData::BitCount"

.SS "\fBu32\fP BitmapInfoData::Compression"

.SS "\fBs32\fP BitmapInfoData::Height"

.SS "\fBu32\fP BitmapInfoData::ImageSize"

.SS "\fBu32\fP BitmapInfoData::ImportantColors"

.SS "\fBu16\fP BitmapInfoData::Planes"

.SS "\fBu32\fP BitmapInfoData::Size"

.SS "\fBu32\fP BitmapInfoData::UsedColors"

.SS "\fBs32\fP BitmapInfoData::Width"

.SS "\fBs32\fP BitmapInfoData::XPixelPerMeter"

.SS "\fBs32\fP BitmapInfoData::YPixelPerMeter"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
