.TH "boost::asio" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::asio
.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBbasic_repeating_timer\fP"
.br
.in -1c
.SS "型定義"

.in +1c
.ti -1c
.RI "typedef \fBbasic_repeating_timer\fP< boost::posix_time::ptime > \fBrepeating_timer\fP"
.br
.in -1c
.SH "型定義詳解"
.PP 
.SS "typedef \fBbasic_repeating_timer\fP<boost::posix_time::ptime> \fBboost::asio::repeating_timer\fP"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
