.TH "boost::asio::basic_repeating_timer< Time, TimeTraits, TimerService >" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::asio::basic_repeating_timer< Time, TimeTraits, TimerService >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_repeating_timer\&.h>\fP
.PP
basic_io_object< TimerService >を継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "typedef boost::asio::basic_deadline_timer< Time > \fBtimer_type\fP"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBbasic_repeating_timer\fP (boost::asio::io_service &io_service)"
.br
.ti -1c
.RI "\fB~basic_repeating_timer\fP ()"
.br
.ti -1c
.RI "template<typename WaitHandler > void \fBstart\fP (typename timer_type::duration_type const &repeat_interval, WaitHandler handler)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBcancel\fP ()"
.br
.ti -1c
.RI "void \fBchange_interval\fP (typename timer_type::duration_type const &repeat_interval)"
.br
.in -1c
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> typedef boost::asio::basic_deadline_timer<Time> \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::\fBtimer_type\fP"

.SH "構築子と解体子"
.PP 
.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::\fBbasic_repeating_timer\fP (boost::asio::io_service & io_service)\fC [inline]\fP, \fC [explicit]\fP"

.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::~\fBbasic_repeating_timer\fP ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> void \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::cancel ()\fC [inline]\fP"

.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> void \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::change_interval (typename timer_type::duration_type const & repeat_interval)\fC [inline]\fP"

.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> template<typename WaitHandler > void \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::start (typename timer_type::duration_type const & repeat_interval, WaitHandler handler)\fC [inline]\fP"

.SS "template<typename Time , typename TimeTraits  = boost::asio::time_traits<Time>, typename TimerService  = boost::asio::detail::deadline_timer_service<TimeTraits>> void \fBboost::asio::basic_repeating_timer\fP< Time, TimeTraits, TimerService >::stop ()\fC [inline]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
