.TH "CacheServerConnection.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheServerConnection.h
.SH SYNOPSIS
.br
.PP
\fC#include 'TCPConnection\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBCacheServerConnection\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
