.TH "CachePacketSaveSkillListResponse" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachePacketSaveSkillListResponse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CachePacketSaveSkillListResponse\&.h>\fP
.PP
\fBProcessPacketBase\fPを継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBResultCode\fP { \fBSuccess\fP, \fBError\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBCachePacketSaveSkillListResponse\fP ()"
.br
.ti -1c
.RI "\fBCachePacketSaveSkillListResponse\fP (\fBu32\fP InClientId, \fBu8\fP InResult, \fBu32\fP InSkillId1, \fBu32\fP InSkillId2, \fBu32\fP InSkillId3, \fBu32\fP InSkillId4)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBResult\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId1\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId2\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId3\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId4\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBCachePacketSaveSkillListResponse::ResultCode\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIError \fP\fP
.SH "構築子と解体子"
.PP 
.SS "CachePacketSaveSkillListResponse::CachePacketSaveSkillListResponse ()\fC [inline]\fP"

.SS "CachePacketSaveSkillListResponse::CachePacketSaveSkillListResponse (\fBu32\fP InClientId, \fBu8\fP InResult, \fBu32\fP InSkillId1, \fBu32\fP InSkillId2, \fBu32\fP InSkillId3, \fBu32\fP InSkillId4)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP CachePacketSaveSkillListResponse::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SS "bool CachePacketSaveSkillListResponse::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu8\fP CachePacketSaveSkillListResponse::Result"

.SS "\fBu32\fP CachePacketSaveSkillListResponse::SkillId1"

.SS "\fBu32\fP CachePacketSaveSkillListResponse::SkillId2"

.SS "\fBu32\fP CachePacketSaveSkillListResponse::SkillId3"

.SS "\fBu32\fP CachePacketSaveSkillListResponse::SkillId4"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
