.TH "CachePacketSkillTreeResponse" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachePacketSkillTreeResponse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CachePacketSkillTreeResponse\&.h>\fP
.PP
\fBProcessPacketBase\fPを継承しています。
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBResultCode\fP { \fBSuccess\fP, \fBError\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBCachePacketSkillTreeResponse\fP ()"
.br
.ti -1c
.RI "\fBCachePacketSkillTreeResponse\fP (\fBu32\fP InClientId, \fBu8\fP InResult, \fBFlexArray\fP< \fBu32\fP > InOpenedList)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBResult\fP"
.br
.ti -1c
.RI "\fBFlexArray\fP< \fBu32\fP > \fBOpenedList\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBCachePacketSkillTreeResponse::ResultCode\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIError \fP\fP
.SH "構築子と解体子"
.PP 
.SS "CachePacketSkillTreeResponse::CachePacketSkillTreeResponse ()\fC [inline]\fP"

.SS "CachePacketSkillTreeResponse::CachePacketSkillTreeResponse (\fBu32\fP InClientId, \fBu8\fP InResult, \fBFlexArray\fP< \fBu32\fP > InOpenedList)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP CachePacketSkillTreeResponse::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SS "bool CachePacketSkillTreeResponse::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBFlexArray\fP<\fBu32\fP> CachePacketSkillTreeResponse::OpenedList"

.SS "\fBu8\fP CachePacketSkillTreeResponse::Result"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
