.TH "CacheServerConnection.cpp" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheServerConnection.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'CacheServerConnection\&.h'\fP
.br
\fC#include 'ServerHost\&.h'\fP
.br
\fC#include 'Client\&.h'\fP
.br
\fC#include 'ClientManager\&.h'\fP
.br
\fC#include 'MemoryStream/MemorySizeCaliculateStream\&.h'\fP
.br
\fC#include 'MemoryStream/MemoryStreamWriter\&.h'\fP
.br
\fC#include 'MemoryStream/MemoryStreamReader\&.h'\fP
.br
\fC#include 'Packet/PacketHeader\&.h'\fP
.br
\fC#include 'Packet/ProcessPacketBase\&.h'\fP
.br

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
