.TH "CachePacketItemListRequest" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachePacketItemListRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CachePacketItemListRequest\&.h>\fP
.PP
\fBProcessPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBCachePacketItemListRequest\fP ()"
.br
.ti -1c
.RI "\fBCachePacketItemListRequest\fP (\fBu32\fP InClientId, \fBu32\fP InCharacterId)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBCharacterId\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "CachePacketItemListRequest::CachePacketItemListRequest ()\fC [inline]\fP"

.SS "CachePacketItemListRequest::CachePacketItemListRequest (\fBu32\fP InClientId, \fBu32\fP InCharacterId)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP CachePacketItemListRequest::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SS "bool CachePacketItemListRequest::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP CachePacketItemListRequest::CharacterId"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
