.TH "CachePacketCharacterDataRequest" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachePacketCharacterDataRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CachePacketCharacterDataRequest\&.h>\fP
.PP
\fBProcessPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBCachePacketCharacterDataRequest\fP ()"
.br
.ti -1c
.RI "\fBCachePacketCharacterDataRequest\fP (\fBu32\fP InClientId, \fBu32\fP InCustomerId)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBCustomerId\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "CachePacketCharacterDataRequest::CachePacketCharacterDataRequest ()\fC [inline]\fP"

.SS "CachePacketCharacterDataRequest::CachePacketCharacterDataRequest (\fBu32\fP InClientId, \fBu32\fP InCustomerId)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP CachePacketCharacterDataRequest::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SS "bool CachePacketCharacterDataRequest::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP CachePacketCharacterDataRequest::CustomerId"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
