.TH "CachePacketCharacterDataSave" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachePacketCharacterDataSave
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CachePacketCharacterDataSave\&.h>\fP
.PP
\fBProcessPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBCachePacketCharacterDataSave\fP ()"
.br
.ti -1c
.RI "\fBCachePacketCharacterDataSave\fP (\fBu32\fP InClientId, \fBu32\fP InCharacterId, \fBu32\fP InLevel, \fBs32\fP InMaxHp, \fBs32\fP InAtk, \fBs32\fP InDef, \fBs32\fP InExp, \fBu32\fP InLastAreaId, float InLastX, float InLastY, float InLastZ)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBCharacterId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBLevel\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBMaxHp\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBAtk\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBDef\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBExp\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBLastAreaId\fP"
.br
.ti -1c
.RI "float \fBLastX\fP"
.br
.ti -1c
.RI "float \fBLastY\fP"
.br
.ti -1c
.RI "float \fBLastZ\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "CachePacketCharacterDataSave::CachePacketCharacterDataSave ()\fC [inline]\fP"

.SS "CachePacketCharacterDataSave::CachePacketCharacterDataSave (\fBu32\fP InClientId, \fBu32\fP InCharacterId, \fBu32\fP InLevel, \fBs32\fP InMaxHp, \fBs32\fP InAtk, \fBs32\fP InDef, \fBs32\fP InExp, \fBu32\fP InLastAreaId, float InLastX, float InLastY, float InLastZ)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP CachePacketCharacterDataSave::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SS "bool CachePacketCharacterDataSave::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBProcessPacketBase\fPを再実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP CachePacketCharacterDataSave::Atk"

.SS "\fBu32\fP CachePacketCharacterDataSave::CharacterId"

.SS "\fBs32\fP CachePacketCharacterDataSave::Def"

.SS "\fBs32\fP CachePacketCharacterDataSave::Exp"

.SS "\fBu32\fP CachePacketCharacterDataSave::LastAreaId"

.SS "float CachePacketCharacterDataSave::LastX"

.SS "float CachePacketCharacterDataSave::LastY"

.SS "float CachePacketCharacterDataSave::LastZ"

.SS "\fBu32\fP CachePacketCharacterDataSave::Level"

.SS "\fBs32\fP CachePacketCharacterDataSave::MaxHp"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
