.TH "CharacterParameter" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterParameter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CharacterParameter\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBLevel\fP"
.br
.ti -1c
.RI "int \fBHp\fP"
.br
.ti -1c
.RI "int \fBMaxHp\fP"
.br
.ti -1c
.RI "int \fBAtk\fP"
.br
.ti -1c
.RI "int \fBDef\fP"
.br
.in -1c
.SH "詳解"
.PP 
キャラクタパラメータ 
.SH "メンバ詳解"
.PP 
.SS "int CharacterParameter::Atk"

.SS "int CharacterParameter::Def"

.SS "int CharacterParameter::Hp"

.SS "\fBu32\fP CharacterParameter::Level"

.SS "int CharacterParameter::MaxHp"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
