.TH "CharacterType" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CharacterType\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBPlayer\fP, \fBEnemy\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBCharacterType\fP ()"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBCharacterType::Type\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIPlayer \fP\fP
.TP
\fB\fIEnemy \fP\fP
.SH "構築子と解体子"
.PP 
.SS "CharacterType::CharacterType ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool CharacterType::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
