.TH "CharacterBase.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterBase.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/enable_shared_from_this\&.hpp>\fP
.br
\fC#include 'CharacterParameter\&.h'\fP
.br
\fC#include 'Math/Vector3D\&.h'\fP
.br
\fC#include 'Math/Rotation\&.h'\fP
.br
\fC#include 'Area/AreaBase\&.h'\fP
.br
\fC#include 'Skill/SkillControl\&.h'\fP
.br
\fC#include 'Skill/SkillRecastManager\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBCharacterBase\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
