.TH "ClientStateTitle" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientStateTitle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientStateTitle\&.h>\fP
.PP
\fBClientStateBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBClientStateTitle\fP (\fBClient\fP *pInParent)"
.br
.ti -1c
.RI "virtual \fB~ClientStateTitle\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
タイトル画面State 
.SH "構築子と解体子"
.PP 
.SS "ClientStateTitle::ClientStateTitle (\fBClient\fP * pInParent)"

.SS "virtual ClientStateTitle::~ClientStateTitle ()\fC [inline]\fP, \fC [virtual]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
