.TH "ClientStateBase.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientStateBase.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <boost/function\&.hpp>\fP
.br
\fC#include 'Packet/PacketID\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBClientStateBase\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
