.TH "ClientStateActive.cpp" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientStateActive.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'ClientStateActive\&.h'\fP
.br
\fC#include 'MemoryStream/MemoryStreamInterface\&.h'\fP
.br
\fC#include 'Client\&.h'\fP
.br
\fC#include 'ClientManager\&.h'\fP
.br
\fC#include 'Config\&.h'\fP
.br
\fC#include 'Character/Player/PlayerCharacter\&.h'\fP
.br
\fC#include 'Area/AreaManager\&.h'\fP
.br
\fC#include 'Master/MasterData\&.h'\fP
.br
\fC#include 'WordCheckServer/WordCheckServerConnection\&.h'\fP
.br
\fC#include 'Party/PartyManager\&.h'\fP
.br
\fC#include 'ClientStateAreaChange\&.h'\fP
.br
\fC#include 'Area/InstanceAreaTicket\&.h'\fP
.br
\fC#include 'Area/InstanceAreaTicketManager\&.h'\fP
.br
\fC#include 'Time/TimeManager\&.h'\fP
.br
\fC#include 'CacheServer/CacheServerConnection\&.h'\fP
.br
\fC#include 'Packet/PacketPing\&.h'\fP
.br
\fC#include 'Packet/PacketMovePlayer\&.h'\fP
.br
\fC#include 'Packet/PacketSendChat\&.h'\fP
.br
\fC#include 'Packet/WordCheckPacketChatRequest\&.h'\fP
.br
\fC#include 'Packet/WordCheckPacketChatResult\&.h'\fP
.br
\fC#include 'Packet/PacketReceiveChat\&.h'\fP
.br
\fC#include 'Packet/PacketAreaMove\&.h'\fP
.br
\fC#include 'Packet/PacketAreaMoveRequest\&.h'\fP
.br
\fC#include 'Packet/PacketAreaMoveResponse\&.h'\fP
.br
\fC#include 'Packet/PacketRespawnRequest\&.h'\fP
.br
\fC#include 'Packet/PacketSkillUse\&.h'\fP
.br
\fC#include 'Packet/PacketPlayerRespawn\&.h'\fP
.br
\fC#include 'Packet/PacketPartyCreateRequest\&.h'\fP
.br
\fC#include 'Packet/PacketPartyCreateResult\&.h'\fP
.br
\fC#include 'Packet/PacketPartyDissolutionRequest\&.h'\fP
.br
\fC#include 'Packet/PacketPartyDissolutionResult\&.h'\fP
.br
\fC#include 'Packet/PacketPartyExitRequest\&.h'\fP
.br
\fC#include 'Packet/PacketPartyExitResult\&.h'\fP
.br
\fC#include 'Packet/PacketPartyExit\&.h'\fP
.br
\fC#include 'Packet/PacketPartyKickRequest\&.h'\fP
.br
\fC#include 'Packet/PacketPartyKickResult\&.h'\fP
.br
\fC#include 'Packet/PacketPartyKick\&.h'\fP
.br
\fC#include 'Packet/PacketPartyInviteRequest\&.h'\fP
.br
\fC#include 'Packet/PacketReceiveNotice\&.h'\fP
.br
\fC#include 'Packet/PacketPartyInviteResult\&.h'\fP
.br
\fC#include 'Packet/PacketPartyInviteResponse\&.h'\fP
.br
\fC#include 'Packet/PacketInstanceAreaTicketProcess\&.h'\fP
.br
\fC#include 'Packet/PacketTime\&.h'\fP
.br
\fC#include 'Packet/PacketNPCTalk\&.h'\fP
.br
\fC#include 'Packet/PacketNPCTalkSelection\&.h'\fP
.br
\fC#include 'Packet/PacketSaveSkillListRequest\&.h'\fP
.br
\fC#include 'Packet/PacketSaveSkillListResponse\&.h'\fP
.br
\fC#include 'Packet/CachePacketSaveSkillListRequest\&.h'\fP
.br
\fC#include 'Packet/CachePacketSaveSkillListResponse\&.h'\fP
.br
\fC#include 'Packet/PacketSkillTreeOpenRequest\&.h'\fP
.br
\fC#include 'Packet/PacketSkillTreeOpenResult\&.h'\fP
.br
\fC#include 'Packet/CachePacketOpenSkillTree\&.h'\fP
.br
\fC#include 'Packet/PacketItemUse\&.h'\fP
.br
\fC#include 'Packet/PacketItemSubtractRequest\&.h'\fP
.br
\fC#include 'Packet/PacketSaveItemShortcutRequest\&.h'\fP
.br
\fC#include 'Packet/CachePacketSaveItemShortcutRequest\&.h'\fP
.br
\fC#include 'Packet/CachePacketSaveItemShortcutResponse\&.h'\fP
.br
\fC#include 'Packet/PacketSaveItemShortcutResult\&.h'\fP
.br
\fC#include 'Packet/PacketQuestRetireRequest\&.h'\fP
.br
\fC#include 'Packet/PacketQuestRetireResponse\&.h'\fP
.br
\fC#include 'Packet/PacketSaveActiveQuest\&.h'\fP
.br
\fC#include 'Packet/CachePacketSaveActiveQuestRequest\&.h'\fP
.br

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
