.TH "ClientManager.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/unordered_map\&.hpp>\fP
.br
\fC#include 'Client\&.h'\fP
.br
\fC#include 'WeakPtrDefine\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBClientManager\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
