.TH "ClientManager" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientManager\&.h>\fP
.PP
noncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fB~ClientManager\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP ()"
.br
.ti -1c
.RI "void \fBCreateClient\fP (const shared_ptr< tcp::socket > &pSocket)"
.br
.ti -1c
.RI "\fBClientPtr\fP \fBGet\fP (\fBu32\fP Uuid)"
.br
.ti -1c
.RI "\fBClientPtr\fP \fBGetFromCustomerId\fP (\fBu32\fP CustomerId)"
.br
.ti -1c
.RI "void \fBBroadcastPacket\fP (\fBPacketBase\fP *pPacket)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBClientManager\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
クライアント管理\&. 
.SH "構築子と解体子"
.PP 
.SS "ClientManager::~ClientManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void ClientManager::BroadcastPacket (\fBPacketBase\fP * pPacket)"

.SS "void ClientManager::CreateClient (const shared_ptr< tcp::socket > & pSocket)"

.SS "\fBClientPtr\fP ClientManager::Get (\fBu32\fP Uuid)"

.SS "\fBClientPtr\fP ClientManager::GetFromCustomerId (\fBu32\fP CustomerId)"

.SS "static \fBClientManager\fP& ClientManager::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "void ClientManager::Poll ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
