.TH "ClientStateActive" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientStateActive
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientStateActive\&.h>\fP
.PP
\fBClientStateBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBClientStateActive\fP (\fBClient\fP *pInParent)"
.br
.ti -1c
.RI "virtual \fB~ClientStateActive\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginState\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
ゲーム中State 
.SH "構築子と解体子"
.PP 
.SS "ClientStateActive::ClientStateActive (\fBClient\fP * pInParent)"

.SS "virtual ClientStateActive::~ClientStateActive ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ClientStateActive::BeginState ()\fC [virtual]\fP"

.PP
\fBClientStateBase\fPを再実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
