.TH "ClientStateAreaChange" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientStateAreaChange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientStateAreaChange\&.h>\fP
.PP
\fBClientStateBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBClientStateAreaChange\fP (\fBClient\fP *pInParent, \fBu32\fP InAreaId, const \fBVector3D\fP &InPosition)"
.br
.ti -1c
.RI "virtual \fB~ClientStateAreaChange\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
エリア切り替え待ちステート 
.SH "構築子と解体子"
.PP 
.SS "ClientStateAreaChange::ClientStateAreaChange (\fBClient\fP * pInParent, \fBu32\fP InAreaId, const \fBVector3D\fP & InPosition)"

.SS "virtual ClientStateAreaChange::~ClientStateAreaChange ()\fC [inline]\fP, \fC [virtual]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
