.TH "Client.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client.h \- クライアントクラス  

.SH SYNOPSIS
.br
.PP
\fC#include 'TCPConnection\&.h'\fP
.br
\fC#include 'Packet/PacketID\&.h'\fP
.br
\fC#include 'Script/ScriptExecuter\&.h'\fP
.br
\fC#include 'Script/ScriptFlagManager\&.h'\fP
.br
\fC#include 'Quest/QuestManager\&.h'\fP
.br
\fC#include 'WeakPtrDefine\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBClient\fP"
.br
.RI "クライアントクラス "
.in -1c
.SH "詳解"
.PP 
クライアントクラス 


.PP
\fB著者:\fP
.RS 4
YanaP 
.RE
.PP

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
