.TH "Color24" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color24
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bitmap\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBColor24\fP ()"
.br
.ti -1c
.RI "\fBColor24\fP (\fBu8\fP InR, \fBu8\fP InG, \fBu8\fP InB)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBR\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBG\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBB\fP"
.br
.in -1c
.SS "静的公開変数類"

.in +1c
.ti -1c
.RI "static const \fBColor24\fP \fBBlack\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "Color24::Color24 ()\fC [inline]\fP"

.SS "Color24::Color24 (\fBu8\fP InR, \fBu8\fP InG, \fBu8\fP InB)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu8\fP Color24::B"

.SS "const \fBColor24\fP Color24::Black\fC [static]\fP"

.SS "\fBu8\fP Color24::G"

.SS "\fBu8\fP Color24::R"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
