.TH "Config" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "静的公開変数類"

.in +1c
.ti -1c
.RI "static const \fBu32\fP \fBCharacterNameMaxLength\fP = 16"
.br
.ti -1c
.RI "static const float \fBSayRange\fP = 3000\&.0f"
.br
.in -1c
.SH "詳解"
.PP 
定数定義\&. 
.SH "メンバ詳解"
.PP 
.SS "const \fBu32\fP Config::CharacterNameMaxLength = 16\fC [static]\fP"

.SS "const float Config::SayRange = 3000\&.0f\fC [static]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
