.TH "DamageCalcUnit" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DamageCalcUnit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DamageCalcUnit\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBDamageCalcUnit\fP (const \fBCharacterParameter\fP &InAttackerParam, const \fBCharacterParameter\fP &InDefencerParam)"
.br
.ti -1c
.RI "\fB~DamageCalcUnit\fP ()"
.br
.ti -1c
.RI "int \fBCalc\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
ダメージ計算クラス\&. 
.SH "構築子と解体子"
.PP 
.SS "DamageCalcUnit::DamageCalcUnit (const \fBCharacterParameter\fP & InAttackerParam, const \fBCharacterParameter\fP & InDefencerParam)"

.SS "DamageCalcUnit::~DamageCalcUnit ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "int DamageCalcUnit::Calc () const"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
