.TH "EndianConverter" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EndianConverter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EndianConverter\&.h>\fP
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static bool \fBIsLittleEndian\fP ()"
.br
.ti -1c
.RI "static \fBs16\fP \fBConvert\fP (\fBs16\fP Value, bool bForce=false)"
.br
.ti -1c
.RI "static \fBu16\fP \fBConvert\fP (\fBu16\fP Value, bool bForce=false)"
.br
.ti -1c
.RI "static \fBs32\fP \fBConvert\fP (\fBs32\fP Value, bool bForce=false)"
.br
.ti -1c
.RI "static \fBu32\fP \fBConvert\fP (\fBu32\fP Value, bool bForce=false)"
.br
.ti -1c
.RI "static float \fBConvert\fP (float Value, bool bForce=false)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "static \fBs16\fP EndianConverter::Convert (\fBs16\fP Value, bool bForce = \fCfalse\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBu16\fP EndianConverter::Convert (\fBu16\fP Value, bool bForce = \fCfalse\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBs32\fP EndianConverter::Convert (\fBs32\fP Value, bool bForce = \fCfalse\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBu32\fP EndianConverter::Convert (\fBu32\fP Value, bool bForce = \fCfalse\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static float EndianConverter::Convert (float Value, bool bForce = \fCfalse\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool EndianConverter::IsLittleEndian ()\fC [inline]\fP, \fC [static]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
