.TH "HateUnit" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HateUnit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hate\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "weak_ptr< \fBCharacterBase\fP > \fBpCharacter\fP"
.br
.ti -1c
.RI "int \fBHateValue\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "int HateUnit::HateValue"

.SS "weak_ptr<\fBCharacterBase\fP> HateUnit::pCharacter"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
