.TH "Hate.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hate.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBHateUnit\fP"
.br
.ti -1c
.RI "class \fBHate\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "bool \fBoperator>\fP (const \fBHateUnit\fP &Left, const \fBHateUnit\fP &Right)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBHateUnit\fP &Left, const \fBHateUnit\fP &Right)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool operator< (const \fBHateUnit\fP & Left, const \fBHateUnit\fP & Right)"

.SS "bool operator> (const \fBHateUnit\fP & Left, const \fBHateUnit\fP & Right)"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
