.TH "InstanceAreaTicketManager.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceAreaTicketManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/unordered_map\&.hpp>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBInstanceAreaTicketManager\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
