.TH "InstanceInfoItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceInfoItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InstanceInfoMaster\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBBossId\fP"
.br
.ti -1c
.RI "float \fBBossX\fP"
.br
.ti -1c
.RI "float \fBBossY\fP"
.br
.ti -1c
.RI "float \fBBossZ\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBExitWarpPointId\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP InstanceInfoItem::BossId"

.SS "float InstanceInfoItem::BossX"

.SS "float InstanceInfoItem::BossY"

.SS "float InstanceInfoItem::BossZ"

.SS "\fBu32\fP InstanceInfoItem::ExitWarpPointId"

.SS "\fBu32\fP InstanceInfoItem::Id"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
