.TH "InstanceAreaTicketInfo" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceAreaTicketInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InstanceAreaTicket\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBClientPtr\fP \fBpClient\fP"
.br
.ti -1c
.RI "\fBETicketState\fP \fBState\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBClientPtr\fP InstanceAreaTicketInfo::pClient"

.SS "\fBETicketState\fP InstanceAreaTicketInfo::State"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
