.TH "InstanceInfoMaster" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceInfoMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InstanceInfoMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBLoad\fP (const \fBMySqlConnection\fP &Connection)"
.br
.ti -1c
.RI "const \fBInstanceInfoItem\fP * \fBGetItem\fP (\fBu32\fP Key) const"
.br
.ti -1c
.RI "std::vector< \fBInstanceInfoItem\fP > \fBGetAll\fP () const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "std::vector< \fBInstanceInfoItem\fP > InstanceInfoMaster::GetAll () const"

.SS "const \fBInstanceInfoItem\fP * InstanceInfoMaster::GetItem (\fBu32\fP Key) const"

.SS "bool InstanceInfoMaster::Load (const \fBMySqlConnection\fP & Connection)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
