.TH "InstanceAreaTicket.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceAreaTicket.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/unordered_map\&.hpp>\fP
.br
\fC#include 'WeakPtrDefine\&.h'\fP
.br
\fC#include 'Math/Vector3D\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBInstanceAreaTicketInfo\fP"
.br
.ti -1c
.RI "class \fBInstanceAreaTicket\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBETicketState\fP { \fBTicketStateWait\fP, \fBTicketStateEnter\fP, \fBTicketStateDiscard\fP }"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBETicketState\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fITicketStateWait \fP\fP
.TP
\fB\fITicketStateEnter \fP\fP
.TP
\fB\fITicketStateDiscard \fP\fP
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
