.TH "ItemList" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemList\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBItemList\fP ()"
.br
.ti -1c
.RI "\fB~ItemList\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBu32\fP ItemId, \fBu32\fP Count)"
.br
.ti -1c
.RI "void \fBSubtract\fP (\fBu32\fP ItemId, \fBu32\fP Count)"
.br
.ti -1c
.RI "\fBu32\fP \fBGetCount\fP (\fBu32\fP ItemId) const"
.br
.in -1c
.SH "詳解"
.PP 
アイテムリストクラス 
.SH "構築子と解体子"
.PP 
.SS "ItemList::ItemList ()"

.SS "ItemList::~ItemList ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void ItemList::Add (\fBu32\fP ItemId, \fBu32\fP Count)"

.SS "\fBu32\fP ItemList::GetCount (\fBu32\fP ItemId) const"

.SS "void ItemList::Subtract (\fBu32\fP ItemId, \fBu32\fP Count)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
