.TH "ItemDropMaster" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemDropMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemDropMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBLoad\fP (const \fBMySqlConnection\fP &Connection)"
.br
.ti -1c
.RI "const \fBItemDropItem\fP * \fBGetItem\fP (\fBu32\fP Key) const"
.br
.ti -1c
.RI "std::vector< \fBItemDropItem\fP > \fBGetAll\fP () const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "std::vector< \fBItemDropItem\fP > ItemDropMaster::GetAll () const"

.SS "const \fBItemDropItem\fP * ItemDropMaster::GetItem (\fBu32\fP Key) const"

.SS "bool ItemDropMaster::Load (const \fBMySqlConnection\fP & Connection)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
