.TH "ItemItem" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBCONSUME\fP = 0, \fBDELIVERY\fP = 1 }"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBBuyGold\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSellGold\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fICONSUME \fP\fP
.TP
\fB\fIDELIVERY \fP\fP
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP ItemItem::BuyGold"

.SS "\fBu32\fP ItemItem::ID"

.SS "std::string ItemItem::Name"

.SS "\fBu32\fP ItemItem::SellGold"

.SS "\fBu32\fP ItemItem::SkillId"

.SS "\fBu8\fP ItemItem::Type"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
