.TH "Main.cpp" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'ClientAcceptor\&.h'\fP
.br
\fC#include 'ClientManager\&.h'\fP
.br
\fC#include 'TickManager\&.h'\fP
.br
\fC#include 'Master/MasterData\&.h'\fP
.br
\fC#include 'Area/AreaManager\&.h'\fP
.br
\fC#include 'Party/PartyManager\&.h'\fP
.br
\fC#include 'Time/TimeManager\&.h'\fP
.br
\fC#include 'ServerHost\&.h'\fP
.br
\fC#include 'CacheServer/CacheServerConnection\&.h'\fP
.br
\fC#include 'WordCheckServer/WordCheckServerConnection\&.h'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "int main ()"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
