.TH "MasterData" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MasterData\&.h>\fP
.PP
noncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBRead\fP ()"
.br
.ti -1c
.RI "const \fBAreaMaster\fP & \fBGetAreaMaster\fP ()"
.br
.ti -1c
.RI "const \fBWarpDataMaster\fP & \fBGetWarpDataMaster\fP ()"
.br
.ti -1c
.RI "const \fBAnpanMaster\fP & \fBGetAnpanMaster\fP ()"
.br
.ti -1c
.RI "const \fBAnpanPopAreaMaster\fP & \fBGetAnpanPopAreaMaster\fP ()"
.br
.ti -1c
.RI "const \fBAnpanPopDataMaster\fP & \fBGetAnpanPopDataMaster\fP ()"
.br
.ti -1c
.RI "const \fBInstanceInfoMaster\fP & \fBGetInstanceInfoMaster\fP ()"
.br
.ti -1c
.RI "const \fBTimeInfoMaster\fP & \fBGetTimeInfoMaster\fP ()"
.br
.ti -1c
.RI "const \fBNPCMaster\fP & \fBGetNPCMaster\fP ()"
.br
.ti -1c
.RI "const \fBSkillMaster\fP & \fBGetSkillMaster\fP ()"
.br
.ti -1c
.RI "const \fBSkillTreeMaster\fP & \fBGetSkillTreeMaster\fP ()"
.br
.ti -1c
.RI "const \fBItemMaster\fP & \fBGetItemMaster\fP ()"
.br
.ti -1c
.RI "const \fBItemDropMaster\fP & \fBGetItemDropMaster\fP ()"
.br
.ti -1c
.RI "const \fBQuestMaster\fP & \fBGetQuestMaster\fP ()"
.br
.ti -1c
.RI "const \fBQuestStageMaster\fP & \fBGetQuestStageMaster\fP ()"
.br
.ti -1c
.RI "const \fBQuestRewardMaster\fP & \fBGetQuestRewardMaster\fP ()"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBMasterData\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
マスタデータクラス 
.SH "関数詳解"
.PP 
.SS "const \fBAnpanMaster\fP& MasterData::GetAnpanMaster ()\fC [inline]\fP"

.SS "const \fBAnpanPopAreaMaster\fP& MasterData::GetAnpanPopAreaMaster ()\fC [inline]\fP"

.SS "const \fBAnpanPopDataMaster\fP& MasterData::GetAnpanPopDataMaster ()\fC [inline]\fP"

.SS "const \fBAreaMaster\fP& MasterData::GetAreaMaster ()\fC [inline]\fP"

.SS "static \fBMasterData\fP& MasterData::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "const \fBInstanceInfoMaster\fP& MasterData::GetInstanceInfoMaster ()\fC [inline]\fP"

.SS "const \fBItemDropMaster\fP& MasterData::GetItemDropMaster ()\fC [inline]\fP"

.SS "const \fBItemMaster\fP& MasterData::GetItemMaster ()\fC [inline]\fP"

.SS "const \fBNPCMaster\fP& MasterData::GetNPCMaster ()\fC [inline]\fP"

.SS "const \fBQuestMaster\fP& MasterData::GetQuestMaster ()\fC [inline]\fP"

.SS "const \fBQuestRewardMaster\fP& MasterData::GetQuestRewardMaster ()\fC [inline]\fP"

.SS "const \fBQuestStageMaster\fP& MasterData::GetQuestStageMaster ()\fC [inline]\fP"

.SS "const \fBSkillMaster\fP& MasterData::GetSkillMaster ()\fC [inline]\fP"

.SS "const \fBSkillTreeMaster\fP& MasterData::GetSkillTreeMaster ()\fC [inline]\fP"

.SS "const \fBTimeInfoMaster\fP& MasterData::GetTimeInfoMaster ()\fC [inline]\fP"

.SS "const \fBWarpDataMaster\fP& MasterData::GetWarpDataMaster ()\fC [inline]\fP"

.SS "bool MasterData::Read ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
