.TH "MathUtil.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MathUtil.h
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include 'Vector3D\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBMathUtil\fP"
.br
.in -1c
.SS "マクロ定義"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.in -1c
.SH "マクロ定義詳解"
.PP 
.SS "#define _USE_MATH_DEFINES"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
