.TH "MemoryBuffer" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryBuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemoryBuffer\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMemoryBuffer\fP ()"
.br
.ti -1c
.RI "\fB~MemoryBuffer\fP ()"
.br
.ti -1c
.RI "\fBu8\fP * \fBGetTop\fP ()"
.br
.ti -1c
.RI "\fBs32\fP \fBGetSize\fP ()"
.br
.ti -1c
.RI "void \fBPush\fP (const \fBu8\fP *Data, \fBs32\fP Size)"
.br
.ti -1c
.RI "void \fBPop\fP (\fBs32\fP Size)"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "MemoryBuffer::MemoryBuffer ()\fC [inline]\fP"

.SS "MemoryBuffer::~MemoryBuffer ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "\fBs32\fP MemoryBuffer::GetSize ()\fC [inline]\fP"

.SS "\fBu8\fP* MemoryBuffer::GetTop ()\fC [inline]\fP"

.SS "void MemoryBuffer::Pop (\fBs32\fP Size)"

.SS "void MemoryBuffer::Push (const \fBu8\fP * Data, \fBs32\fP Size)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
