.TH "MemoryStreamWriter" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryStreamWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemoryStreamWriter\&.h>\fP
.PP
\fBMemoryStreamInterface\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMemoryStreamWriter\fP (const int InSize)"
.br
.ti -1c
.RI "virtual \fB~MemoryStreamWriter\fP ()"
.br
.ti -1c
.RI "const \fBu8\fP * \fBGetStream\fP () const"
.br
.ti -1c
.RI "const int \fBGetSize\fP () const"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBs32\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBu32\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBs16\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBu16\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBs8\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (\fBu8\fP *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (std::string *pValue)"
.br
.ti -1c
.RI "virtual bool \fBSerialize\fP (float *pValue)"
.br
.ti -1c
.RI "virtual bool \fBIsReadMode\fP () const"
.br
.ti -1c
.RI "virtual bool \fBIsError\fP () const"
.br
.ti -1c
.RI "virtual void \fBReset\fP ()"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "MemoryStreamWriter::MemoryStreamWriter (const int InSize)"

.SS "virtual MemoryStreamWriter::~MemoryStreamWriter ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "const int MemoryStreamWriter::GetSize () const\fC [inline]\fP"

.SS "const \fBu8\fP* MemoryStreamWriter::GetStream () const\fC [inline]\fP"

.SS "virtual bool MemoryStreamWriter::IsError () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "virtual bool MemoryStreamWriter::IsReadMode () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "void MemoryStreamWriter::Reset ()\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (\fBs32\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (\fBu32\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (\fBs16\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (\fBu16\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (\fBs8\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (\fBu8\fP * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (std::string * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。
.SS "bool MemoryStreamWriter::Serialize (float * pValue)\fC [virtual]\fP"

.PP
\fBMemoryStreamInterface\fPを実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
