.TH "MemoryStreamReader.cpp" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryStreamReader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'MemoryStreamReader\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'EndianConverter\&.h'\fP
.br

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
