.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/MemoryStream/MemoryStreamInterface.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/MemoryStream/MemoryStreamInterface.h
.SH SYNOPSIS
.br
.PP
\fC#include 'TypeDefs\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBMemoryStreamInterface\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
