.TH "MySqlQuery" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySqlQuery
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MySqlQuery\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMySqlQuery\fP (MYSQL *pInConnection, const char *pInQuery)"
.br
.ti -1c
.RI "\fB~MySqlQuery\fP ()"
.br
.ti -1c
.RI "void \fBBindInt\fP (int *pPtr)"
.br
.ti -1c
.RI "void \fBBindInt\fP (unsigned int *pPtr)"
.br
.ti -1c
.RI "void \fBBindShort\fP (short *pPtr)"
.br
.ti -1c
.RI "void \fBBindShort\fP (unsigned short *pPtr)"
.br
.ti -1c
.RI "void \fBBindChar\fP (char *pPtr)"
.br
.ti -1c
.RI "void \fBBindChar\fP (unsigned char *pPtr)"
.br
.ti -1c
.RI "void \fBBindFloat\fP (float *pPtr)"
.br
.ti -1c
.RI "void \fBBindString\fP (char *pPtr)"
.br
.ti -1c
.RI "void \fBBindWString\fP (wchar_t *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultInt\fP (int *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultInt\fP (unsigned int *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultShort\fP (short *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultShort\fP (unsigned short *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultChar\fP (char *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultChar\fP (unsigned char *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultFloat\fP (float *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultString\fP (char *pPtr)"
.br
.ti -1c
.RI "void \fBBindResultWString\fP (wchar_t *pPtr)"
.br
.ti -1c
.RI "bool \fBExecuteQuery\fP ()"
.br
.ti -1c
.RI "bool \fBFetch\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
MySQLクエリクラス 
.SH "構築子と解体子"
.PP 
.SS "MySqlQuery::MySqlQuery (MYSQL * pInConnection, const char * pInQuery)"

.SS "MySqlQuery::~MySqlQuery ()"

.SH "関数詳解"
.PP 
.SS "void MySqlQuery::BindChar (char * pPtr)"

.SS "void MySqlQuery::BindChar (unsigned char * pPtr)"

.SS "void MySqlQuery::BindFloat (float * pPtr)"

.SS "void MySqlQuery::BindInt (int * pPtr)"

.SS "void MySqlQuery::BindInt (unsigned int * pPtr)"

.SS "void MySqlQuery::BindResultChar (char * pPtr)"

.SS "void MySqlQuery::BindResultChar (unsigned char * pPtr)"

.SS "void MySqlQuery::BindResultFloat (float * pPtr)"

.SS "void MySqlQuery::BindResultInt (int * pPtr)"

.SS "void MySqlQuery::BindResultInt (unsigned int * pPtr)"

.SS "void MySqlQuery::BindResultShort (short * pPtr)"

.SS "void MySqlQuery::BindResultShort (unsigned short * pPtr)"

.SS "void MySqlQuery::BindResultString (char * pPtr)"

.SS "void MySqlQuery::BindResultWString (wchar_t * pPtr)"

.SS "void MySqlQuery::BindShort (short * pPtr)"

.SS "void MySqlQuery::BindShort (unsigned short * pPtr)"

.SS "void MySqlQuery::BindString (char * pPtr)"

.SS "void MySqlQuery::BindWString (wchar_t * pPtr)"

.SS "void MySqlQuery::Close ()"

.SS "bool MySqlQuery::ExecuteQuery ()"

.SS "bool MySqlQuery::Fetch ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
