.TH "MySqlBinds" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySqlBinds
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MySqlBinds\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMySqlBinds\fP ()"
.br
.ti -1c
.RI "\fB~MySqlBinds\fP ()"
.br
.ti -1c
.RI "void \fBAddInt\fP (int *pPtr)"
.br
.ti -1c
.RI "void \fBAddInt\fP (unsigned int *pPtr)"
.br
.ti -1c
.RI "void \fBAddShort\fP (short *pPtr)"
.br
.ti -1c
.RI "void \fBAddShort\fP (unsigned short *pPtr)"
.br
.ti -1c
.RI "void \fBAddChar\fP (char *pPtr)"
.br
.ti -1c
.RI "void \fBAddChar\fP (unsigned char *pPtr)"
.br
.ti -1c
.RI "void \fBAddFloat\fP (float *pPtr)"
.br
.ti -1c
.RI "void \fBAddString\fP (char *pPtr, bool bForResult)"
.br
.ti -1c
.RI "void \fBAddWString\fP (wchar_t *pPtr, bool bForResult)"
.br
.ti -1c
.RI "MYSQL_BIND * \fBGet\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
バインド 
.SH "構築子と解体子"
.PP 
.SS "MySqlBinds::MySqlBinds ()"

.SS "MySqlBinds::~MySqlBinds ()"

.SH "関数詳解"
.PP 
.SS "void MySqlBinds::AddChar (char * pPtr)"

.SS "void MySqlBinds::AddChar (unsigned char * pPtr)"

.SS "void MySqlBinds::AddFloat (float * pPtr)"

.SS "void MySqlBinds::AddInt (int * pPtr)"

.SS "void MySqlBinds::AddInt (unsigned int * pPtr)"

.SS "void MySqlBinds::AddShort (short * pPtr)"

.SS "void MySqlBinds::AddShort (unsigned short * pPtr)"

.SS "void MySqlBinds::AddString (char * pPtr, bool bForResult)"

.SS "void MySqlBinds::AddWString (wchar_t * pPtr, bool bForResult)"

.SS "MYSQL_BIND* MySqlBinds::Get ()\fC [inline]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
