.TH "MySqlConnection" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySqlConnection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MySqlConnection\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMySqlConnection\fP ()"
.br
.ti -1c
.RI "\fB~MySqlConnection\fP ()"
.br
.ti -1c
.RI "bool \fBConnect\fP (const char *pHost, const char *pUserName, const char *pPassword, const char *pDBName)"
.br
.ti -1c
.RI "bool \fBSimpleQuery\fP (const char *pQuery) const"
.br
.ti -1c
.RI "\fBMySqlQuery\fP \fBCreateQuery\fP (const char *pQuery) const"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
MySQL接続クラス 
.SH "構築子と解体子"
.PP 
.SS "MySqlConnection::MySqlConnection ()"

.SS "MySqlConnection::~MySqlConnection ()"

.SH "関数詳解"
.PP 
.SS "void MySqlConnection::Close ()"

.SS "bool MySqlConnection::Connect (const char * pHost, const char * pUserName, const char * pPassword, const char * pDBName)"

.SS "\fBMySqlQuery\fP MySqlConnection::CreateQuery (const char * pQuery) const"

.SS "bool MySqlConnection::SimpleQuery (const char * pQuery) const"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
