.TH "NPCItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NPCItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NPCMaster\&.h>\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAreaId\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.ti -1c
.RI "float \fBRotation\fP"
.br
.ti -1c
.RI "std::string \fBScriptName\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBAppearConditionId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBEraseConditionId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBResourceId\fP"
.br
.in -1c
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP NPCItem::AppearConditionId"

.SS "\fBu32\fP NPCItem::AreaId"

.SS "\fBu32\fP NPCItem::EraseConditionId"

.SS "\fBu32\fP NPCItem::ID"

.SS "std::string NPCItem::Name"

.SS "\fBu32\fP NPCItem::ResourceId"

.SS "float NPCItem::Rotation"

.SS "std::string NPCItem::ScriptName"

.SS "float NPCItem::X"

.SS "float NPCItem::Y"

.SS "float NPCItem::Z"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
