.TH "PacketMovePlayer" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketMovePlayer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketMovePlayer\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketMovePlayer\fP ()"
.br
.ti -1c
.RI "\fBPacketMovePlayer\fP (\fBu32\fP InUuid, float InX, float InY, float InZ, float InRotation)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBUuid\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.ti -1c
.RI "float \fBRotation\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketMovePlayer::PacketMovePlayer ()\fC [inline]\fP"

.SS "PacketMovePlayer::PacketMovePlayer (\fBu32\fP InUuid, float InX, float InY, float InZ, float InRotation)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketMovePlayer::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketMovePlayer::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "float PacketMovePlayer::Rotation"

.SS "\fBu32\fP PacketMovePlayer::Uuid"

.SS "float PacketMovePlayer::X"

.SS "float PacketMovePlayer::Y"

.SS "float PacketMovePlayer::Z"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
