.TH "PacketPlayerRespawn" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketPlayerRespawn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketPlayerRespawn\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketPlayerRespawn\fP ()"
.br
.ti -1c
.RI "\fBPacketPlayerRespawn\fP (\fBu32\fP InUuid, float InX, float InY, float InZ)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBUuid\fP"
.br
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketPlayerRespawn::PacketPlayerRespawn ()\fC [inline]\fP"

.SS "PacketPlayerRespawn::PacketPlayerRespawn (\fBu32\fP InUuid, float InX, float InY, float InZ)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketPlayerRespawn::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketPlayerRespawn::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketPlayerRespawn::Uuid"

.SS "float PacketPlayerRespawn::X"

.SS "float PacketPlayerRespawn::Y"

.SS "float PacketPlayerRespawn::Z"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
