.TH "PacketDamage" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketDamage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketDamage\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketDamage\fP ()"
.br
.ti -1c
.RI "\fBPacketDamage\fP (\fBu8\fP InTargetType, \fBu32\fP InTargetUuid, \fBs32\fP InDamageValue, \fBs32\fP InResultHp)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBTargetType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBTargetUuid\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBDamageValue\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBResultHp\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketDamage::PacketDamage ()\fC [inline]\fP"

.SS "PacketDamage::PacketDamage (\fBu8\fP InTargetType, \fBu32\fP InTargetUuid, \fBs32\fP InDamageValue, \fBs32\fP InResultHp)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketDamage::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketDamage::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP PacketDamage::DamageValue"

.SS "\fBs32\fP PacketDamage::ResultHp"

.SS "\fBu8\fP PacketDamage::TargetType"

.SS "\fBu32\fP PacketDamage::TargetUuid"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
