.TH "PacketPartyDissolutionRequest" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketPartyDissolutionRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketPartyDissolutionRequest\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketPartyDissolutionRequest\fP ()"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketPartyDissolutionRequest::PacketPartyDissolutionRequest ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketPartyDissolutionRequest::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketPartyDissolutionRequest::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
