.TH "PacketScriptFlag" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketScriptFlag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketScriptFlag\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketScriptFlag\fP ()"
.br
.ti -1c
.RI "\fBPacketScriptFlag\fP (\fBu32\fP InBitField1, \fBu32\fP InBitField2, \fBu32\fP InBitField3)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBBitField1\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBBitField2\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBBitField3\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketScriptFlag::PacketScriptFlag ()\fC [inline]\fP"

.SS "PacketScriptFlag::PacketScriptFlag (\fBu32\fP InBitField1, \fBu32\fP InBitField2, \fBu32\fP InBitField3)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketScriptFlag::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketScriptFlag::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketScriptFlag::BitField1"

.SS "\fBu32\fP PacketScriptFlag::BitField2"

.SS "\fBu32\fP PacketScriptFlag::BitField3"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
