.TH "PacketSkillList" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketSkillList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketSkillList\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketSkillList\fP ()"
.br
.ti -1c
.RI "\fBPacketSkillList\fP (\fBu32\fP InNormalAttack, \fBu32\fP InSkill1, \fBu32\fP InSkill2, \fBu32\fP InSkill3, \fBu32\fP InSkill4)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBNormalAttack\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkill1\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkill2\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkill3\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkill4\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketSkillList::PacketSkillList ()\fC [inline]\fP"

.SS "PacketSkillList::PacketSkillList (\fBu32\fP InNormalAttack, \fBu32\fP InSkill1, \fBu32\fP InSkill2, \fBu32\fP InSkill3, \fBu32\fP InSkill4)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketSkillList::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketSkillList::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketSkillList::NormalAttack"

.SS "\fBu32\fP PacketSkillList::Skill1"

.SS "\fBu32\fP PacketSkillList::Skill2"

.SS "\fBu32\fP PacketSkillList::Skill3"

.SS "\fBu32\fP PacketSkillList::Skill4"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
