.TH "PacketSkillTreeData" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketSkillTreeData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketSkillTreeData\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketSkillTreeData\fP ()"
.br
.ti -1c
.RI "\fBPacketSkillTreeData\fP (\fBFlexArray\fP< \fBSkillTreeNode\fP > InNodes)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBFlexArray\fP< \fBSkillTreeNode\fP > \fBNodes\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketSkillTreeData::PacketSkillTreeData ()\fC [inline]\fP"

.SS "PacketSkillTreeData::PacketSkillTreeData (\fBFlexArray\fP< \fBSkillTreeNode\fP > InNodes)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketSkillTreeData::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketSkillTreeData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBFlexArray\fP<\fBSkillTreeNode\fP> PacketSkillTreeData::Nodes"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
