.TH "PartyMemberData" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartyMemberData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartyMemberData\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPartyMemberData\fP ()"
.br
.ti -1c
.RI "\fBPartyMemberData\fP (\fBu32\fP InUuid, std::string InCharacterName)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBUuid\fP"
.br
.ti -1c
.RI "std::string \fBCharacterName\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PartyMemberData::PartyMemberData ()\fC [inline]\fP"

.SS "PartyMemberData::PartyMemberData (\fBu32\fP InUuid, std::string InCharacterName)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool PartyMemberData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "std::string PartyMemberData::CharacterName"

.SS "\fBu32\fP PartyMemberData::Uuid"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
