.TH "Party" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Party
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Party\&.h>\fP
.PP
enable_shared_from_this< Party >を継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBParty\fP (\fBu32\fP InUuid)"
.br
.ti -1c
.RI "virtual \fB~Party\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP ()"
.br
.ti -1c
.RI "bool \fBJoin\fP (\fBPlayerCharacterPtr\fP pPlayer)"
.br
.ti -1c
.RI "void \fBExit\fP (\fBu32\fP CharacterUuid)"
.br
.ti -1c
.RI "std::vector< \fBPlayerCharacterPtr\fP > \fBGetMemberList\fP () const"
.br
.ti -1c
.RI "bool \fBIsMaximumMember\fP () const"
.br
.ti -1c
.RI "bool \fBIsAbleDelete\fP () const"
.br
.ti -1c
.RI "\fBu32\fP \fBGetUuid\fP () const"
.br
.ti -1c
.RI "void \fBBroadcastPacket\fP (\fBPacketBase\fP *pPacket, \fBClient\fP *pIgnoreClient=NULL)"
.br
.in -1c
.SH "詳解"
.PP 
パーティクラス 
.SH "構築子と解体子"
.PP 
.SS "Party::Party (\fBu32\fP InUuid)"

.SS "virtual Party::~Party ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void Party::BroadcastPacket (\fBPacketBase\fP * pPacket, \fBClient\fP * pIgnoreClient = \fCNULL\fP)"

.SS "void Party::Exit (\fBu32\fP CharacterUuid)"

.SS "std::vector< \fBPlayerCharacterPtr\fP > Party::GetMemberList () const"

.SS "\fBu32\fP Party::GetUuid () const\fC [inline]\fP"

.SS "bool Party::IsAbleDelete () const"

.SS "bool Party::IsMaximumMember () const\fC [inline]\fP"

.SS "bool Party::Join (\fBPlayerCharacterPtr\fP pPlayer)"

.SS "void Party::Poll ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
