.TH "PartyManager" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartyManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartyManager\&.h>\fP
.PP
noncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fB~PartyManager\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP ()"
.br
.ti -1c
.RI "void \fBCreate\fP (\fBPlayerCharacterPtr\fP pCreatePlayer)"
.br
.ti -1c
.RI "bool \fBDissolution\fP (\fBu32\fP Uuid)"
.br
.ti -1c
.RI "\fBPartyPtr\fP \fBGet\fP (\fBu32\fP Uuid)"
.br
.ti -1c
.RI "bool \fBIsAlreadyJoined\fP (\fBu32\fP Uuid)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBPartyManager\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
パーティマネージャ 
.SH "構築子と解体子"
.PP 
.SS "PartyManager::~PartyManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void PartyManager::Create (\fBPlayerCharacterPtr\fP pCreatePlayer)"

.SS "bool PartyManager::Dissolution (\fBu32\fP Uuid)"

.SS "\fBPartyPtr\fP PartyManager::Get (\fBu32\fP Uuid)"

.SS "static \fBPartyManager\fP& PartyManager::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "bool PartyManager::IsAlreadyJoined (\fBu32\fP Uuid)"

.SS "void PartyManager::Poll ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
