.TH "PlayerManager.cpp" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'PlayerManager\&.h'\fP
.br
\fC#include 'Client\&.h'\fP
.br
\fC#include 'Character/Player/PlayerCharacter\&.h'\fP
.br
\fC#include 'Packet/PacketSpawnPlayer\&.h'\fP
.br
\fC#include 'Packet/PacketPlayerList\&.h'\fP
.br
\fC#include 'Packet/PacketMovePlayer\&.h'\fP
.br
\fC#include 'Packet/PacketExitPlayer\&.h'\fP
.br

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
