.TH "PlayerCharacter" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerCharacter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerCharacter\&.h>\fP
.PP
\fBCharacterBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPlayerCharacter\fP (\fBClient\fP *pInClient, \fBu32\fP InCharacterId, \fBu8\fP InJob, \fBu32\fP Level, int MaxHp, int Atk, int Def, int InExp, \fBu32\fP InGold)"
.br
.ti -1c
.RI "virtual \fB~PlayerCharacter\fP ()"
.br
.ti -1c
.RI "\fBClient\fP * \fBGetClient\fP () const"
.br
.ti -1c
.RI "void \fBAddExp\fP (int Value)"
.br
.ti -1c
.RI "int \fBGetExp\fP () const"
.br
.ti -1c
.RI "void \fBSetName\fP (const std::string &InName)"
.br
.ti -1c
.RI "\fBu32\fP \fBGetCharacterId\fP () const"
.br
.ti -1c
.RI "const std::string & \fBGetName\fP () const"
.br
.ti -1c
.RI "\fBu8\fP \fBGetJob\fP () const"
.br
.ti -1c
.RI "virtual \fBu8\fP \fBGetCharacterType\fP () const"
.br
.ti -1c
.RI "void \fBSetParty\fP (const \fBPartyPtr\fP &pInParty)"
.br
.ti -1c
.RI "\fBPartyPtr\fP \fBGetParty\fP () const"
.br
.ti -1c
.RI "void \fBOnMoved\fP ()"
.br
.ti -1c
.RI "void \fBOnAreaChange\fP ()"
.br
.ti -1c
.RI "\fBu32\fP \fBGetGold\fP () const"
.br
.ti -1c
.RI "void \fBAddGold\fP (\fBu32\fP Value)"
.br
.ti -1c
.RI "void \fBSubtractGold\fP (\fBu32\fP Value)"
.br
.ti -1c
.RI "void \fBInitializeSkillTree\fP (const \fBFlexArray\fP< \fBu32\fP > &OpenedNodes)"
.br
.ti -1c
.RI "const \fBSkillTree\fP & \fBGetSkillTree\fP () const"
.br
.ti -1c
.RI "\fBu8\fP \fBOpenSkillTree\fP (\fBu32\fP NodeId)"
.br
.ti -1c
.RI "void \fBOnRecvItemList\fP (const \fBFlexArray\fP< \fBItemData\fP > &List)"
.br
.ti -1c
.RI "void \fBUseItem\fP (\fBu32\fP ItemId, \fBCharacterPtr\fP pTarget)"
.br
.ti -1c
.RI "void \fBAddItem\fP (\fBu32\fP ItemId, \fBu32\fP Count)"
.br
.ti -1c
.RI "void \fBSubtractItem\fP (\fBu32\fP ItemId, \fBu32\fP Count)"
.br
.ti -1c
.RI "const \fBItemList\fP & \fBGetItemList\fP () const"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
プレイヤーキャラクタ 
.SH "構築子と解体子"
.PP 
.SS "PlayerCharacter::PlayerCharacter (\fBClient\fP * pInClient, \fBu32\fP InCharacterId, \fBu8\fP InJob, \fBu32\fP Level, int MaxHp, int Atk, int Def, int InExp, \fBu32\fP InGold)"

.SS "PlayerCharacter::~PlayerCharacter ()\fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void PlayerCharacter::AddExp (int Value)\fC [inline]\fP"

.SS "void PlayerCharacter::AddGold (\fBu32\fP Value)"

.SS "void PlayerCharacter::AddItem (\fBu32\fP ItemId, \fBu32\fP Count)"

.SS "\fBu32\fP PlayerCharacter::GetCharacterId () const\fC [inline]\fP"

.SS "virtual \fBu8\fP PlayerCharacter::GetCharacterType () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBCharacterBase\fPを実装しています。
.SS "\fBClient\fP* PlayerCharacter::GetClient () const\fC [inline]\fP"

.SS "int PlayerCharacter::GetExp () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBCharacterBase\fPを再実装しています。
.SS "\fBu32\fP PlayerCharacter::GetGold () const\fC [inline]\fP"

.SS "const \fBItemList\fP& PlayerCharacter::GetItemList () const\fC [inline]\fP"

.SS "\fBu8\fP PlayerCharacter::GetJob () const\fC [inline]\fP"

.SS "const std::string& PlayerCharacter::GetName () const\fC [inline]\fP"

.SS "\fBPartyPtr\fP PlayerCharacter::GetParty () const\fC [inline]\fP"

.SS "const \fBSkillTree\fP& PlayerCharacter::GetSkillTree () const\fC [inline]\fP"

.SS "void PlayerCharacter::InitializeSkillTree (const \fBFlexArray\fP< \fBu32\fP > & OpenedNodes)"

.SS "void PlayerCharacter::OnAreaChange ()"

.SS "void PlayerCharacter::OnMoved ()"

.SS "void PlayerCharacter::OnRecvItemList (const \fBFlexArray\fP< \fBItemData\fP > & List)"

.SS "\fBu8\fP PlayerCharacter::OpenSkillTree (\fBu32\fP NodeId)"

.SS "void PlayerCharacter::SetName (const std::string & InName)\fC [inline]\fP"

.SS "void PlayerCharacter::SetParty (const \fBPartyPtr\fP & pInParty)\fC [inline]\fP"

.SS "void PlayerCharacter::SubtractGold (\fBu32\fP Value)"

.SS "void PlayerCharacter::SubtractItem (\fBu32\fP ItemId, \fBu32\fP Count)"

.SS "void PlayerCharacter::UseItem (\fBu32\fP ItemId, \fBCharacterPtr\fP pTarget)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
