.TH "PlayerExp" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerExp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerExp\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBPlayerExp\fP (int InExp)"
.br
.ti -1c
.RI "\fB~PlayerExp\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (int Value)"
.br
.ti -1c
.RI "int \fBGet\fP () const"
.br
.ti -1c
.RI "void \fBSetLevelUpCallback\fP (const function< void()> &InLevelUpCallback)"
.br
.in -1c
.SH "詳解"
.PP 
プレイヤーの経験値管理\&. 
.SH "構築子と解体子"
.PP 
.SS "PlayerExp::PlayerExp (int InExp)"

.SS "PlayerExp::~PlayerExp ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void PlayerExp::Add (int Value)"

.SS "int PlayerExp::Get () const\fC [inline]\fP"

.SS "void PlayerExp::SetLevelUpCallback (const function< void()> & InLevelUpCallback)\fC [inline]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
