.TH "QuestMaster.cpp" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestMaster.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'QuestMaster\&.h'\fP
.br
\fC#include 'MySQL/MySqlConnection\&.h'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBQuestItem\fP &A, const \fBQuestItem\fP &B)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBQuestItem\fP &A, const \fBQuestItem\fP &B)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool operator< (const \fBQuestItem\fP & A, const \fBQuestItem\fP & B)"

.SS "bool operator> (const \fBQuestItem\fP & A, const \fBQuestItem\fP & B)"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
