.TH "QuestItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBMAIN_QUEST\fP = 0, \fBSUB_QUEST\fP = 1 }"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBId\fP"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "std::string \fBExplain\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBStartStageId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBRewardId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBNextQuestId\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIMAIN_QUEST \fP\fP
.TP
\fB\fISUB_QUEST \fP\fP
.SH "メンバ詳解"
.PP 
.SS "std::string QuestItem::Explain"

.SS "\fBu32\fP QuestItem::Id"

.SS "std::string QuestItem::Name"

.SS "\fBu32\fP QuestItem::NextQuestId"

.SS "\fBu32\fP QuestItem::RewardId"

.SS "\fBu32\fP QuestItem::StartStageId"

.SS "\fBu8\fP QuestItem::Type"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
