.TH "QuestRewardItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestRewardItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestRewardMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBNONE\fP = 0, \fBITEM\fP = 1, \fBGOLD\fP = 2 }"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBItemId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCount\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIITEM \fP\fP
.TP
\fB\fIGOLD \fP\fP
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP QuestRewardItem::Count"

.SS "\fBu32\fP QuestRewardItem::ID"

.SS "\fBu32\fP QuestRewardItem::ItemId"

.SS "\fBu8\fP QuestRewardItem::Type"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
