.TH "QuestRewardMaster.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestRewardMaster.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBQuestRewardItem\fP"
.br
.ti -1c
.RI "class \fBQuestRewardMaster\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBQuestRewardItem\fP &A, const \fBQuestRewardItem\fP &B)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBQuestRewardItem\fP &A, const \fBQuestRewardItem\fP &B)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool operator< (const \fBQuestRewardItem\fP & A, const \fBQuestRewardItem\fP & B)"

.SS "bool operator> (const \fBQuestRewardItem\fP & A, const \fBQuestRewardItem\fP & B)"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
