.TH "QuestManager" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QuestManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBQuestManager\fP (\fBClient\fP *pInClient)"
.br
.ti -1c
.RI "\fB~QuestManager\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBQuestData\fP &Data)"
.br
.ti -1c
.RI "void \fBAccept\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "\fBu8\fP \fBRetire\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "void \fBProgressStage\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "void \fBOnKilledAnpan\fP (\fBu32\fP AreaId)"
.br
.ti -1c
.RI "bool \fBIsActive\fP (\fBu32\fP QuestId) const"
.br
.ti -1c
.RI "bool \fBIsClear\fP (\fBu32\fP QuestId) const"
.br
.ti -1c
.RI "\fBu32\fP \fBGetStageNo\fP (\fBu32\fP QuestId) const"
.br
.in -1c
.SH "詳解"
.PP 
クエスト管理\&. 
.SH "構築子と解体子"
.PP 
.SS "QuestManager::QuestManager (\fBClient\fP * pInClient)"

.SS "QuestManager::~QuestManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void QuestManager::Accept (\fBu32\fP QuestId)"

.SS "void QuestManager::Add (const \fBQuestData\fP & Data)"

.SS "\fBu32\fP QuestManager::GetStageNo (\fBu32\fP QuestId) const"

.SS "bool QuestManager::IsActive (\fBu32\fP QuestId) const\fC [inline]\fP"

.SS "bool QuestManager::IsClear (\fBu32\fP QuestId) const"

.SS "void QuestManager::OnKilledAnpan (\fBu32\fP AreaId)"

.SS "void QuestManager::ProgressStage (\fBu32\fP QuestId)"

.SS "\fBu8\fP QuestManager::Retire (\fBu32\fP QuestId)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
