.TH "Random.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Random.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/random\&.hpp>\fP
.br
\fC#include <boost/random/random_device\&.hpp>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBRandom\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
