.TH "Random" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Random
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Random\&.h>\fP
.PP
noncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fB~Random\fP ()"
.br
.ti -1c
.RI "template<> int \fBRange\fP (int Min, int Max)"
.br
.ti -1c
.RI "template<> float \fBRange\fP (float Min, float Max)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "template<class T > static T \fBRange\fP (T Min, T Max)"
.br
.in -1c
.SH "詳解"
.PP 
乱数クラス 
.SH "構築子と解体子"
.PP 
.SS "Random::~Random ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "template<> int Random::Range (int Min, int Max)"

.SS "template<class T > static T Random::Range (T Min, T Max)\fC [static]\fP"

.SS "template<> float Random::Range (float Min, float Max)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
