.TH "Rotation" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rotation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rotation\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBRotation\fP ()"
.br
.ti -1c
.RI "\fBRotation\fP (float InValue)"
.br
.ti -1c
.RI "\fB~Rotation\fP ()"
.br
.ti -1c
.RI "float \fBGet\fP () const"
.br
.ti -1c
.RI "void \fBSet\fP (float InValue)"
.br
.ti -1c
.RI "float \fBoperator+\fP (float InValue) const"
.br
.ti -1c
.RI "float \fBoperator\-\fP (float InValue) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (float InValue)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (float InValue)"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "Rotation::Rotation ()"

.SS "Rotation::Rotation (float InValue)"

.SS "Rotation::~Rotation ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "float Rotation::Get () const\fC [inline]\fP"

.SS "float Rotation::operator+ (float InValue) const"

.SS "void Rotation::operator+= (float InValue)"

.SS "float Rotation::operator\- (float InValue) const"

.SS "void Rotation::operator\-= (float InValue)"

.SS "void Rotation::Set (float InValue)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
