.TH "ScriptExecuter" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptExecuter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptExecuter\&.h>\fP
.PP
\fBScriptExecuterBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBScriptExecuter\fP ()"
.br
.ti -1c
.RI "virtual \fB~ScriptExecuter\fP ()"
.br
.ti -1c
.RI "void \fBSetClient\fP (\fBClient\fP *pInClient)"
.br
.ti -1c
.RI "void \fBLoadAndRun\fP (const std::string &FileName)"
.br
.ti -1c
.RI "virtual void \fBShowMessage_Impl\fP (const std::string &Message)"
.br
.ti -1c
.RI "virtual void \fBPushSelection_Impl\fP (const std::string &Message)"
.br
.ti -1c
.RI "virtual void \fBShowSelection_Impl\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetFlag\fP (int Flag)"
.br
.ti -1c
.RI "virtual bool \fBGetFlag\fP (int Flag)"
.br
.ti -1c
.RI "virtual bool \fBIsQuestActive\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "virtual void \fBProgressQuest\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetQuestStageNo\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetItemCount\fP (\fBu32\fP ItemId)"
.br
.ti -1c
.RI "virtual void \fBConsumeItem\fP (\fBu32\fP ItemId, \fBu32\fP Count)"
.br
.ti -1c
.RI "virtual void \fBAcceptQuest\fP (\fBu32\fP QuestId)"
.br
.ti -1c
.RI "virtual bool \fBIsQuestClear\fP (\fBu32\fP QuestId)"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual void \fBOnExecuteError\fP (const std::string &ErrorMessage)"
.br
.ti -1c
.RI "virtual void \fBOnFinished\fP ()"
.br
.ti -1c
.RI "virtual void \fBShowDebugMessage\fP (const std::string &Message)"
.br
.ti -1c
.RI "virtual bool \fBIsServer\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
スクリプト実行クラス 
.SH "構築子と解体子"
.PP 
.SS "ScriptExecuter::ScriptExecuter ()"

.SS "virtual ScriptExecuter::~ScriptExecuter ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void ScriptExecuter::AcceptQuest (\fBu32\fP QuestId)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::ConsumeItem (\fBu32\fP ItemId, \fBu32\fP Count)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "bool ScriptExecuter::GetFlag (int Flag)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "\fBu32\fP ScriptExecuter::GetItemCount (\fBu32\fP ItemId)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "\fBu32\fP ScriptExecuter::GetQuestStageNo (\fBu32\fP QuestId)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "bool ScriptExecuter::IsQuestActive (\fBu32\fP QuestId)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "bool ScriptExecuter::IsQuestClear (\fBu32\fP QuestId)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual bool ScriptExecuter::IsServer () const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::LoadAndRun (const std::string & FileName)"

.SS "void ScriptExecuter::OnExecuteError (const std::string & ErrorMessage)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::OnFinished ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::ProgressQuest (\fBu32\fP QuestId)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual void ScriptExecuter::PushSelection_Impl (const std::string & Message)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::SetClient (\fBClient\fP * pInClient)\fC [inline]\fP"

.SS "void ScriptExecuter::SetFlag (int Flag)\fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "void ScriptExecuter::ShowDebugMessage (const std::string & Message)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual void ScriptExecuter::ShowMessage_Impl (const std::string & Message)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。
.SS "virtual void ScriptExecuter::ShowSelection_Impl ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBScriptExecuterBase\fPを実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
