.TH "ScriptFlagManager" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptFlagManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptFlagManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBScriptFlagManager\fP ()"
.br
.ti -1c
.RI "\fB~ScriptFlagManager\fP ()"
.br
.ti -1c
.RI "void \fBSet\fP (int Key)"
.br
.ti -1c
.RI "bool \fBGet\fP (int Key) const"
.br
.ti -1c
.RI "void \fBToBitField\fP (\fBu32\fP &OutBitField1, \fBu32\fP &OutBitField2, \fBu32\fP &OutBitField3) const"
.br
.ti -1c
.RI "void \fBFromBitField\fP (\fBu32\fP BitField1, \fBu32\fP BitField2, \fBu32\fP BitField3)"
.br
.in -1c
.SH "詳解"
.PP 
スクリプトフラグ管理\&. 
.SH "構築子と解体子"
.PP 
.SS "ScriptFlagManager::ScriptFlagManager ()"

.SS "ScriptFlagManager::~ScriptFlagManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void ScriptFlagManager::FromBitField (\fBu32\fP BitField1, \fBu32\fP BitField2, \fBu32\fP BitField3)"

.SS "bool ScriptFlagManager::Get (int Key) const"

.SS "void ScriptFlagManager::Set (int Key)"

.SS "void ScriptFlagManager::ToBitField (\fBu32\fP & OutBitField1, \fBu32\fP & OutBitField2, \fBu32\fP & OutBitField3) const"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
