.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/Script/ScriptBinds.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/Script/ScriptBinds.h
.SH SYNOPSIS
.br
.PP
.SS "関数"

.in +1c
.ti -1c
.RI "int \fBShowMessage_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBPushSelection_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBShowSelection_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBSetFlag_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBGetFlag_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBIsQuestActive_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBProgressQuest_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBGetQuestStageNo_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBGetItemCount_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBConsumeItem_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBAcceptQuest_Call\fP (lua_State *pState)"
.br
.ti -1c
.RI "int \fBIsQuestClear_Call\fP (lua_State *pState)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "int AcceptQuest_Call (lua_State * pState)"

.SS "int ConsumeItem_Call (lua_State * pState)"

.SS "int GetFlag_Call (lua_State * pState)"

.SS "int GetItemCount_Call (lua_State * pState)"

.SS "int GetQuestStageNo_Call (lua_State * pState)"

.SS "int IsQuestActive_Call (lua_State * pState)"

.SS "int IsQuestClear_Call (lua_State * pState)"

.SS "int ProgressQuest_Call (lua_State * pState)"

.SS "int PushSelection_Call (lua_State * pState)"

.SS "int SetFlag_Call (lua_State * pState)"

.SS "int ShowMessage_Call (lua_State * pState)"

.SS "int ShowSelection_Call (lua_State * pState)"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
