.TH "SkillTreeMaster" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillTreeMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillTreeMaster\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "bool \fBLoad\fP (const \fBMySqlConnection\fP &Connection)"
.br
.ti -1c
.RI "const \fBSkillTreeItem\fP * \fBGetItem\fP (\fBu32\fP Key) const"
.br
.ti -1c
.RI "std::vector< \fBSkillTreeItem\fP > \fBGetAll\fP () const"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "std::vector< \fBSkillTreeItem\fP > SkillTreeMaster::GetAll () const"

.SS "const \fBSkillTreeItem\fP * SkillTreeMaster::GetItem (\fBu32\fP Key) const"

.SS "bool SkillTreeMaster::Load (const \fBMySqlConnection\fP & Connection)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
