.TH "SkillStateNutral" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillStateNutral
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillStateNutral\&.h>\fP
.PP
\fBSkillStateBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSkillStateNutral\fP (\fBSkillControl\fP *pInControl)"
.br
.ti -1c
.RI "virtual \fB~SkillStateNutral\fP ()"
.br
.ti -1c
.RI "virtual \fBESkillStateType\fP \fBGetStateType\fP ()"
.br
.in -1c
.SS "その他の継承メンバ"
.SH "詳解"
.PP 
スキルステート：何もしていない 
.SH "構築子と解体子"
.PP 
.SS "SkillStateNutral::SkillStateNutral (\fBSkillControl\fP * pInControl)"

.SS "virtual SkillStateNutral::~SkillStateNutral ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBESkillStateType\fP SkillStateNutral::GetStateType ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBSkillStateBase\fPを実装しています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
