.TH "SkillTree" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillTree
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillTree\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSkillTree\fP (\fBu8\fP Job)"
.br
.ti -1c
.RI "\fB~SkillTree\fP ()"
.br
.ti -1c
.RI "bool \fBOpen\fP (\fBu32\fP NodeId)"
.br
.ti -1c
.RI "bool \fBIsOpened\fP (\fBu32\fP NodeId, bool &bOutOpened) const"
.br
.ti -1c
.RI "bool \fBGetSkillId\fP (\fBu32\fP NodeId, \fBu32\fP &OutSkillId) const"
.br
.ti -1c
.RI "void \fBGenerateNodeDataList\fP (\fBFlexArray\fP< \fBSkillTreeNode\fP > &OutDataList) const"
.br
.in -1c
.SH "詳解"
.PP 
スキルツリークラス 
.SH "構築子と解体子"
.PP 
.SS "SkillTree::SkillTree (\fBu8\fP Job)"

.SS "SkillTree::~SkillTree ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void SkillTree::GenerateNodeDataList (\fBFlexArray\fP< \fBSkillTreeNode\fP > & OutDataList) const"

.SS "bool SkillTree::GetSkillId (\fBu32\fP NodeId, \fBu32\fP & OutSkillId) const"

.SS "bool SkillTree::IsOpened (\fBu32\fP NodeId, bool & bOutOpened) const"

.SS "bool SkillTree::Open (\fBu32\fP NodeId)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
