.TH "SkillControl.cpp" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillControl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'SkillControl\&.h'\fP
.br
\fC#include 'Master/MasterData\&.h'\fP
.br
\fC#include 'Character/CharacterBase\&.h'\fP
.br
\fC#include 'Character/Player/PlayerCharacter\&.h'\fP
.br
\fC#include 'Character/Anpan/Anpan\&.h'\fP
.br
\fC#include 'Math/DamageCalcUnit\&.h'\fP
.br
\fC#include 'Math/Random\&.h'\fP
.br
\fC#include 'State/SkillStateNutral\&.h'\fP
.br
\fC#include 'State/SkillStateCast\&.h'\fP
.br
\fC#include 'State/SkillStateAutoMove\&.h'\fP
.br
\fC#include 'Packet/CharacterType\&.h'\fP
.br
\fC#include 'Packet/PacketSkillCastFinish\&.h'\fP
.br
\fC#include 'Packet/PacketSkillActivate\&.h'\fP
.br
\fC#include 'Packet/PacketSkillUseFailed\&.h'\fP
.br

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
