.TH "SkillTreeNode" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillTreeNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillTreeNode\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBNodeState\fP { \fBClosed\fP, \fBOpen\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSkillTreeNode\fP ()"
.br
.ti -1c
.RI "\fBSkillTreeNode\fP (\fBu32\fP InNodeId, \fBu8\fP InState)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBNodeId\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBState\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBSkillTreeNode::NodeState\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIClosed \fP\fP
.TP
\fB\fIOpen \fP\fP
.SH "構築子と解体子"
.PP 
.SS "SkillTreeNode::SkillTreeNode ()\fC [inline]\fP"

.SS "SkillTreeNode::SkillTreeNode (\fBu32\fP InNodeId, \fBu8\fP InState)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool SkillTreeNode::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP SkillTreeNode::NodeId"

.SS "\fBu8\fP SkillTreeNode::State"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
