.TH "SkillStateBase" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillStateBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillStateBase\&.h>\fP
.PP
\fBSkillStateAutoMove\fP, \fBSkillStateCast\fP, \fBSkillStateNutral\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSkillStateBase\fP (\fBSkillControl\fP *pInControl)"
.br
.ti -1c
.RI "virtual \fB~SkillStateBase\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBBeginState\fP ()"
.br
.ti -1c
.RI "virtual void \fBPoll\fP (\fBs32\fP DeltaTime)"
.br
.ti -1c
.RI "virtual \fBESkillStateType\fP \fBGetStateType\fP ()=0"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSkillControl\fP * \fBGetControl\fP () const"
.br
.in -1c
.SH "詳解"
.PP 
スキルステート基底クラス 
.SH "構築子と解体子"
.PP 
.SS "SkillStateBase::SkillStateBase (\fBSkillControl\fP * pInControl)"

.SS "SkillStateBase::~SkillStateBase ()\fC [pure virtual]\fP"

.SH "関数詳解"
.PP 
.SS "virtual void SkillStateBase::BeginState ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBSkillStateCast\fPで再実装されています。
.SS "\fBSkillControl\fP* SkillStateBase::GetControl () const\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual \fBESkillStateType\fP SkillStateBase::GetStateType ()\fC [pure virtual]\fP"

.PP
\fBSkillStateAutoMove\fP, \fBSkillStateCast\fP, \fBSkillStateNutral\fPで実装されています。
.SS "virtual void SkillStateBase::Poll (\fBs32\fP DeltaTime)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBSkillStateAutoMove\fP, \fBSkillStateCast\fPで再実装されています。

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
