.TH "SkillTreeItem" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillTreeItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillTreeMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBFIGHTER\fP = 0, \fBSORCERER\fP = 1, \fBHEALER\fP = 2, \fBLANCER\fP = 3 }"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBJob\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBNeedLevel\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCost\fP"
.br
.ti -1c
.RI "float \fBNodeX\fP"
.br
.ti -1c
.RI "float \fBNodeY\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBParentNode\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIFIGHTER \fP\fP
.TP
\fB\fISORCERER \fP\fP
.TP
\fB\fIHEALER \fP\fP
.TP
\fB\fILANCER \fP\fP
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP SkillTreeItem::Cost"

.SS "\fBu32\fP SkillTreeItem::ID"

.SS "\fBu8\fP SkillTreeItem::Job"

.SS "\fBu32\fP SkillTreeItem::NeedLevel"

.SS "float SkillTreeItem::NodeX"

.SS "float SkillTreeItem::NodeY"

.SS "\fBu32\fP SkillTreeItem::ParentNode"

.SS "\fBu32\fP SkillTreeItem::SkillId"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
