.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/Skill/State/SkillStateBase.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/Skill/State/SkillStateBase.h
.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBSkillStateBase\fP"
.br
.in -1c
.SS "列挙型"

.in +1c
.ti -1c
.RI "enum \fBESkillStateType\fP { \fBNutral\fP, \fBCast\fP, \fBAutoMove\fP }"
.br
.in -1c
.SH "列挙型詳解"
.PP 
.SS "enum \fBESkillStateType\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINutral \fP\fP
.TP
\fB\fICast \fP\fP
.TP
\fB\fIAutoMove \fP\fP
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
