.TH "stdafx.h" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdafx.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include 'basic_repeating_timer\&.h'\fP
.br
\fC#include 'TypeDefs\&.h'\fP
.br

.SS "マクロ定義"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_WINNT\fP   0x0501"
.br
.in -1c
.SH "マクロ定義詳解"
.PP 
.SS "#define _WIN32_WINNT   0x0501"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
