.TH "TCPConnection" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TCPConnection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TCPConnection\&.h>\fP
.PP
\fBCacheServerConnection\fP, \fBClient\fP, \fBWordCheckServerConnection\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBTCPConnection\fP (const shared_ptr< tcp::socket > &pInSocket)"
.br
.ti -1c
.RI "virtual \fB~TCPConnection\fP ()=0"
.br
.ti -1c
.RI "bool \fBIsConnected\fP () const"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "tcp::socket * \fBGetSocket\fP ()"
.br
.ti -1c
.RI "void \fBAsyncRecv\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRecvData\fP (size_t Size)"
.br
.ti -1c
.RI "virtual void \fBOnDisconnected\fP ()"
.br
.ti -1c
.RI "void \fBAsyncSend\fP (const \fBu8\fP *pBuffer, int Size)"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "\fBMemoryBuffer\fP \fBRecvBuffer\fP"
.br
.ti -1c
.RI "bool \fBbIsConnected\fP"
.br
.in -1c
.SH "詳解"
.PP 
TCP接続クラス 
.SH "構築子と解体子"
.PP 
.SS "TCPConnection::TCPConnection (const shared_ptr< tcp::socket > & pInSocket)"

.SS "TCPConnection::~TCPConnection ()\fC [pure virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void TCPConnection::AsyncRecv ()\fC [protected]\fP"

.SS "void TCPConnection::AsyncSend (const \fBu8\fP * pBuffer, int Size)\fC [protected]\fP"

.SS "tcp::socket* TCPConnection::GetSocket ()\fC [inline]\fP, \fC [protected]\fP"

.SS "bool TCPConnection::IsConnected () const\fC [inline]\fP"

.SS "virtual void TCPConnection::OnDisconnected ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBCacheServerConnection\fP, \fBWordCheckServerConnection\fPで再実装されています。
.SS "virtual void TCPConnection::OnRecvData (size_t Size)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBClient\fP, \fBCacheServerConnection\fP, \fBWordCheckServerConnection\fPで再実装されています。
.SH "メンバ詳解"
.PP 
.SS "bool TCPConnection::bIsConnected\fC [protected]\fP"

.SS "\fBMemoryBuffer\fP TCPConnection::RecvBuffer\fC [protected]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
