.TH "TickManager" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TickManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TickManager\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fB~TickManager\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const TickFunction &Function)"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBTickManager\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
時間を伴うフレーム処理管理\&. 
.SH "構築子と解体子"
.PP 
.SS "TickManager::~TickManager ()\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "void TickManager::Add (const TickFunction & Function)"

.SS "static \fBTickManager\fP& TickManager::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "void TickManager::Poll ()"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
