.TH "TimeManager" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TimeManager\&.h>\fP
.PP
noncopyableを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fB~TimeManager\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP (int DeltaTime)"
.br
.ti -1c
.RI "\fBu32\fP \fBGetMasterId\fP () const"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBTimeManager\fP & \fBGetInstance\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
時間管理\&. 
.SH "構築子と解体子"
.PP 
.SS "virtual TimeManager::~TimeManager ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "static \fBTimeManager\fP& TimeManager::GetInstance ()\fC [inline]\fP, \fC [static]\fP"

.SS "\fBu32\fP TimeManager::GetMasterId () const\fC [inline]\fP"

.SS "void TimeManager::Initialize ()"

.SS "void TimeManager::Poll (int DeltaTime)"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
