.TH "Util" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Util
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Util\&.h>\fP
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBu32\fP \fBCalcStringLength\fP (const std::string &Str)"
.br
.ti -1c
.RI "static \fBu32\fP \fBCalcCharByte\fP (unsigned char Ch)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBu32\fP Util::CalcCharByte (unsigned char Ch)\fC [static]\fP"

.SS "\fBu32\fP Util::CalcStringLength (const std::string & Str)\fC [static]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
