.TH "Vector3D" 3 "2018年12月21日(金)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector3D
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vector3D\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBVector3D\fP ()"
.br
.ti -1c
.RI "\fBVector3D\fP (float InX, float InY, float InZ)"
.br
.ti -1c
.RI "\fBVector3D\fP (const \fBVector3D\fP &Arg)"
.br
.ti -1c
.RI "float \fBGetSize\fP () const"
.br
.ti -1c
.RI "float \fBGetSizeSq\fP () const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBGetNormalized\fP () const"
.br
.ti -1c
.RI "void \fBNormalize\fP ()"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator+\fP (const \fBVector3D\fP &Arg) const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator\-\fP (const \fBVector3D\fP &Arg) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBVector3D\fP &Arg)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBVector3D\fP &Arg)"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator*\fP (float Arg) const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator/\fP (float Arg) const"
.br
.ti -1c
.RI "void \fBoperator*=\fP (float Arg)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (float Arg)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVector3D\fP &Arg) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBVector3D\fP &Arg) const"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "float \fBX\fP"
.br
.ti -1c
.RI "float \fBY\fP"
.br
.ti -1c
.RI "float \fBZ\fP"
.br
.in -1c
.SS "静的公開変数類"

.in +1c
.ti -1c
.RI "static const \fBVector3D\fP \fBZero\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "Vector3D::Vector3D ()\fC [inline]\fP"

.SS "Vector3D::Vector3D (float InX, float InY, float InZ)\fC [inline]\fP"

.SS "Vector3D::Vector3D (const \fBVector3D\fP & Arg)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "\fBVector3D\fP Vector3D::GetNormalized () const\fC [inline]\fP"

.SS "float Vector3D::GetSize () const\fC [inline]\fP"

.SS "float Vector3D::GetSizeSq () const\fC [inline]\fP"

.SS "void Vector3D::Normalize ()\fC [inline]\fP"

.SS "bool Vector3D::operator!= (const \fBVector3D\fP & Arg) const\fC [inline]\fP"

.SS "\fBVector3D\fP Vector3D::operator* (float Arg) const\fC [inline]\fP"

.SS "void Vector3D::operator*= (float Arg)\fC [inline]\fP"

.SS "\fBVector3D\fP Vector3D::operator+ (const \fBVector3D\fP & Arg) const\fC [inline]\fP"

.SS "void Vector3D::operator+= (const \fBVector3D\fP & Arg)\fC [inline]\fP"

.SS "\fBVector3D\fP Vector3D::operator\- (const \fBVector3D\fP & Arg) const\fC [inline]\fP"

.SS "void Vector3D::operator\-= (const \fBVector3D\fP & Arg)\fC [inline]\fP"

.SS "\fBVector3D\fP Vector3D::operator/ (float Arg) const\fC [inline]\fP"

.SS "void Vector3D::operator/= (float Arg)\fC [inline]\fP"

.SS "bool Vector3D::operator== (const \fBVector3D\fP & Arg) const\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "float Vector3D::X"

.SS "float Vector3D::Y"

.SS "float Vector3D::Z"

.SS "const \fBVector3D\fP Vector3D::Zero\fC [static]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
