.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/WeakPtrDefine.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/WeakPtrDefine.h
.SH SYNOPSIS
.br
.PP
.SS "型定義"

.in +1c
.ti -1c
.RI "typedef weak_ptr< \fBCharacterBase\fP > \fBCharacterPtr\fP"
.br
.ti -1c
.RI "typedef weak_ptr< \fBPlayerCharacter\fP > \fBPlayerCharacterPtr\fP"
.br
.ti -1c
.RI "typedef weak_ptr< \fBAnpan\fP > \fBAnpanPtr\fP"
.br
.ti -1c
.RI "typedef weak_ptr< \fBParty\fP > \fBPartyPtr\fP"
.br
.ti -1c
.RI "typedef weak_ptr< \fBClient\fP > \fBClientPtr\fP"
.br
.ti -1c
.RI "typedef weak_ptr< \fBAreaBase\fP > \fBAreaPtr\fP"
.br
.in -1c
.SH "型定義詳解"
.PP 
.SS "typedef weak_ptr<\fBAnpan\fP> \fBAnpanPtr\fP"

.SS "typedef weak_ptr<\fBAreaBase\fP> \fBAreaPtr\fP"

.SS "typedef weak_ptr<\fBCharacterBase\fP> \fBCharacterPtr\fP"

.SS "typedef weak_ptr<\fBClient\fP> \fBClientPtr\fP"

.SS "typedef weak_ptr<\fBParty\fP> \fBPartyPtr\fP"

.SS "typedef weak_ptr<\fBPlayerCharacter\fP> \fBPlayerCharacterPtr\fP"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
