.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/Area/AreaConfig.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/Area/AreaConfig.h
.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBAreaConfig\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
