.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/Bitmap.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/Bitmap.h
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include 'EndianConverter\&.h'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBBitmapFileHeader\fP"
.br
.ti -1c
.RI "struct \fBBitmapInfoData\fP"
.br
.ti -1c
.RI "struct \fBColor24\fP"
.br
.ti -1c
.RI "class \fBBitmap\fP"
.br
.in -1c
.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
