.TH "CharacterBase" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CharacterBase\&.h>\fP
.PP
enable_shared_from_this< CharacterBase >を継承しています。
.PP
\fBAnpan\fP, \fBPlayerCharacter\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBCharacterBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~CharacterBase\fP ()"
.br
.ti -1c
.RI "void \fBPoll\fP (\fBs32\fP DeltaTime)"
.br
.ti -1c
.RI "const \fBCharacterParameter\fP & \fBGetParameter\fP () const"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBVector3D\fP &MoveTarget)"
.br
.ti -1c
.RI "void \fBSetRotate\fP (const \fBRotation\fP &TargetRotation)"
.br
.ti -1c
.RI "const \fBVector3D\fP & \fBGetPosition\fP () const"
.br
.ti -1c
.RI "const \fBRotation\fP & \fBGetRotation\fP () const"
.br
.ti -1c
.RI "bool \fBIsDead\fP () const"
.br
.ti -1c
.RI "void \fBApplyDamage\fP (\fBCharacterPtr\fP pAttacker, int Value)"
.br
.ti -1c
.RI "void \fBHeal\fP (int Value)"
.br
.ti -1c
.RI "\fBVector3D\fP \fBGetCenterVec\fP () const"
.br
.ti -1c
.RI "void \fBSetUuid\fP (\fBu32\fP InUuid)"
.br
.ti -1c
.RI "\fBu32\fP \fBGetUuid\fP () const"
.br
.ti -1c
.RI "\fBu32\fP \fBGetLevel\fP () const"
.br
.ti -1c
.RI "virtual \fBu8\fP \fBGetCharacterType\fP () const =0"
.br
.ti -1c
.RI "void \fBMove\fP (const \fBVector3D\fP &MoveValue)"
.br
.ti -1c
.RI "void \fBRotate\fP (float RotateValue)"
.br
.ti -1c
.RI "void \fBRespawn\fP ()"
.br
.ti -1c
.RI "void \fBSetArea\fP (const \fBAreaPtr\fP &pInArea)"
.br
.ti -1c
.RI "\fBAreaPtr\fP \fBGetArea\fP () const"
.br
.ti -1c
.RI "void \fBUseSkill\fP (\fBu32\fP SkillId, \fBCharacterPtr\fP pTarget)"
.br
.ti -1c
.RI "void \fBStartRecast\fP (\fBu32\fP SkillId)"
.br
.ti -1c
.RI "bool \fBIsSkillActive\fP () const"
.br
.ti -1c
.RI "bool \fBIsSkillCasting\fP () const"
.br
.ti -1c
.RI "bool \fBIsRecasting\fP (\fBu32\fP SkillId) const"
.br
.ti -1c
.RI "virtual int \fBGetExp\fP () const"
.br
.ti -1c
.RI "virtual \fBu32\fP \fBGetDropId\fP () const"
.br
.in -1c
.SS "限定公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBSetParameter\fP (\fBu32\fP Level, int Hp, int MaxHp, int Atk, int Def)"
.br
.ti -1c
.RI "void \fBLevelUp\fP (int MaxHp, int Atk, int Def)"
.br
.ti -1c
.RI "virtual void \fBOnDamaged\fP (weak_ptr< \fBCharacterBase\fP > pAttacker, int DamageValue)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (\fBs32\fP DeltaTime)"
.br
.in -1c
.SS "限定公開変数類"

.in +1c
.ti -1c
.RI "\fBVector3D\fP \fBPosition\fP"
.br
.ti -1c
.RI "\fBRotation\fP \fBRot\fP"
.br
.ti -1c
.RI "\fBSkillControl\fP \fBSkill\fP"
.br
.ti -1c
.RI "\fBSkillRecastManager\fP \fBRecast\fP"
.br
.in -1c
.SH "詳解"
.PP 
キャラクタ基底クラス 
.SH "構築子と解体子"
.PP 
.SS "CharacterBase::CharacterBase ()"

.SS "virtual CharacterBase::~CharacterBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "関数詳解"
.PP 
.SS "void CharacterBase::ApplyDamage (\fBCharacterPtr\fP pAttacker, int Value)"

.SS "\fBAreaPtr\fP CharacterBase::GetArea () const\fC [inline]\fP"

.SS "\fBVector3D\fP CharacterBase::GetCenterVec () const"

.SS "virtual \fBu8\fP CharacterBase::GetCharacterType () const\fC [pure virtual]\fP"

.PP
\fBPlayerCharacter\fP, \fBAnpan\fPで実装されています。
.SS "virtual \fBu32\fP CharacterBase::GetDropId () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBAnpan\fPで再実装されています。
.SS "virtual int CharacterBase::GetExp () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPlayerCharacter\fP, \fBAnpan\fPで再実装されています。
.SS "\fBu32\fP CharacterBase::GetLevel () const\fC [inline]\fP"

.SS "const \fBCharacterParameter\fP& CharacterBase::GetParameter () const\fC [inline]\fP"

.SS "const \fBVector3D\fP& CharacterBase::GetPosition () const\fC [inline]\fP"

.SS "const \fBRotation\fP& CharacterBase::GetRotation () const\fC [inline]\fP"

.SS "\fBu32\fP CharacterBase::GetUuid () const\fC [inline]\fP"

.SS "void CharacterBase::Heal (int Value)"

.SS "bool CharacterBase::IsDead () const\fC [inline]\fP"

.SS "bool CharacterBase::IsRecasting (\fBu32\fP SkillId) const\fC [inline]\fP"

.SS "bool CharacterBase::IsSkillActive () const\fC [inline]\fP"

.SS "bool CharacterBase::IsSkillCasting () const\fC [inline]\fP"

.SS "void CharacterBase::LevelUp (int MaxHp, int Atk, int Def)\fC [inline]\fP, \fC [protected]\fP"

.SS "void CharacterBase::Move (const \fBVector3D\fP & MoveValue)"

.SS "virtual void CharacterBase::OnDamaged (weak_ptr< \fBCharacterBase\fP > pAttacker, int DamageValue)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBAnpan\fPで再実装されています。
.SS "void CharacterBase::Poll (\fBs32\fP DeltaTime)"

.SS "void CharacterBase::Respawn ()"

.SS "void CharacterBase::Rotate (float RotateValue)"

.SS "void CharacterBase::SetArea (const \fBAreaPtr\fP & pInArea)\fC [inline]\fP"

.SS "void CharacterBase::SetParameter (\fBu32\fP Level, int Hp, int MaxHp, int Atk, int Def)\fC [inline]\fP, \fC [protected]\fP"

.SS "void CharacterBase::SetPosition (const \fBVector3D\fP & MoveTarget)"

.SS "void CharacterBase::SetRotate (const \fBRotation\fP & TargetRotation)"

.SS "void CharacterBase::SetUuid (\fBu32\fP InUuid)\fC [inline]\fP"

.SS "void CharacterBase::StartRecast (\fBu32\fP SkillId)"

.SS "virtual void CharacterBase::Update (\fBs32\fP DeltaTime)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBAnpan\fPで再実装されています。
.SS "void CharacterBase::UseSkill (\fBu32\fP SkillId, \fBCharacterPtr\fP pTarget)"

.SH "メンバ詳解"
.PP 
.SS "\fBVector3D\fP CharacterBase::Position\fC [protected]\fP"

.SS "\fBSkillRecastManager\fP CharacterBase::Recast\fC [protected]\fP"

.SS "\fBRotation\fP CharacterBase::Rot\fC [protected]\fP"

.SS "\fBSkillControl\fP CharacterBase::Skill\fC [protected]\fP"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
