.TH "ItemData" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ItemData\&.h>\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBItemData\fP ()"
.br
.ti -1c
.RI "\fBItemData\fP (\fBu32\fP InItemId, \fBu32\fP InCount)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBItemId\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCount\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "ItemData::ItemData ()\fC [inline]\fP"

.SS "ItemData::ItemData (\fBu32\fP InItemId, \fBu32\fP InCount)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool ItemData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP ItemData::Count"

.SS "\fBu32\fP ItemData::ItemId"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
