.TH "NoticeData" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoticeData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoticeData\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum \fBNoticeType\fP { \fBPartyInvide\fP }"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBNoticeData\fP ()"
.br
.ti -1c
.RI "\fBNoticeData\fP (\fBu8\fP InType, \fBu32\fP InCustomerId, std::string InCharacterName)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCustomerId\fP"
.br
.ti -1c
.RI "std::string \fBCharacterName\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "enum \fBNoticeData::NoticeType\fP"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIPartyInvide \fP\fP
.SH "構築子と解体子"
.PP 
.SS "NoticeData::NoticeData ()\fC [inline]\fP"

.SS "NoticeData::NoticeData (\fBu8\fP InType, \fBu32\fP InCustomerId, std::string InCharacterName)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "bool NoticeData::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP"

.SH "メンバ詳解"
.PP 
.SS "std::string NoticeData::CharacterName"

.SS "\fBu32\fP NoticeData::CustomerId"

.SS "\fBu8\fP NoticeData::Type"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
