.TH "PacketSaveSkillListRequest" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketSaveSkillListRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketSaveSkillListRequest\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketSaveSkillListRequest\fP ()"
.br
.ti -1c
.RI "\fBPacketSaveSkillListRequest\fP (\fBu32\fP InSkillId1, \fBu32\fP InSkillId2, \fBu32\fP InSkillId3, \fBu32\fP InSkillId4)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBSkillId1\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId2\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId3\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkillId4\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketSaveSkillListRequest::PacketSaveSkillListRequest ()\fC [inline]\fP"

.SS "PacketSaveSkillListRequest::PacketSaveSkillListRequest (\fBu32\fP InSkillId1, \fBu32\fP InSkillId2, \fBu32\fP InSkillId3, \fBu32\fP InSkillId4)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketSaveSkillListRequest::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketSaveSkillListRequest::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketSaveSkillListRequest::SkillId1"

.SS "\fBu32\fP PacketSaveSkillListRequest::SkillId2"

.SS "\fBu32\fP PacketSaveSkillListRequest::SkillId3"

.SS "\fBu32\fP PacketSaveSkillListRequest::SkillId4"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
