.TH "PacketChangeGold" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketChangeGold
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PacketChangeGold\&.h>\fP
.PP
\fBPacketBase\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "virtual \fBu8\fP \fBGetPacketID\fP () const"
.br
.ti -1c
.RI "\fBPacketChangeGold\fP ()"
.br
.ti -1c
.RI "\fBPacketChangeGold\fP (\fBu32\fP InGold)"
.br
.ti -1c
.RI "bool \fBSerialize\fP (\fBMemoryStreamInterface\fP *pStream)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBGold\fP"
.br
.in -1c
.SH "構築子と解体子"
.PP 
.SS "PacketChangeGold::PacketChangeGold ()\fC [inline]\fP"

.SS "PacketChangeGold::PacketChangeGold (\fBu32\fP InGold)\fC [inline]\fP"

.SH "関数詳解"
.PP 
.SS "virtual \fBu8\fP PacketChangeGold::GetPacketID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SS "bool PacketChangeGold::Serialize (\fBMemoryStreamInterface\fP * pStream)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBPacketBase\fPを実装しています。
.SH "メンバ詳解"
.PP 
.SS "\fBu32\fP PacketChangeGold::Gold"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
