.TH "SkillItem" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkillItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkillMaster\&.h>\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "enum { \fBATTACK\fP = 0, \fBHEAL\fP = 1, \fBBUFF\fP = 2, \fBDEBUFF\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBNORMAL\fP = 0, \fBRANGE_CIRCLE\fP = 1, \fBRANGE_BOX\fP = 2 }"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBID\fP"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBSkillType\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBRangeType\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBDistance\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBRangeX\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBRangeY\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBCastTime\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBRecastTime\fP"
.br
.in -1c
.SH "列挙型メンバ詳解"
.PP 
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fIATTACK \fP\fP
.TP
\fB\fIHEAL \fP\fP
.TP
\fB\fIBUFF \fP\fP
.TP
\fB\fIDEBUFF \fP\fP
.SS "anonymous enum"

.PP
\fB列挙値\fP
.in +1c
.TP
\fB\fINORMAL \fP\fP
.TP
\fB\fIRANGE_CIRCLE \fP\fP
.TP
\fB\fIRANGE_BOX \fP\fP
.SH "メンバ詳解"
.PP 
.SS "\fBs32\fP SkillItem::CastTime"

.SS "\fBs32\fP SkillItem::Distance"

.SS "\fBu32\fP SkillItem::ID"

.SS "std::string SkillItem::Name"

.SS "\fBu8\fP SkillItem::RangeType"

.SS "\fBs32\fP SkillItem::RangeX"

.SS "\fBs32\fP SkillItem::RangeY"

.SS "\fBs32\fP SkillItem::RecastTime"

.SS "\fBu8\fP SkillItem::SkillType"


.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
