.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/Master/SkillMaster.cpp" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/Master/SkillMaster.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'SkillMaster\&.h'\fP
.br
\fC#include 'MySQL/MySqlConnection\&.h'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSkillItem\fP &A, const \fBSkillItem\fP &B)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBSkillItem\fP &A, const \fBSkillItem\fP &B)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "bool operator< (const \fBSkillItem\fP & A, const \fBSkillItem\fP & B)"

.SS "bool operator> (const \fBSkillItem\fP & A, const \fBSkillItem\fP & B)"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
