.TH "D:/Prog/AnpanMMO/Server/AnpanMMOServer/TypeDefs.h" 3 "2018年12月20日(木)" "GameServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Prog/AnpanMMO/Server/AnpanMMOServer/TypeDefs.h
.SH SYNOPSIS
.br
.PP
.SS "型定義"

.in +1c
.ti -1c
.RI "typedef char \fBs8\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBu8\fP"
.br
.ti -1c
.RI "typedef short \fBs16\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBu16\fP"
.br
.ti -1c
.RI "typedef int \fBs32\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBu32\fP"
.br
.in -1c
.SH "型定義詳解"
.PP 
.SS "typedef short \fBs16\fP"

.SS "typedef int \fBs32\fP"

.SS "typedef char \fBs8\fP"

.SS "typedef unsigned short \fBu16\fP"

.SS "typedef unsigned int \fBu32\fP"

.SS "typedef unsigned char \fBu8\fP"

.SH "著者"
.PP 
 GameServerのソースコードから抽出しました。
